//! Bubbleberry color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Bubbleberry
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Bubbleberry",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x202020),
    fg: Color::from_hex(0xcccccc),
    cursor: Some(Color::from_hex(0xeeeeee)),
    selection: Some(Color::from_hex(0x151515)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x777777)),
    statusbar_bg: Some(Color::from_hex(0x191919)),
    statusbar_fg: Some(Color::from_hex(0xbbbbbb)),
    comment: Some(Color::from_hex(0x9aaccb)),
    keyword: Some(Color::from_hex(0xb8e9cb)),
    string: Some(Color::from_hex(0xb3dadc)),
    function: Some(Color::from_hex(0xadcefd)),
    variable: Some(Color::from_hex(0xadcefd)),
    r#type: Some(Color::from_hex(0xc5b3fd)),
    constant: Some(Color::from_hex(0xc5b3fd)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xb3dadc)),
    cyan: Some(Color::from_hex(0xc5b3fd)),
    blue: Some(Color::from_hex(0xadcefd)),
    purple: Some(Color::from_hex(0xb8e9cb)),
    magenta: Some(Color::from_hex(0xadcefd)),
};
