//! Dakrone color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Dakrone
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Dakrone",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1c1c1c),
    fg: Color::from_hex(0xfff8dc),
    cursor: None,
    selection: Some(Color::from_hex(0x333333)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x333333)),
    statusbar_bg: Some(Color::from_hex(0x4b8bb0)),
    statusbar_fg: Some(Color::from_hex(0xbfebbf)),
    comment: Some(Color::from_hex(0x656763)),
    keyword: Some(Color::from_hex(0x729fcf)),
    string: Some(Color::from_hex(0x8ae234)),
    function: Some(Color::from_hex(0x00ffff)),
    variable: Some(Color::from_hex(0x00ffff)),
    r#type: Some(Color::from_hex(0xedd400)),
    constant: Some(Color::from_hex(0xfa8072)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x8ae234)),
    cyan: Some(Color::from_hex(0xfa8072)),
    blue: Some(Color::from_hex(0x00ffff)),
    purple: Some(Color::from_hex(0x729fcf)),
    magenta: Some(Color::from_hex(0x00ffff)),
};
