//! Dark Pink color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Dark Pink
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Dark Pink",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x101010),
    fg: Color::from_hex(0xcccccc),
    cursor: Some(Color::from_hex(0xcccccc)),
    selection: Some(Color::from_hex(0x412b3f)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x787878)),
    statusbar_bg: Some(Color::from_hex(0x2b2b2b)),
    statusbar_fg: Some(Color::from_hex(0xd1afdd)),
    comment: Some(Color::from_hex(0x755273)),
    keyword: Some(Color::from_hex(0xd1afdd)),
    string: Some(Color::from_hex(0xa582a3)),
    function: Some(Color::from_hex(0xefefef)),
    variable: Some(Color::from_hex(0x787878)),
    r#type: Some(Color::from_hex(0xe0e0e0)),
    constant: Some(Color::from_hex(0xb294bb)),
    operator: None,
    tag: None,
    error: None,
    warning: Some(Color::from_hex(0xf0dfff)),
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xf0dfff)),
    green: Some(Color::from_hex(0xa582a3)),
    cyan: Some(Color::from_hex(0xb294bb)),
    blue: Some(Color::from_hex(0xefefef)),
    purple: Some(Color::from_hex(0xd1afdd)),
    magenta: Some(Color::from_hex(0x787878)),
};
