//! Dark Krystal color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Dark Krystal
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Dark Krystal",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0c0c13),
    fg: Color::from_hex(0xffffff),
    cursor: Some(Color::from_hex(0xd0c6c6)),
    selection: Some(Color::from_hex(0x172f4f)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x3d3d42)),
    statusbar_bg: Some(Color::from_hex(0x24242b)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0x4a496d)),
    keyword: Some(Color::from_hex(0x00b6ad)),
    string: Some(Color::from_hex(0x05df0d)),
    function: Some(Color::from_hex(0x00e3cb)),
    variable: None,
    r#type: None,
    constant: Some(Color::from_hex(0xc5060b)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x05df0d)),
    cyan: Some(Color::from_hex(0xc5060b)),
    blue: Some(Color::from_hex(0x00e3cb)),
    purple: Some(Color::from_hex(0x00b6ad)),
    magenta: None,
};
