//! Dark Blue2 color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Dark Blue2
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Dark Blue2"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x233b5a),
    fg: Color::from_hex(0xfff8dc),
    cursor: Some(Color::from_hex(0xffff00)),
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x66cdaa)),
    keyword: Some(Color::from_hex(0x00ffff)),
    string: Some(Color::from_hex(0x7fffd4)),
    function: Some(Color::from_hex(0x87cefa)),
    variable: None,
    r#type: Some(Color::from_hex(0x98fb98)),
    constant: Some(Color::from_hex(0x7fffd4)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x7fffd4)),
    cyan: Some(Color::from_hex(0x7fffd4)),
    blue: Some(Color::from_hex(0x87cefa)),
    purple: Some(Color::from_hex(0x00ffff)),
    magenta: None,
};
