//! Deep Blue color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Deep Blue
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Deep Blue"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x102e4e),
    fg: Color::from_hex(0xeeeeee),
    cursor: Some(Color::from_hex(0x008000)),
    selection: Some(Color::from_hex(0x008b8b)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x5f9ea0)),
    keyword: None,
    string: Some(Color::from_hex(0xdeb887)),
    function: Some(Color::from_hex(0xdaa520)),
    variable: None,
    r#type: None,
    constant: Some(Color::from_hex(0xffd700)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xdeb887)),
    cyan: Some(Color::from_hex(0xffd700)),
    blue: Some(Color::from_hex(0xdaa520)),
    purple: None,
    magenta: None,
};
