//! Deep Thought color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Deep Thought
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Deep Thought",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xffffff),
    cursor: Some(Color::from_hex(0x3748a0)),
    selection: Some(Color::from_hex(0x102530)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x203047)),
    statusbar_bg: Some(Color::from_hex(0x001520)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0x105f89)),
    keyword: Some(Color::from_hex(0x1a8da7)),
    string: Some(Color::from_hex(0x10adee)),
    function: Some(Color::from_hex(0x1083be)),
    variable: Some(Color::from_hex(0x1e8eb8)),
    r#type: Some(Color::from_hex(0x1f5e8a)),
    constant: Some(Color::from_hex(0x1a99e7)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x10adee)),
    cyan: Some(Color::from_hex(0x1a99e7)),
    blue: Some(Color::from_hex(0x1083be)),
    purple: Some(Color::from_hex(0x1a8da7)),
    magenta: Some(Color::from_hex(0x1e8eb8)),
};
