//! Desert color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Desert
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Desert"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x333333),
    fg: Color::from_hex(0xf8f8ff),
    cursor: Some(Color::from_hex(0xf0e68c)),
    selection: Some(Color::from_hex(0x6b8e23)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0xffff00)),
    statusbar_bg: Some(Color::from_hex(0x262626)),
    statusbar_fg: Some(Color::from_hex(0x999999)),
    comment: None,
    keyword: Some(Color::from_hex(0xf0e68c)),
    string: Some(Color::from_hex(0xffa0a0)),
    function: None,
    variable: Some(Color::from_hex(0xf8f8ff)),
    r#type: None,
    constant: Some(Color::from_hex(0xffa0a0)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffc0cb)),
    warning: Some(Color::from_hex(0xff8c00)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffc0cb)),
    orange: None,
    yellow: Some(Color::from_hex(0xff8c00)),
    green: Some(Color::from_hex(0xffa0a0)),
    cyan: Some(Color::from_hex(0xffa0a0)),
    blue: None,
    purple: Some(Color::from_hex(0xf0e68c)),
    magenta: Some(Color::from_hex(0xf8f8ff)),
};
