//! Feng Shui color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Feng Shui
///
/// Variant: Light
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Feng Shui"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xfffff0),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x6a5acd)),
    selection: Some(Color::from_hex(0xe6e6fa)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xffe4e1)),
    statusbar_fg: Some(Color::from_hex(0x000080)),
    comment: None,
    keyword: Some(Color::from_hex(0x0000ff)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x000000)),
    r#type: Some(Color::from_hex(0x000000)),
    constant: Some(Color::from_hex(0x00008b)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: None,
    cyan: Some(Color::from_hex(0x00008b)),
    blue: None,
    purple: Some(Color::from_hex(0x0000ff)),
    magenta: Some(Color::from_hex(0x000000)),
};
