//! Gray1 color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Gray1
///
/// Variant: Dark
/// Contrast: Normal
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Gray1"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xa9a9a9),
    fg: Color::from_hex(0x000000),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0xff0000)),
    string: Some(Color::from_hex(0xff0000)),
    function: None,
    variable: None,
    r#type: Some(Color::from_hex(0xffffff)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xff0000)),
    cyan: Some(Color::from_hex(0xffffff)),
    blue: None,
    purple: Some(Color::from_hex(0xff0000)),
    magenta: None,
};
