//! Heroku color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Heroku
///
/// Variant: Dark
/// Contrast: Normal
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Heroku"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x3f464c),
    fg: Color::from_hex(0xeeeeec),
    cursor: Some(Color::from_hex(0xfce94f)),
    selection: Some(Color::from_hex(0x6c91be)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xbdbdbd)),
    statusbar_fg: Some(Color::from_hex(0x030303)),
    comment: Some(Color::from_hex(0xaeaeae)),
    keyword: Some(Color::from_hex(0xfbde2d)),
    string: Some(Color::from_hex(0xadc6ee)),
    function: Some(Color::from_hex(0xffffff)),
    variable: Some(Color::from_hex(0xfbde2d)),
    r#type: Some(Color::from_hex(0xffffff)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xadc6ee)),
    cyan: Some(Color::from_hex(0xffffff)),
    blue: Some(Color::from_hex(0xffffff)),
    purple: Some(Color::from_hex(0xfbde2d)),
    magenta: Some(Color::from_hex(0xfbde2d)),
};
