//! Infodoc color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Infodoc
///
/// Variant: Light
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Infodoc",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xf5deb3),
    fg: Color::from_hex(0x000000),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: None,
    keyword: Some(Color::from_hex(0x9932cc)),
    string: Some(Color::from_hex(0xb8860b)),
    function: None,
    variable: Some(Color::from_hex(0xd2691e)),
    r#type: Some(Color::from_hex(0xa52a2a)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xb8860b)),
    cyan: Some(Color::from_hex(0xa52a2a)),
    blue: None,
    purple: Some(Color::from_hex(0x9932cc)),
    magenta: Some(Color::from_hex(0xd2691e)),
};
