//! Lawrence color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Lawrence
///
/// Variant: Dark
/// Contrast: Normal
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Lawrence",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0x00cc00),
    cursor: Some(Color::from_hex(0x008000)),
    selection: Some(Color::from_hex(0x2e8b57)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0x404040)),
    statusbar_fg: Some(Color::from_hex(0x008000)),
    comment: Some(Color::from_hex(0x00fa9a)),
    keyword: Some(Color::from_hex(0x008000)),
    string: Some(Color::from_hex(0x2e8b57)),
    function: Some(Color::from_hex(0x00cc00)),
    variable: None,
    r#type: None,
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x2e8b57)),
    cyan: None,
    blue: Some(Color::from_hex(0x00cc00)),
    purple: Some(Color::from_hex(0x008000)),
    magenta: None,
};
