//! Lush color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Lush
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Lush",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0c1021),
    fg: Color::from_hex(0xe0e0e0),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0x333333)),
    statusbar_fg: Some(Color::from_hex(0xf0f0f0)),
    comment: Some(Color::from_hex(0x2aa198)),
    keyword: Some(Color::from_hex(0xffe329)),
    string: Some(Color::from_hex(0x61ce3c)),
    function: Some(Color::from_hex(0xff88ff)),
    variable: Some(Color::from_hex(0xfa583f)),
    r#type: Some(Color::from_hex(0x82a6df)),
    constant: Some(Color::from_hex(0xff951b)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x61ce3c)),
    cyan: Some(Color::from_hex(0xff951b)),
    blue: Some(Color::from_hex(0xff88ff)),
    purple: Some(Color::from_hex(0xffe329)),
    magenta: Some(Color::from_hex(0xfa583f)),
};
