//! Marine color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Marine
///
/// Variant: Light
/// Contrast: Normal
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Marine"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x9dcec9),
    fg: Color::from_hex(0x2f4f4f),
    cursor: None,
    selection: Some(Color::from_hex(0x0000ff)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x5f9ea0)),
    keyword: Some(Color::from_hex(0x800080)),
    string: Some(Color::from_hex(0x4169e1)),
    function: None,
    variable: None,
    r#type: Some(Color::from_hex(0x8b008b)),
    constant: Some(Color::from_hex(0xff4500)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x4169e1)),
    cyan: Some(Color::from_hex(0xff4500)),
    blue: None,
    purple: Some(Color::from_hex(0x800080)),
    magenta: None,
};
