//! Mellow color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Mellow
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Mellow",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x36312c),
    fg: Color::from_hex(0xf8f8f2),
    cursor: Some(Color::from_hex(0xf8f8f0)),
    selection: Some(Color::from_hex(0x161a1f)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x5d5954)),
    statusbar_bg: Some(Color::from_hex(0x494540)),
    statusbar_fg: Some(Color::from_hex(0xf8f8f2)),
    comment: Some(Color::from_hex(0x7a7267)),
    keyword: Some(Color::from_hex(0xf2bc79)),
    string: Some(Color::from_hex(0xf8bb39)),
    function: Some(Color::from_hex(0xf28972)),
    variable: None,
    r#type: Some(Color::from_hex(0xf8bb39)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xf8bb39)),
    cyan: Some(Color::from_hex(0xf8bb39)),
    blue: Some(Color::from_hex(0xf28972)),
    purple: Some(Color::from_hex(0xf2bc79)),
    magenta: None,
};
