//! Parus color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Parus
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Parus"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x00005a),
    fg: Color::from_hex(0xffffff),
    cursor: None,
    selection: Some(Color::from_hex(0x0000ff)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0xffd1d1)),
    keyword: Some(Color::from_hex(0xa0ffff)),
    string: Some(Color::from_hex(0xefca10)),
    function: Some(Color::from_hex(0xb2e4ff)),
    variable: None,
    r#type: Some(Color::from_hex(0x98fb98)),
    constant: Some(Color::from_hex(0x7fffd4)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xefca10)),
    cyan: Some(Color::from_hex(0x7fffd4)),
    blue: Some(Color::from_hex(0xb2e4ff)),
    purple: Some(Color::from_hex(0xa0ffff)),
    magenta: None,
};
