//! Railscasts color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Railscasts
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Railscasts",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x232323),
    fg: Color::from_hex(0xe6e1dc),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x555577)),
    line_highlight: Some(Color::from_hex(0x2a2a2a)),
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xcdcdcd)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xbc9458)),
    keyword: Some(Color::from_hex(0xcc7833)),
    string: Some(Color::from_hex(0xa5c261)),
    function: Some(Color::from_hex(0xffc66d)),
    variable: Some(Color::from_hex(0xc8c8ff)),
    r#type: Some(Color::from_hex(0x6d9cbe)),
    constant: Some(Color::from_hex(0x6d9cbe)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xa5c261)),
    cyan: Some(Color::from_hex(0x6d9cbe)),
    blue: Some(Color::from_hex(0xffc66d)),
    purple: Some(Color::from_hex(0xcc7833)),
    magenta: Some(Color::from_hex(0xc8c8ff)),
};
