//! Sitaramv Nt color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Sitaramv Nt
///
/// Variant: Light
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Sitaramv Nt"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x228b22)),
    keyword: Some(Color::from_hex(0x0000ff)),
    string: Some(Color::from_hex(0xff0000)),
    function: Some(Color::from_hex(0x8b008b)),
    variable: Some(Color::from_hex(0x000000)),
    r#type: Some(Color::from_hex(0x0000ff)),
    constant: Some(Color::from_hex(0x5f9ea0)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xff0000)),
    cyan: Some(Color::from_hex(0x5f9ea0)),
    blue: Some(Color::from_hex(0x8b008b)),
    purple: Some(Color::from_hex(0x0000ff)),
    magenta: Some(Color::from_hex(0x000000)),
};
