//! Tangotango color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Tangotango
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Tangotango"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x2e3434),
    fg: Color::from_hex(0xeeeeec),
    cursor: Some(Color::from_hex(0xfce94f)),
    selection: Some(Color::from_hex(0x483d8b)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0x222222)),
    statusbar_fg: Some(Color::from_hex(0xbbbbbc)),
    comment: Some(Color::from_hex(0x888a85)),
    keyword: Some(Color::from_hex(0x729fcf)),
    string: Some(Color::from_hex(0xad7fa8)),
    function: Some(Color::from_hex(0xedd400)),
    variable: Some(Color::from_hex(0xff6347)),
    r#type: Some(Color::from_hex(0x8ae234)),
    constant: Some(Color::from_hex(0x8ae234)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xad7fa8)),
    cyan: Some(Color::from_hex(0x8ae234)),
    blue: Some(Color::from_hex(0xedd400)),
    purple: Some(Color::from_hex(0x729fcf)),
    magenta: Some(Color::from_hex(0xff6347)),
};
