//! Tron color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Tron
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Tron",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xb0c7d4),
    cursor: None,
    selection: Some(Color::from_hex(0x356a9c)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0x99bac7)),
    statusbar_fg: Some(Color::from_hex(0x072d40)),
    comment: Some(Color::from_hex(0x575b5b)),
    keyword: Some(Color::from_hex(0xa4cee5)),
    string: Some(Color::from_hex(0xe8b778)),
    function: Some(Color::from_hex(0xec9346)),
    variable: Some(Color::from_hex(0x9ebbc2)),
    r#type: Some(Color::from_hex(0x74abbe)),
    constant: Some(Color::from_hex(0xeeedec)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xe8b778)),
    cyan: Some(Color::from_hex(0xeeedec)),
    blue: Some(Color::from_hex(0xec9346)),
    purple: Some(Color::from_hex(0xa4cee5)),
    magenta: Some(Color::from_hex(0x9ebbc2)),
};
