//! Twilight color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Twilight
///
/// Variant: Dark
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Twilight",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x141414),
    fg: Color::from_hex(0xf8f8f8),
    cursor: Some(Color::from_hex(0xa7a7a7)),
    selection: Some(Color::from_hex(0x27292a)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xbfbfbf)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x5f5a60)),
    keyword: Some(Color::from_hex(0xcda869)),
    string: Some(Color::from_hex(0x8f9d6a)),
    function: Some(Color::from_hex(0x9b703f)),
    variable: Some(Color::from_hex(0x7587a6)),
    r#type: Some(Color::from_hex(0x9b703f)),
    constant: Some(Color::from_hex(0xcf6a4c)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x8f9d6a)),
    cyan: Some(Color::from_hex(0xcf6a4c)),
    blue: Some(Color::from_hex(0x9b703f)),
    purple: Some(Color::from_hex(0xcda869)),
    magenta: Some(Color::from_hex(0x7587a6)),
};
