//! Vim Colors color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Vim Colors
///
/// Variant: Light
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: "Vim Colors",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x000000)),
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xbfbfbf)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: None,
    keyword: Some(Color::from_hex(0xa52a2a)),
    string: Some(Color::from_hex(0xff00ff)),
    function: Some(Color::from_hex(0x008b8b)),
    variable: Some(Color::from_hex(0x008b8b)),
    r#type: Some(Color::from_hex(0x228b22)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xff00ff)),
    cyan: Some(Color::from_hex(0x228b22)),
    blue: Some(Color::from_hex(0x008b8b)),
    purple: Some(Color::from_hex(0xa52a2a)),
    magenta: Some(Color::from_hex(0x008b8b)),
};
