//! Whateveryouwant color theme.
//!
//! Auto-generated by `cargo xtask generate emacs` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Whateveryouwant
///
/// Variant: Light
/// Contrast: High
/// Source: emacs (emacs-themes-site)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Whateveryouwant"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x000000)),
    selection: Some(Color::from_hex(0xaa0000)),
    line_highlight: None,
    gutter: None,
    statusbar_bg: Some(Color::from_hex(0xe5e5e5)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xcc0000)),
    keyword: None,
    string: Some(Color::from_hex(0x000080)),
    function: Some(Color::from_hex(0x000080)),
    variable: Some(Color::from_hex(0x000000)),
    r#type: Some(Color::from_hex(0x000000)),
    constant: Some(Color::from_hex(0x5f9ea0)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0x000080)),
    cyan: Some(Color::from_hex(0x5f9ea0)),
    blue: Some(Color::from_hex(0x000080)),
    purple: None,
    magenta: Some(Color::from_hex(0x000000)),
};
