//! Alien Blood color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Alien Blood
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Low
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Alien Blood"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x0f160f),
    fg: Color::from_hex(0x5a6f5c),
    cursor: Some(Color::from_hex(0x5a6f5c)),
    selection: Some(Color::from_hex(0x3c4711)),
    line_highlight: Some(Color::from_hex(0x112615)),
    gutter: Some(Color::from_hex(0x46542a)),
    statusbar_bg: Some(Color::from_hex(0x112615)),
    statusbar_fg: Some(Color::from_hex(0x506243)),
    comment: Some(Color::from_hex(0x46542a)),
    keyword: Some(Color::from_hex(0x47577e)),
    string: Some(Color::from_hex(0x2f7e25)),
    function: Some(Color::from_hex(0x2f697f)),
    variable: Some(Color::from_hex(0x7f2b26)),
    r#type: Some(Color::from_hex(0x00a9df)),
    constant: Some(Color::from_hex(0x707f23)),
    operator: Some(Color::from_hex(0x5a6f5c)),
    tag: Some(Color::from_hex(0x7f2b26)),
    error: Some(Color::from_hex(0x7f2b26)),
    warning: Some(Color::from_hex(0x00a9df)),
    info: Some(Color::from_hex(0x2f697f)),
    success: Some(Color::from_hex(0x2f7e25)),
    red: Some(Color::from_hex(0xdf8008)),
    orange: Some(Color::from_hex(0x707f23)),
    yellow: Some(Color::from_hex(0xbde000)),
    green: Some(Color::from_hex(0x18e000)),
    cyan: Some(Color::from_hex(0x317f76)),
    blue: Some(Color::from_hex(0x00dfc3)),
    purple: Some(Color::from_hex(0x00a9df)),
    magenta: Some(Color::from_hex(0x0058df)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x0f160f),
        base01: Color::from_hex(0x112615),
        base02: Color::from_hex(0x3c4711),
        base03: Color::from_hex(0x46542a),
        base04: Color::from_hex(0x506243),
        base05: Color::from_hex(0x5a6f5c),
        base06: Color::from_hex(0x647d75),
        base07: Color::from_hex(0x73f990),
        base08: Color::from_hex(0x7f2b26),
        base09: Color::from_hex(0x707f23),
        base0a: Color::from_hex(0x00a9df),
        base0b: Color::from_hex(0x2f7e25),
        base0c: Color::from_hex(0x317f76),
        base0d: Color::from_hex(0x2f697f),
        base0e: Color::from_hex(0x47577e),
        base0f: Color::from_hex(0x3f1513),
    },
    base10: Color::from_hex(0x282f0b),
    base11: Color::from_hex(0x141705),
    base12: Color::from_hex(0xdf8008),
    base13: Color::from_hex(0xbde000),
    base14: Color::from_hex(0x18e000),
    base15: Color::from_hex(0x00dfc3),
    base16: Color::from_hex(0x00a9df),
    base17: Color::from_hex(0x0058df),
};
