//! Ayu Light color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Ayu Light
///
/// Author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
/// Variant: Light
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Ayu Light"),
    author: Cow::Borrowed(
        "Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)",
    ),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf8f9fa),
    fg: Color::from_hex(0x5c6166),
    cursor: Some(Color::from_hex(0x5c6166)),
    selection: Some(Color::from_hex(0xd2d4d8)),
    line_highlight: Some(Color::from_hex(0xedeff1)),
    gutter: Some(Color::from_hex(0xa0a6ac)),
    statusbar_bg: Some(Color::from_hex(0xedeff1)),
    statusbar_fg: Some(Color::from_hex(0x8a9199)),
    comment: Some(Color::from_hex(0xa0a6ac)),
    keyword: Some(Color::from_hex(0xa37acc)),
    string: Some(Color::from_hex(0x6cbf49)),
    function: Some(Color::from_hex(0x399ee6)),
    variable: Some(Color::from_hex(0xf07171)),
    r#type: Some(Color::from_hex(0xf2ae49)),
    constant: Some(Color::from_hex(0xfa8d3e)),
    operator: Some(Color::from_hex(0x5c6166)),
    tag: Some(Color::from_hex(0xf07171)),
    error: Some(Color::from_hex(0xf07171)),
    warning: Some(Color::from_hex(0xf2ae49)),
    info: Some(Color::from_hex(0x399ee6)),
    success: Some(Color::from_hex(0x6cbf49)),
    red: Some(Color::from_hex(0xff7383)),
    orange: Some(Color::from_hex(0xfa8d3e)),
    yellow: Some(Color::from_hex(0xffaa33)),
    green: Some(Color::from_hex(0x86b300)),
    cyan: Some(Color::from_hex(0x4cbf99)),
    blue: Some(Color::from_hex(0x55b4d4)),
    purple: Some(Color::from_hex(0x478acc)),
    magenta: Some(Color::from_hex(0xb595d6)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0xf8f9fa),
        base01: Color::from_hex(0xedeff1),
        base02: Color::from_hex(0xd2d4d8),
        base03: Color::from_hex(0xa0a6ac),
        base04: Color::from_hex(0x8a9199),
        base05: Color::from_hex(0x5c6166),
        base06: Color::from_hex(0x4e5257),
        base07: Color::from_hex(0x404447),
        base08: Color::from_hex(0xf07171),
        base09: Color::from_hex(0xfa8d3e),
        base0a: Color::from_hex(0xf2ae49),
        base0b: Color::from_hex(0x6cbf49),
        base0c: Color::from_hex(0x4cbf99),
        base0d: Color::from_hex(0x399ee6),
        base0e: Color::from_hex(0xa37acc),
        base0f: Color::from_hex(0xe6ba7e),
    },
    base10: Color::from_hex(0xf9f9f9),
    base11: Color::from_hex(0xffffff),
    base12: Color::from_hex(0xff7383),
    base13: Color::from_hex(0xffaa33),
    base14: Color::from_hex(0x86b300),
    base15: Color::from_hex(0x55b4d4),
    base16: Color::from_hex(0x478acc),
    base17: Color::from_hex(0xb595d6),
};
