//! Ayu Dark color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Ayu Dark
///
/// Author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Ayu Dark",
    author: "Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0b0e14),
    fg: Color::from_hex(0xe6e1cf),
    cursor: Some(Color::from_hex(0xe6e1cf)),
    selection: Some(Color::from_hex(0x202229)),
    line_highlight: Some(Color::from_hex(0x131721)),
    gutter: Some(Color::from_hex(0x3e4b59)),
    statusbar_bg: Some(Color::from_hex(0x131721)),
    statusbar_fg: Some(Color::from_hex(0xbfbdb6)),
    comment: Some(Color::from_hex(0x3e4b59)),
    keyword: Some(Color::from_hex(0xd2a6ff)),
    string: Some(Color::from_hex(0xaad94c)),
    function: Some(Color::from_hex(0x59c2ff)),
    variable: Some(Color::from_hex(0xf07178)),
    r#type: Some(Color::from_hex(0xffb454)),
    constant: Some(Color::from_hex(0xff8f40)),
    operator: Some(Color::from_hex(0xe6e1cf)),
    tag: Some(Color::from_hex(0xf07178)),
    error: Some(Color::from_hex(0xf07178)),
    warning: Some(Color::from_hex(0xffb454)),
    info: Some(Color::from_hex(0x59c2ff)),
    success: Some(Color::from_hex(0xaad94c)),
    red: Some(Color::from_hex(0xf26d78)),
    orange: Some(Color::from_hex(0xff8f40)),
    yellow: Some(Color::from_hex(0xe6b673)),
    green: Some(Color::from_hex(0x7fd962)),
    cyan: Some(Color::from_hex(0x95e6cb)),
    blue: Some(Color::from_hex(0x39bae6)),
    purple: Some(Color::from_hex(0x73b8ff)),
    magenta: Some(Color::from_hex(0xddbcff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x0b0e14),
        base01: Color::from_hex(0x131721),
        base02: Color::from_hex(0x202229),
        base03: Color::from_hex(0x3e4b59),
        base04: Color::from_hex(0xbfbdb6),
        base05: Color::from_hex(0xe6e1cf),
        base06: Color::from_hex(0xece8db),
        base07: Color::from_hex(0xf2f0e7),
        base08: Color::from_hex(0xf07178),
        base09: Color::from_hex(0xff8f40),
        base0a: Color::from_hex(0xffb454),
        base0b: Color::from_hex(0xaad94c),
        base0c: Color::from_hex(0x95e6cb),
        base0d: Color::from_hex(0x59c2ff),
        base0e: Color::from_hex(0xd2a6ff),
        base0f: Color::from_hex(0xe6b450),
    },
    base10: Color::from_hex(0x0a0d13),
    base11: Color::from_hex(0x06070a),
    base12: Color::from_hex(0xf26d78),
    base13: Color::from_hex(0xe6b673),
    base14: Color::from_hex(0x7fd962),
    base15: Color::from_hex(0x39bae6),
    base16: Color::from_hex(0x73b8ff),
    base17: Color::from_hex(0xddbcff),
};
