//! Bluloco Light color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Bluloco Light
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Light
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Bluloco Light",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xf7f7f7),
    fg: Color::from_hex(0x38383a),
    cursor: Some(Color::from_hex(0x38383a)),
    selection: Some(Color::from_hex(0xdddee8)),
    line_highlight: Some(Color::from_hex(0xcbccd4)),
    gutter: Some(Color::from_hex(0xa6a7ae)),
    statusbar_bg: Some(Color::from_hex(0xcbccd4)),
    statusbar_fg: Some(Color::from_hex(0x6f6f74)),
    comment: Some(Color::from_hex(0xa6a7ae)),
    keyword: Some(Color::from_hex(0x6d1bed)),
    string: Some(Color::from_hex(0x208839)),
    function: Some(Color::from_hex(0x1d44dd)),
    variable: Some(Color::from_hex(0xc80d41)),
    r#type: Some(Color::from_hex(0x1085d9)),
    constant: Some(Color::from_hex(0xd44d16)),
    operator: Some(Color::from_hex(0x38383a)),
    tag: Some(Color::from_hex(0xc80d41)),
    error: Some(Color::from_hex(0xc80d41)),
    warning: Some(Color::from_hex(0x1085d9)),
    info: Some(Color::from_hex(0x1d44dd)),
    success: Some(Color::from_hex(0x208839)),
    red: Some(Color::from_hex(0xfb496d)),
    orange: Some(Color::from_hex(0xd44d16)),
    yellow: Some(Color::from_hex(0xb79326)),
    green: Some(Color::from_hex(0x34b253)),
    cyan: Some(Color::from_hex(0x1e4d7a)),
    blue: Some(Color::from_hex(0x5a7fac)),
    purple: Some(Color::from_hex(0x1085d9)),
    magenta: Some(Color::from_hex(0xc00cb2)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0xf7f7f7),
        base01: Color::from_hex(0xcbccd4),
        base02: Color::from_hex(0xdddee8),
        base03: Color::from_hex(0xa6a7ae),
        base04: Color::from_hex(0x6f6f74),
        base05: Color::from_hex(0x38383a),
        base06: Color::from_hex(0x000000),
        base07: Color::from_hex(0x1c1d21),
        base08: Color::from_hex(0xc80d41),
        base09: Color::from_hex(0xd44d16),
        base0a: Color::from_hex(0x1085d9),
        base0b: Color::from_hex(0x208839),
        base0c: Color::from_hex(0x1e4d7a),
        base0d: Color::from_hex(0x1d44dd),
        base0e: Color::from_hex(0x6d1bed),
        base0f: Color::from_hex(0x640620),
    },
    base10: Color::from_hex(0x93949a),
    base11: Color::from_hex(0x494a4d),
    base12: Color::from_hex(0xfb496d),
    base13: Color::from_hex(0xb79326),
    base14: Color::from_hex(0x34b253),
    base15: Color::from_hex(0x5a7fac),
    base16: Color::from_hex(0x1085d9),
    base17: Color::from_hex(0xc00cb2),
};
