//! Broadcast color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Broadcast
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Broadcast",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2b2b2b),
    fg: Color::from_hex(0xcbcbcb),
    cursor: Some(Color::from_hex(0xcbcbcb)),
    selection: Some(Color::from_hex(0x323232)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x656565)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x989898)),
    comment: Some(Color::from_hex(0x656565)),
    keyword: Some(Color::from_hex(0xd0d0ff)),
    string: Some(Color::from_hex(0x519f50)),
    function: Some(Color::from_hex(0x6d9cbe)),
    variable: Some(Color::from_hex(0xda4939)),
    r#type: Some(Color::from_hex(0x9fcef0)),
    constant: Some(Color::from_hex(0xffd24a)),
    operator: Some(Color::from_hex(0xcbcbcb)),
    tag: Some(Color::from_hex(0xda4939)),
    error: Some(Color::from_hex(0xda4939)),
    warning: Some(Color::from_hex(0x9fcef0)),
    info: Some(Color::from_hex(0x6d9cbe)),
    success: Some(Color::from_hex(0x519f50)),
    red: Some(Color::from_hex(0xff7b6b)),
    orange: Some(Color::from_hex(0xffd24a)),
    yellow: Some(Color::from_hex(0xffff7c)),
    green: Some(Color::from_hex(0x83d182)),
    cyan: Some(Color::from_hex(0x6e9cbe)),
    blue: Some(Color::from_hex(0xa0cef0)),
    purple: Some(Color::from_hex(0x9fcef0)),
    magenta: Some(Color::from_hex(0xffffff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x2b2b2b),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x323232),
        base03: Color::from_hex(0x656565),
        base04: Color::from_hex(0x989898),
        base05: Color::from_hex(0xcbcbcb),
        base06: Color::from_hex(0xffffff),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xda4939),
        base09: Color::from_hex(0xffd24a),
        base0a: Color::from_hex(0x9fcef0),
        base0b: Color::from_hex(0x519f50),
        base0c: Color::from_hex(0x6e9cbe),
        base0d: Color::from_hex(0x6d9cbe),
        base0e: Color::from_hex(0xd0d0ff),
        base0f: Color::from_hex(0x6d241c),
    },
    base10: Color::from_hex(0x212121),
    base11: Color::from_hex(0x101010),
    base12: Color::from_hex(0xff7b6b),
    base13: Color::from_hex(0xffff7c),
    base14: Color::from_hex(0x83d182),
    base15: Color::from_hex(0xa0cef0),
    base16: Color::from_hex(0x9fcef0),
    base17: Color::from_hex(0xffffff),
};
