//! Builtin Solarized Light color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Builtin Solarized Light
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Light
/// Contrast: Low
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Builtin Solarized Light",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Light,
    contrast: Contrast::Low,
    bg: Color::from_hex(0xfdf6e3),
    fg: Color::from_hex(0xb2b8ad),
    cursor: Some(Color::from_hex(0xb2b8ad)),
    selection: Some(Color::from_hex(0x002b36)),
    line_highlight: Some(Color::from_hex(0x073642)),
    gutter: Some(Color::from_hex(0x3b5a5d)),
    statusbar_bg: Some(Color::from_hex(0x073642)),
    statusbar_fg: Some(Color::from_hex(0x778985)),
    comment: Some(Color::from_hex(0x3b5a5d)),
    keyword: Some(Color::from_hex(0xd33682)),
    string: Some(Color::from_hex(0x859900)),
    function: Some(Color::from_hex(0x268bd2)),
    variable: Some(Color::from_hex(0xdc322f)),
    r#type: Some(Color::from_hex(0x839496)),
    constant: Some(Color::from_hex(0xb58900)),
    operator: Some(Color::from_hex(0xb2b8ad)),
    tag: Some(Color::from_hex(0xdc322f)),
    error: Some(Color::from_hex(0xdc322f)),
    warning: Some(Color::from_hex(0x839496)),
    info: Some(Color::from_hex(0x268bd2)),
    success: Some(Color::from_hex(0x859900)),
    red: Some(Color::from_hex(0xcb4b16)),
    orange: Some(Color::from_hex(0xb58900)),
    yellow: Some(Color::from_hex(0x657b83)),
    green: Some(Color::from_hex(0x586e75)),
    cyan: Some(Color::from_hex(0x2aa198)),
    blue: Some(Color::from_hex(0x93a1a1)),
    purple: Some(Color::from_hex(0x839496)),
    magenta: Some(Color::from_hex(0x6c71c4)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0xfdf6e3),
        base01: Color::from_hex(0x073642),
        base02: Color::from_hex(0x002b36),
        base03: Color::from_hex(0x3b5a5d),
        base04: Color::from_hex(0x778985),
        base05: Color::from_hex(0xb2b8ad),
        base06: Color::from_hex(0xeee8d5),
        base07: Color::from_hex(0xfdf6e3),
        base08: Color::from_hex(0xdc322f),
        base09: Color::from_hex(0xb58900),
        base0a: Color::from_hex(0x839496),
        base0b: Color::from_hex(0x859900),
        base0c: Color::from_hex(0x2aa198),
        base0d: Color::from_hex(0x268bd2),
        base0e: Color::from_hex(0xd33682),
        base0f: Color::from_hex(0x6e1917),
    },
    base10: Color::from_hex(0x001c24),
    base11: Color::from_hex(0x000e12),
    base12: Color::from_hex(0xcb4b16),
    base13: Color::from_hex(0x657b83),
    base14: Color::from_hex(0x586e75),
    base15: Color::from_hex(0x93a1a1),
    base16: Color::from_hex(0x839496),
    base17: Color::from_hex(0x6c71c4),
};
