//! Catppuccin Mocha color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Catppuccin Mocha
///
/// Author: https://github.com/catppuccin/catppuccin
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Catppuccin Mocha",
    author: "https://github.com/catppuccin/catppuccin",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1e1e2e),
    fg: Color::from_hex(0xcdd6f4),
    cursor: Some(Color::from_hex(0xcdd6f4)),
    selection: Some(Color::from_hex(0x313244)),
    line_highlight: Some(Color::from_hex(0x181825)),
    gutter: Some(Color::from_hex(0x45475a)),
    statusbar_bg: Some(Color::from_hex(0x181825)),
    statusbar_fg: Some(Color::from_hex(0x585b70)),
    comment: Some(Color::from_hex(0x45475a)),
    keyword: Some(Color::from_hex(0xcba6f7)),
    string: Some(Color::from_hex(0xa6e3a1)),
    function: Some(Color::from_hex(0x89b4fa)),
    variable: Some(Color::from_hex(0xf38ba8)),
    r#type: Some(Color::from_hex(0xf9e2af)),
    constant: Some(Color::from_hex(0xfab387)),
    operator: Some(Color::from_hex(0xcdd6f4)),
    tag: Some(Color::from_hex(0xf38ba8)),
    error: Some(Color::from_hex(0xf38ba8)),
    warning: Some(Color::from_hex(0xf9e2af)),
    info: Some(Color::from_hex(0x89b4fa)),
    success: Some(Color::from_hex(0xa6e3a1)),
    red: Some(Color::from_hex(0xeba0ac)),
    orange: Some(Color::from_hex(0xfab387)),
    yellow: Some(Color::from_hex(0xf5e0dc)),
    green: Some(Color::from_hex(0xa6e3a1)),
    cyan: Some(Color::from_hex(0x94e2d5)),
    blue: Some(Color::from_hex(0x89dceb)),
    purple: Some(Color::from_hex(0x74c7ec)),
    magenta: Some(Color::from_hex(0xf5c2e7)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1e1e2e),
        base01: Color::from_hex(0x181825),
        base02: Color::from_hex(0x313244),
        base03: Color::from_hex(0x45475a),
        base04: Color::from_hex(0x585b70),
        base05: Color::from_hex(0xcdd6f4),
        base06: Color::from_hex(0xf5e0dc),
        base07: Color::from_hex(0xb4befe),
        base08: Color::from_hex(0xf38ba8),
        base09: Color::from_hex(0xfab387),
        base0a: Color::from_hex(0xf9e2af),
        base0b: Color::from_hex(0xa6e3a1),
        base0c: Color::from_hex(0x94e2d5),
        base0d: Color::from_hex(0x89b4fa),
        base0e: Color::from_hex(0xcba6f7),
        base0f: Color::from_hex(0xf2cdcd),
    },
    base10: Color::from_hex(0x181825),
    base11: Color::from_hex(0x11111b),
    base12: Color::from_hex(0xeba0ac),
    base13: Color::from_hex(0xf5e0dc),
    base14: Color::from_hex(0xa6e3a1),
    base15: Color::from_hex(0x89dceb),
    base16: Color::from_hex(0x74c7ec),
    base17: Color::from_hex(0xf5c2e7),
};
