//! Catppuccin Macchiato color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Catppuccin Macchiato
///
/// Author: https://github.com/catppuccin/catppuccin
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Catppuccin Macchiato"),
    author: Cow::Borrowed("https://github.com/catppuccin/catppuccin"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x24273a),
    fg: Color::from_hex(0xcad3f5),
    cursor: Some(Color::from_hex(0xcad3f5)),
    selection: Some(Color::from_hex(0x363a4f)),
    line_highlight: Some(Color::from_hex(0x1e2030)),
    gutter: Some(Color::from_hex(0x494d64)),
    statusbar_bg: Some(Color::from_hex(0x1e2030)),
    statusbar_fg: Some(Color::from_hex(0x5b6078)),
    comment: Some(Color::from_hex(0x494d64)),
    keyword: Some(Color::from_hex(0xc6a0f6)),
    string: Some(Color::from_hex(0xa6da95)),
    function: Some(Color::from_hex(0x8aadf4)),
    variable: Some(Color::from_hex(0xed8796)),
    r#type: Some(Color::from_hex(0xeed49f)),
    constant: Some(Color::from_hex(0xf5a97f)),
    operator: Some(Color::from_hex(0xcad3f5)),
    tag: Some(Color::from_hex(0xed8796)),
    error: Some(Color::from_hex(0xed8796)),
    warning: Some(Color::from_hex(0xeed49f)),
    info: Some(Color::from_hex(0x8aadf4)),
    success: Some(Color::from_hex(0xa6da95)),
    red: Some(Color::from_hex(0xee99a0)),
    orange: Some(Color::from_hex(0xf5a97f)),
    yellow: Some(Color::from_hex(0xf4dbd6)),
    green: Some(Color::from_hex(0xa6da95)),
    cyan: Some(Color::from_hex(0x8bd5ca)),
    blue: Some(Color::from_hex(0x91d7e3)),
    purple: Some(Color::from_hex(0x7dc4e4)),
    magenta: Some(Color::from_hex(0xf5bde6)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x24273a),
        base01: Color::from_hex(0x1e2030),
        base02: Color::from_hex(0x363a4f),
        base03: Color::from_hex(0x494d64),
        base04: Color::from_hex(0x5b6078),
        base05: Color::from_hex(0xcad3f5),
        base06: Color::from_hex(0xf4dbd6),
        base07: Color::from_hex(0xb7bdf8),
        base08: Color::from_hex(0xed8796),
        base09: Color::from_hex(0xf5a97f),
        base0a: Color::from_hex(0xeed49f),
        base0b: Color::from_hex(0xa6da95),
        base0c: Color::from_hex(0x8bd5ca),
        base0d: Color::from_hex(0x8aadf4),
        base0e: Color::from_hex(0xc6a0f6),
        base0f: Color::from_hex(0xf0c6c6),
    },
    base10: Color::from_hex(0x1e2030),
    base11: Color::from_hex(0x181926),
    base12: Color::from_hex(0xee99a0),
    base13: Color::from_hex(0xf4dbd6),
    base14: Color::from_hex(0xa6da95),
    base15: Color::from_hex(0x91d7e3),
    base16: Color::from_hex(0x7dc4e4),
    base17: Color::from_hex(0xf5bde6),
};
