//! Ciapre color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Ciapre
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Ciapre"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x181c27),
    fg: Color::from_hex(0x978f73),
    cursor: Some(Color::from_hex(0x978f73)),
    selection: Some(Color::from_hex(0x555555)),
    line_highlight: Some(Color::from_hex(0x181818)),
    gutter: Some(Color::from_hex(0x6b685f)),
    statusbar_bg: Some(Color::from_hex(0x181818)),
    statusbar_fg: Some(Color::from_hex(0x817c69)),
    comment: Some(Color::from_hex(0x6b685f)),
    keyword: Some(Color::from_hex(0x724c7c)),
    string: Some(Color::from_hex(0x48513b)),
    function: Some(Color::from_hex(0x566d8c)),
    variable: Some(Color::from_hex(0x800009)),
    r#type: Some(Color::from_hex(0x2f97c6)),
    constant: Some(Color::from_hex(0xcc8a3e)),
    operator: Some(Color::from_hex(0x978f73)),
    tag: Some(Color::from_hex(0x800009)),
    error: Some(Color::from_hex(0x800009)),
    warning: Some(Color::from_hex(0x2f97c6)),
    info: Some(Color::from_hex(0x566d8c)),
    success: Some(Color::from_hex(0x48513b)),
    red: Some(Color::from_hex(0xab3834)),
    orange: Some(Color::from_hex(0xcc8a3e)),
    yellow: Some(Color::from_hex(0xdcde7b)),
    green: Some(Color::from_hex(0xa6a65d)),
    cyan: Some(Color::from_hex(0x5b4f4a)),
    blue: Some(Color::from_hex(0xf3dab1)),
    purple: Some(Color::from_hex(0x2f97c6)),
    magenta: Some(Color::from_hex(0xd33060)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x181c27),
        base01: Color::from_hex(0x181818),
        base02: Color::from_hex(0x555555),
        base03: Color::from_hex(0x6b685f),
        base04: Color::from_hex(0x817c69),
        base05: Color::from_hex(0x978f73),
        base06: Color::from_hex(0xada37e),
        base07: Color::from_hex(0xf3f3f3),
        base08: Color::from_hex(0x800009),
        base09: Color::from_hex(0xcc8a3e),
        base0a: Color::from_hex(0x2f97c6),
        base0b: Color::from_hex(0x48513b),
        base0c: Color::from_hex(0x5b4f4a),
        base0d: Color::from_hex(0x566d8c),
        base0e: Color::from_hex(0x724c7c),
        base0f: Color::from_hex(0x400004),
    },
    base10: Color::from_hex(0x383838),
    base11: Color::from_hex(0x1c1c1c),
    base12: Color::from_hex(0xab3834),
    base13: Color::from_hex(0xdcde7b),
    base14: Color::from_hex(0xa6a65d),
    base15: Color::from_hex(0xf3dab1),
    base16: Color::from_hex(0x2f97c6),
    base17: Color::from_hex(0xd33060),
};
