//! Cobalt Neon color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Cobalt Neon
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Cobalt Neon",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x142838),
    fg: Color::from_hex(0xcc72a6),
    cursor: Some(Color::from_hex(0xcc72a6)),
    selection: Some(Color::from_hex(0xfff688)),
    line_highlight: Some(Color::from_hex(0x142630)),
    gutter: Some(Color::from_hex(0xeeca92)),
    statusbar_bg: Some(Color::from_hex(0x142630)),
    statusbar_fg: Some(Color::from_hex(0xdd9e9c)),
    comment: Some(Color::from_hex(0xeeca92)),
    keyword: Some(Color::from_hex(0x781aa0)),
    string: Some(Color::from_hex(0x3aa5ff)),
    function: Some(Color::from_hex(0x8ff586)),
    variable: Some(Color::from_hex(0xff2320)),
    r#type: Some(Color::from_hex(0x3c7dd2)),
    constant: Some(Color::from_hex(0xe9e75c)),
    operator: Some(Color::from_hex(0xcc72a6)),
    tag: Some(Color::from_hex(0xff2320)),
    error: Some(Color::from_hex(0xff2320)),
    warning: Some(Color::from_hex(0x3c7dd2)),
    info: Some(Color::from_hex(0x8ff586)),
    success: Some(Color::from_hex(0x3aa5ff)),
    red: Some(Color::from_hex(0xd4312e)),
    orange: Some(Color::from_hex(0xe9e75c)),
    yellow: Some(Color::from_hex(0xe9f06d)),
    green: Some(Color::from_hex(0x8ff586)),
    cyan: Some(Color::from_hex(0x8ff586)),
    blue: Some(Color::from_hex(0x6cbc67)),
    purple: Some(Color::from_hex(0x3c7dd2)),
    magenta: Some(Color::from_hex(0x8230a7)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x142838),
        base01: Color::from_hex(0x142630),
        base02: Color::from_hex(0xfff688),
        base03: Color::from_hex(0xeeca92),
        base04: Color::from_hex(0xdd9e9c),
        base05: Color::from_hex(0xcc72a6),
        base06: Color::from_hex(0xba45b1),
        base07: Color::from_hex(0x8ff586),
        base08: Color::from_hex(0xff2320),
        base09: Color::from_hex(0xe9e75c),
        base0a: Color::from_hex(0x3c7dd2),
        base0b: Color::from_hex(0x3aa5ff),
        base0c: Color::from_hex(0x8ff586),
        base0d: Color::from_hex(0x8ff586),
        base0e: Color::from_hex(0x781aa0),
        base0f: Color::from_hex(0x7f1110),
    },
    base10: Color::from_hex(0xaaa45a),
    base11: Color::from_hex(0x55522d),
    base12: Color::from_hex(0xd4312e),
    base13: Color::from_hex(0xe9f06d),
    base14: Color::from_hex(0x8ff586),
    base15: Color::from_hex(0x6cbc67),
    base16: Color::from_hex(0x3c7dd2),
    base17: Color::from_hex(0x8230a7),
};
