//! Dracula color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Dracula
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Dracula"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x282a36),
    fg: Color::from_hex(0xf8f8f2),
    cursor: Some(Color::from_hex(0xf8f8f2)),
    selection: Some(Color::from_hex(0x44475a)),
    line_highlight: Some(Color::from_hex(0x363447)),
    gutter: Some(Color::from_hex(0x6272a4)),
    statusbar_bg: Some(Color::from_hex(0x363447)),
    statusbar_fg: Some(Color::from_hex(0x9ea8c7)),
    comment: Some(Color::from_hex(0x6272a4)),
    keyword: Some(Color::from_hex(0xff79c6)),
    string: Some(Color::from_hex(0x50fa7b)),
    function: Some(Color::from_hex(0x80bfff)),
    variable: Some(Color::from_hex(0xff5555)),
    r#type: Some(Color::from_hex(0xf1fa8c)),
    constant: Some(Color::from_hex(0xffb86c)),
    operator: Some(Color::from_hex(0xf8f8f2)),
    tag: Some(Color::from_hex(0xff5555)),
    error: Some(Color::from_hex(0xff5555)),
    warning: Some(Color::from_hex(0xf1fa8c)),
    info: Some(Color::from_hex(0x80bfff)),
    success: Some(Color::from_hex(0x50fa7b)),
    red: Some(Color::from_hex(0xf28c8c)),
    orange: Some(Color::from_hex(0xffb86c)),
    yellow: Some(Color::from_hex(0xeef5a3)),
    green: Some(Color::from_hex(0xa3f5b8)),
    cyan: Some(Color::from_hex(0x8be9fd)),
    blue: Some(Color::from_hex(0xbaedf7)),
    purple: Some(Color::from_hex(0xa3ccf5)),
    magenta: Some(Color::from_hex(0xf5a3d2)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x282a36),
        base01: Color::from_hex(0x363447),
        base02: Color::from_hex(0x44475a),
        base03: Color::from_hex(0x6272a4),
        base04: Color::from_hex(0x9ea8c7),
        base05: Color::from_hex(0xf8f8f2),
        base06: Color::from_hex(0xf0f1f4),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xff5555),
        base09: Color::from_hex(0xffb86c),
        base0a: Color::from_hex(0xf1fa8c),
        base0b: Color::from_hex(0x50fa7b),
        base0c: Color::from_hex(0x8be9fd),
        base0d: Color::from_hex(0x80bfff),
        base0e: Color::from_hex(0xff79c6),
        base0f: Color::from_hex(0xbd93f9),
    },
    base10: Color::from_hex(0x1e2029),
    base11: Color::from_hex(0x16171d),
    base12: Color::from_hex(0xf28c8c),
    base13: Color::from_hex(0xeef5a3),
    base14: Color::from_hex(0xa3f5b8),
    base15: Color::from_hex(0xbaedf7),
    base16: Color::from_hex(0xa3ccf5),
    base17: Color::from_hex(0xf5a3d2),
};
