//! Espresso Libre color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Espresso Libre
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Espresso Libre"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2a211c),
    fg: Color::from_hex(0xb3b7b0),
    cursor: Some(Color::from_hex(0xb3b7b0)),
    selection: Some(Color::from_hex(0x545753)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x737772)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x939791)),
    comment: Some(Color::from_hex(0x737772)),
    keyword: Some(Color::from_hex(0xc5656b)),
    string: Some(Color::from_hex(0x1a921c)),
    function: Some(Color::from_hex(0x0066ff)),
    variable: Some(Color::from_hex(0xcc0000)),
    r#type: Some(Color::from_hex(0x43a8ed)),
    constant: Some(Color::from_hex(0xefe43a)),
    operator: Some(Color::from_hex(0xb3b7b0)),
    tag: Some(Color::from_hex(0xcc0000)),
    error: Some(Color::from_hex(0xcc0000)),
    warning: Some(Color::from_hex(0x43a8ed)),
    info: Some(Color::from_hex(0x0066ff)),
    success: Some(Color::from_hex(0x1a921c)),
    red: Some(Color::from_hex(0xef2828)),
    orange: Some(Color::from_hex(0xefe43a)),
    yellow: Some(Color::from_hex(0xfffa5c)),
    green: Some(Color::from_hex(0x9aff87)),
    cyan: Some(Color::from_hex(0x05989a)),
    blue: Some(Color::from_hex(0x34e2e2)),
    purple: Some(Color::from_hex(0x43a8ed)),
    magenta: Some(Color::from_hex(0xff8089)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x2a211c),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x545753),
        base03: Color::from_hex(0x737772),
        base04: Color::from_hex(0x939791),
        base05: Color::from_hex(0xb3b7b0),
        base06: Color::from_hex(0xd3d7cf),
        base07: Color::from_hex(0xededec),
        base08: Color::from_hex(0xcc0000),
        base09: Color::from_hex(0xefe43a),
        base0a: Color::from_hex(0x43a8ed),
        base0b: Color::from_hex(0x1a921c),
        base0c: Color::from_hex(0x05989a),
        base0d: Color::from_hex(0x0066ff),
        base0e: Color::from_hex(0xc5656b),
        base0f: Color::from_hex(0x660000),
    },
    base10: Color::from_hex(0x383a37),
    base11: Color::from_hex(0x1c1d1b),
    base12: Color::from_hex(0xef2828),
    base13: Color::from_hex(0xfffa5c),
    base14: Color::from_hex(0x9aff87),
    base15: Color::from_hex(0x34e2e2),
    base16: Color::from_hex(0x43a8ed),
    base17: Color::from_hex(0xff8089),
};
