//! Fideloper color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Fideloper
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Fideloper",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x282f32),
    fg: Color::from_hex(0xb1b1a3),
    cursor: Some(Color::from_hex(0xb1b1a3)),
    selection: Some(Color::from_hex(0x092027)),
    line_highlight: Some(Color::from_hex(0x282f32)),
    gutter: Some(Color::from_hex(0x415050)),
    statusbar_bg: Some(Color::from_hex(0x282f32)),
    statusbar_fg: Some(Color::from_hex(0x79817a)),
    comment: Some(Color::from_hex(0x415050)),
    keyword: Some(Color::from_hex(0xc0226e)),
    string: Some(Color::from_hex(0xedb7ab)),
    function: Some(Color::from_hex(0x2e78c1)),
    variable: Some(Color::from_hex(0xca1d2c)),
    r#type: Some(Color::from_hex(0x7c84c4)),
    constant: Some(Color::from_hex(0xb7aa9a)),
    operator: Some(Color::from_hex(0xb1b1a3)),
    tag: Some(Color::from_hex(0xca1d2c)),
    error: Some(Color::from_hex(0xca1d2c)),
    warning: Some(Color::from_hex(0x7c84c4)),
    info: Some(Color::from_hex(0x2e78c1)),
    success: Some(Color::from_hex(0xedb7ab)),
    red: Some(Color::from_hex(0xd35f5a)),
    orange: Some(Color::from_hex(0xb7aa9a)),
    yellow: Some(Color::from_hex(0xa86571)),
    green: Some(Color::from_hex(0xd35f5a)),
    cyan: Some(Color::from_hex(0x309185)),
    blue: Some(Color::from_hex(0x81908f)),
    purple: Some(Color::from_hex(0x7c84c4)),
    magenta: Some(Color::from_hex(0x5b5db2)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x282f32),
        base01: Color::from_hex(0x282f32),
        base02: Color::from_hex(0x092027),
        base03: Color::from_hex(0x415050),
        base04: Color::from_hex(0x79817a),
        base05: Color::from_hex(0xb1b1a3),
        base06: Color::from_hex(0xe9e2cd),
        base07: Color::from_hex(0xfcf4de),
        base08: Color::from_hex(0xca1d2c),
        base09: Color::from_hex(0xb7aa9a),
        base0a: Color::from_hex(0x7c84c4),
        base0b: Color::from_hex(0xedb7ab),
        base0c: Color::from_hex(0x309185),
        base0d: Color::from_hex(0x2e78c1),
        base0e: Color::from_hex(0xc0226e),
        base0f: Color::from_hex(0x650e16),
    },
    base10: Color::from_hex(0x06151a),
    base11: Color::from_hex(0x030a0d),
    base12: Color::from_hex(0xd35f5a),
    base13: Color::from_hex(0xa86571),
    base14: Color::from_hex(0xd35f5a),
    base15: Color::from_hex(0x81908f),
    base16: Color::from_hex(0x7c84c4),
    base17: Color::from_hex(0x5b5db2),
};
