//! Flexoki Dark color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Flexoki Dark
///
/// Author: Steph Ango (https://github.com/kepano/flexoki)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Flexoki Dark",
    author: "Steph Ango (https://github.com/kepano/flexoki)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x100f0f),
    fg: Color::from_hex(0xcecdc3),
    cursor: Some(Color::from_hex(0xcecdc3)),
    selection: Some(Color::from_hex(0x282726)),
    line_highlight: Some(Color::from_hex(0x1c1b1a)),
    gutter: Some(Color::from_hex(0x575653)),
    statusbar_bg: Some(Color::from_hex(0x1c1b1a)),
    statusbar_fg: Some(Color::from_hex(0x878580)),
    comment: Some(Color::from_hex(0x575653)),
    keyword: Some(Color::from_hex(0x8b7ec8)),
    string: Some(Color::from_hex(0x879a39)),
    function: Some(Color::from_hex(0x4385be)),
    variable: Some(Color::from_hex(0xd14d41)),
    r#type: Some(Color::from_hex(0xd0a215)),
    constant: Some(Color::from_hex(0xda702c)),
    operator: Some(Color::from_hex(0xcecdc3)),
    tag: Some(Color::from_hex(0xd14d41)),
    error: Some(Color::from_hex(0xd14d41)),
    warning: Some(Color::from_hex(0xd0a215)),
    info: Some(Color::from_hex(0x4385be)),
    success: Some(Color::from_hex(0x879a39)),
    red: Some(Color::from_hex(0xaf3029)),
    orange: Some(Color::from_hex(0xda702c)),
    yellow: Some(Color::from_hex(0xbc5215)),
    green: Some(Color::from_hex(0xad8301)),
    cyan: Some(Color::from_hex(0x3aa99f)),
    blue: Some(Color::from_hex(0x66800b)),
    purple: Some(Color::from_hex(0x24837b)),
    magenta: Some(Color::from_hex(0x205ea6)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x100f0f),
        base01: Color::from_hex(0x1c1b1a),
        base02: Color::from_hex(0x282726),
        base03: Color::from_hex(0x575653),
        base04: Color::from_hex(0x878580),
        base05: Color::from_hex(0xcecdc3),
        base06: Color::from_hex(0xe6e4d9),
        base07: Color::from_hex(0xfffcf0),
        base08: Color::from_hex(0xd14d41),
        base09: Color::from_hex(0xda702c),
        base0a: Color::from_hex(0xd0a215),
        base0b: Color::from_hex(0x879a39),
        base0c: Color::from_hex(0x3aa99f),
        base0d: Color::from_hex(0x4385be),
        base0e: Color::from_hex(0x8b7ec8),
        base0f: Color::from_hex(0xce5d97),
    },
    base10: Color::from_hex(0x1c1b1a),
    base11: Color::from_hex(0x000000),
    base12: Color::from_hex(0xaf3029),
    base13: Color::from_hex(0xbc5215),
    base14: Color::from_hex(0xad8301),
    base15: Color::from_hex(0x66800b),
    base16: Color::from_hex(0x24837b),
    base17: Color::from_hex(0x205ea6),
};
