//! Framer color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Framer
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Framer"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x111111),
    fg: Color::from_hex(0xa9a9a9),
    cursor: Some(Color::from_hex(0xa9a9a9)),
    selection: Some(Color::from_hex(0x414141)),
    line_highlight: Some(Color::from_hex(0x141414)),
    gutter: Some(Color::from_hex(0x636363)),
    statusbar_bg: Some(Color::from_hex(0x141414)),
    statusbar_fg: Some(Color::from_hex(0x868686)),
    comment: Some(Color::from_hex(0x636363)),
    keyword: Some(Color::from_hex(0xaa88ff)),
    string: Some(Color::from_hex(0x98ec65)),
    function: Some(Color::from_hex(0x00aaff)),
    variable: Some(Color::from_hex(0xff5555)),
    r#type: Some(Color::from_hex(0x33bbff)),
    constant: Some(Color::from_hex(0xffcc33)),
    operator: Some(Color::from_hex(0xa9a9a9)),
    tag: Some(Color::from_hex(0xff5555)),
    error: Some(Color::from_hex(0xff5555)),
    warning: Some(Color::from_hex(0x33bbff)),
    info: Some(Color::from_hex(0x00aaff)),
    success: Some(Color::from_hex(0x98ec65)),
    red: Some(Color::from_hex(0xff8888)),
    orange: Some(Color::from_hex(0xffcc33)),
    yellow: Some(Color::from_hex(0xffd966)),
    green: Some(Color::from_hex(0xb6f292)),
    cyan: Some(Color::from_hex(0x88ddff)),
    blue: Some(Color::from_hex(0xbbecff)),
    purple: Some(Color::from_hex(0x33bbff)),
    magenta: Some(Color::from_hex(0xcebbff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x111111),
        base01: Color::from_hex(0x141414),
        base02: Color::from_hex(0x414141),
        base03: Color::from_hex(0x636363),
        base04: Color::from_hex(0x868686),
        base05: Color::from_hex(0xa9a9a9),
        base06: Color::from_hex(0xcccccc),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xff5555),
        base09: Color::from_hex(0xffcc33),
        base0a: Color::from_hex(0x33bbff),
        base0b: Color::from_hex(0x98ec65),
        base0c: Color::from_hex(0x88ddff),
        base0d: Color::from_hex(0x00aaff),
        base0e: Color::from_hex(0xaa88ff),
        base0f: Color::from_hex(0x7f2a2a),
    },
    base10: Color::from_hex(0x2b2b2b),
    base11: Color::from_hex(0x151515),
    base12: Color::from_hex(0xff8888),
    base13: Color::from_hex(0xffd966),
    base14: Color::from_hex(0xb6f292),
    base15: Color::from_hex(0xbbecff),
    base16: Color::from_hex(0x33bbff),
    base17: Color::from_hex(0xcebbff),
};
