//! Galaxy color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Galaxy
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Galaxy",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1c2836),
    fg: Color::from_hex(0xa1a1a1),
    cursor: Some(Color::from_hex(0xa1a1a1)),
    selection: Some(Color::from_hex(0x555555)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x6e6e6e)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x888888)),
    comment: Some(Color::from_hex(0x6e6e6e)),
    keyword: Some(Color::from_hex(0x934d95)),
    string: Some(Color::from_hex(0x20af89)),
    function: Some(Color::from_hex(0x589cf5)),
    variable: Some(Color::from_hex(0xf9555f)),
    r#type: Some(Color::from_hex(0xfdf029)),
    constant: Some(Color::from_hex(0xfdba29)),
    operator: Some(Color::from_hex(0xa1a1a1)),
    tag: Some(Color::from_hex(0xf9555f)),
    error: Some(Color::from_hex(0xf9555f)),
    warning: Some(Color::from_hex(0xfdf029)),
    info: Some(Color::from_hex(0x589cf5)),
    success: Some(Color::from_hex(0x20af89)),
    red: Some(Color::from_hex(0xfa8b8e)),
    orange: Some(Color::from_hex(0xfdba29)),
    yellow: Some(Color::from_hex(0xffff55)),
    green: Some(Color::from_hex(0x34bb99)),
    cyan: Some(Color::from_hex(0x1e9ee6)),
    blue: Some(Color::from_hex(0x3978bb)),
    purple: Some(Color::from_hex(0x589cf5)),
    magenta: Some(Color::from_hex(0xe75598)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1c2836),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x555555),
        base03: Color::from_hex(0x6e6e6e),
        base04: Color::from_hex(0x888888),
        base05: Color::from_hex(0xa1a1a1),
        base06: Color::from_hex(0xbbbbbb),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xf9555f),
        base09: Color::from_hex(0xfdba29),
        base0a: Color::from_hex(0xfdf029),
        base0b: Color::from_hex(0x20af89),
        base0c: Color::from_hex(0x1e9ee6),
        base0d: Color::from_hex(0x589cf5),
        base0e: Color::from_hex(0x934d95),
        base0f: Color::from_hex(0x7c2a2f),
    },
    base10: Color::from_hex(0x383838),
    base11: Color::from_hex(0x1c1c1c),
    base12: Color::from_hex(0xfa8b8e),
    base13: Color::from_hex(0xffff55),
    base14: Color::from_hex(0x34bb99),
    base15: Color::from_hex(0x3978bb),
    base16: Color::from_hex(0x589cf5),
    base17: Color::from_hex(0xe75598),
};
