//! IC-Green-PPL color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// IC-Green-PPL
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "IC-Green-PPL",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2c2c2c),
    fg: Color::from_hex(0xadd5b6),
    cursor: Some(Color::from_hex(0xadd5b6)),
    selection: Some(Color::from_hex(0x025c02)),
    line_highlight: Some(Color::from_hex(0x014401)),
    gutter: Some(Color::from_hex(0x3b843e)),
    statusbar_bg: Some(Color::from_hex(0x014401)),
    statusbar_fg: Some(Color::from_hex(0x74ad7a)),
    comment: Some(Color::from_hex(0x3b843e)),
    keyword: Some(Color::from_hex(0x50a096)),
    string: Some(Color::from_hex(0x41a638)),
    function: Some(Color::from_hex(0x2ec3b9)),
    variable: Some(Color::from_hex(0xfe2635)),
    r#type: Some(Color::from_hex(0x2efaeb)),
    constant: Some(Color::from_hex(0x76a830)),
    operator: Some(Color::from_hex(0xadd5b6)),
    tag: Some(Color::from_hex(0xfe2635)),
    error: Some(Color::from_hex(0xfe2635)),
    warning: Some(Color::from_hex(0x2efaeb)),
    info: Some(Color::from_hex(0x2ec3b9)),
    success: Some(Color::from_hex(0x41a638)),
    red: Some(Color::from_hex(0xb4fa5c)),
    orange: Some(Color::from_hex(0x76a830)),
    yellow: Some(Color::from_hex(0xdafa87)),
    green: Some(Color::from_hex(0xaefa86)),
    cyan: Some(Color::from_hex(0x3ca078)),
    blue: Some(Color::from_hex(0x3cfac8)),
    purple: Some(Color::from_hex(0x2efaeb)),
    magenta: Some(Color::from_hex(0x50fafa)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x2c2c2c),
        base01: Color::from_hex(0x014401),
        base02: Color::from_hex(0x025c02),
        base03: Color::from_hex(0x3b843e),
        base04: Color::from_hex(0x74ad7a),
        base05: Color::from_hex(0xadd5b6),
        base06: Color::from_hex(0xe6fef2),
        base07: Color::from_hex(0xe0f1dc),
        base08: Color::from_hex(0xfe2635),
        base09: Color::from_hex(0x76a830),
        base0a: Color::from_hex(0x2efaeb),
        base0b: Color::from_hex(0x41a638),
        base0c: Color::from_hex(0x3ca078),
        base0d: Color::from_hex(0x2ec3b9),
        base0e: Color::from_hex(0x50a096),
        base0f: Color::from_hex(0x7f131a),
    },
    base10: Color::from_hex(0x013d01),
    base11: Color::from_hex(0x001e00),
    base12: Color::from_hex(0xb4fa5c),
    base13: Color::from_hex(0xdafa87),
    base14: Color::from_hex(0xaefa86),
    base15: Color::from_hex(0x3cfac8),
    base16: Color::from_hex(0x2efaeb),
    base17: Color::from_hex(0x50fafa),
};
