//! Idle Toes color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Idle Toes
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Idle Toes"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x323232),
    fg: Color::from_hex(0xc7c7c5),
    cursor: Some(Color::from_hex(0xc7c7c5)),
    selection: Some(Color::from_hex(0x535353)),
    line_highlight: Some(Color::from_hex(0x323232)),
    gutter: Some(Color::from_hex(0x797979)),
    statusbar_bg: Some(Color::from_hex(0x323232)),
    statusbar_fg: Some(Color::from_hex(0xa0a09f)),
    comment: Some(Color::from_hex(0x797979)),
    keyword: Some(Color::from_hex(0xf57fff)),
    string: Some(Color::from_hex(0x7fe173)),
    function: Some(Color::from_hex(0x4098ff)),
    variable: Some(Color::from_hex(0xd25252)),
    r#type: Some(Color::from_hex(0x5eb7f7)),
    constant: Some(Color::from_hex(0xffc66d)),
    operator: Some(Color::from_hex(0xc7c7c5)),
    tag: Some(Color::from_hex(0xd25252)),
    error: Some(Color::from_hex(0xd25252)),
    warning: Some(Color::from_hex(0x5eb7f7)),
    info: Some(Color::from_hex(0x4098ff)),
    success: Some(Color::from_hex(0x7fe173)),
    red: Some(Color::from_hex(0xf07070)),
    orange: Some(Color::from_hex(0xffc66d)),
    yellow: Some(Color::from_hex(0xffe48b)),
    green: Some(Color::from_hex(0x9dff90)),
    cyan: Some(Color::from_hex(0xbed6ff)),
    blue: Some(Color::from_hex(0xdcf4ff)),
    purple: Some(Color::from_hex(0x5eb7f7)),
    magenta: Some(Color::from_hex(0xff9dff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x323232),
        base01: Color::from_hex(0x323232),
        base02: Color::from_hex(0x535353),
        base03: Color::from_hex(0x797979),
        base04: Color::from_hex(0xa0a09f),
        base05: Color::from_hex(0xc7c7c5),
        base06: Color::from_hex(0xeeeeec),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xd25252),
        base09: Color::from_hex(0xffc66d),
        base0a: Color::from_hex(0x5eb7f7),
        base0b: Color::from_hex(0x7fe173),
        base0c: Color::from_hex(0xbed6ff),
        base0d: Color::from_hex(0x4098ff),
        base0e: Color::from_hex(0xf57fff),
        base0f: Color::from_hex(0x692929),
    },
    base10: Color::from_hex(0x373737),
    base11: Color::from_hex(0x1b1b1b),
    base12: Color::from_hex(0xf07070),
    base13: Color::from_hex(0xffe48b),
    base14: Color::from_hex(0x9dff90),
    base15: Color::from_hex(0xdcf4ff),
    base16: Color::from_hex(0x5eb7f7),
    base17: Color::from_hex(0xff9dff),
};
