//! Jellybeans color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Jellybeans
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Jellybeans"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xd5d5d5),
    cursor: Some(Color::from_hex(0xd5d5d5)),
    selection: Some(Color::from_hex(0xbdbdbd)),
    line_highlight: Some(Color::from_hex(0x929292)),
    gutter: Some(Color::from_hex(0xc5c5c5)),
    statusbar_bg: Some(Color::from_hex(0x929292)),
    statusbar_fg: Some(Color::from_hex(0xcdcdcd)),
    comment: Some(Color::from_hex(0xc5c5c5)),
    keyword: Some(Color::from_hex(0xe1c0fa)),
    string: Some(Color::from_hex(0x93b979)),
    function: Some(Color::from_hex(0x97bedc)),
    variable: Some(Color::from_hex(0xe27373)),
    r#type: Some(Color::from_hex(0xb1d8f6)),
    constant: Some(Color::from_hex(0xffba7b)),
    operator: Some(Color::from_hex(0xd5d5d5)),
    tag: Some(Color::from_hex(0xe27373)),
    error: Some(Color::from_hex(0xe27373)),
    warning: Some(Color::from_hex(0xb1d8f6)),
    info: Some(Color::from_hex(0x97bedc)),
    success: Some(Color::from_hex(0x93b979)),
    red: Some(Color::from_hex(0xffa1a1)),
    orange: Some(Color::from_hex(0xffba7b)),
    yellow: Some(Color::from_hex(0xffdca0)),
    green: Some(Color::from_hex(0xbddeab)),
    cyan: Some(Color::from_hex(0x00988e)),
    blue: Some(Color::from_hex(0x1ab2a8)),
    purple: Some(Color::from_hex(0xb1d8f6)),
    magenta: Some(Color::from_hex(0xfbdaff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x121212),
        base01: Color::from_hex(0x929292),
        base02: Color::from_hex(0xbdbdbd),
        base03: Color::from_hex(0xc5c5c5),
        base04: Color::from_hex(0xcdcdcd),
        base05: Color::from_hex(0xd5d5d5),
        base06: Color::from_hex(0xdedede),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xe27373),
        base09: Color::from_hex(0xffba7b),
        base0a: Color::from_hex(0xb1d8f6),
        base0b: Color::from_hex(0x93b979),
        base0c: Color::from_hex(0x00988e),
        base0d: Color::from_hex(0x97bedc),
        base0e: Color::from_hex(0xe1c0fa),
        base0f: Color::from_hex(0x713939),
    },
    base10: Color::from_hex(0x7e7e7e),
    base11: Color::from_hex(0x3f3f3f),
    base12: Color::from_hex(0xffa1a1),
    base13: Color::from_hex(0xffdca0),
    base14: Color::from_hex(0xbddeab),
    base15: Color::from_hex(0x1ab2a8),
    base16: Color::from_hex(0xb1d8f6),
    base17: Color::from_hex(0xfbdaff),
};
