//! Laser color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Laser
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Laser"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x030d18),
    fg: Color::from_hex(0xd8d8d8),
    cursor: Some(Color::from_hex(0xd8d8d8)),
    selection: Some(Color::from_hex(0x8e8e8e)),
    line_highlight: Some(Color::from_hex(0x616161)),
    gutter: Some(Color::from_hex(0xa6a6a6)),
    statusbar_bg: Some(Color::from_hex(0x616161)),
    statusbar_fg: Some(Color::from_hex(0xbfbfbf)),
    comment: Some(Color::from_hex(0xa6a6a6)),
    keyword: Some(Color::from_hex(0xff8ffd)),
    string: Some(Color::from_hex(0xb4fa72)),
    function: Some(Color::from_hex(0xfed300)),
    variable: Some(Color::from_hex(0xff8272)),
    r#type: Some(Color::from_hex(0xf92883)),
    constant: Some(Color::from_hex(0x09b4bd)),
    operator: Some(Color::from_hex(0xd8d8d8)),
    tag: Some(Color::from_hex(0xff8272)),
    error: Some(Color::from_hex(0xff8272)),
    warning: Some(Color::from_hex(0xf92883)),
    info: Some(Color::from_hex(0xfed300)),
    success: Some(Color::from_hex(0xb4fa72)),
    red: Some(Color::from_hex(0xffc4bd)),
    orange: Some(Color::from_hex(0x09b4bd)),
    yellow: Some(Color::from_hex(0xfefdd5)),
    green: Some(Color::from_hex(0xd6fcb9)),
    cyan: Some(Color::from_hex(0xd0d1fe)),
    blue: Some(Color::from_hex(0xe5e6fe)),
    purple: Some(Color::from_hex(0xf92883)),
    magenta: Some(Color::from_hex(0xffb1fe)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x030d18),
        base01: Color::from_hex(0x616161),
        base02: Color::from_hex(0x8e8e8e),
        base03: Color::from_hex(0xa6a6a6),
        base04: Color::from_hex(0xbfbfbf),
        base05: Color::from_hex(0xd8d8d8),
        base06: Color::from_hex(0xf1f1f1),
        base07: Color::from_hex(0xfeffff),
        base08: Color::from_hex(0xff8272),
        base09: Color::from_hex(0x09b4bd),
        base0a: Color::from_hex(0xf92883),
        base0b: Color::from_hex(0xb4fa72),
        base0c: Color::from_hex(0xd0d1fe),
        base0d: Color::from_hex(0xfed300),
        base0e: Color::from_hex(0xff8ffd),
        base0f: Color::from_hex(0x7f4139),
    },
    base10: Color::from_hex(0x5e5e5e),
    base11: Color::from_hex(0x2f2f2f),
    base12: Color::from_hex(0xffc4bd),
    base13: Color::from_hex(0xfefdd5),
    base14: Color::from_hex(0xd6fcb9),
    base15: Color::from_hex(0xe5e6fe),
    base16: Color::from_hex(0xf92883),
    base17: Color::from_hex(0xffb1fe),
};
