//! Material color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Material
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Light
/// Contrast: Low
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Material",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Light,
    contrast: Contrast::Low,
    bg: Color::from_hex(0xeaeaea),
    fg: Color::from_hex(0xc3c3c3),
    cursor: Some(Color::from_hex(0xc3c3c3)),
    selection: Some(Color::from_hex(0x424242)),
    line_highlight: Some(Color::from_hex(0x212121)),
    gutter: Some(Color::from_hex(0x6d6d6d)),
    statusbar_bg: Some(Color::from_hex(0x212121)),
    statusbar_fg: Some(Color::from_hex(0x989898)),
    comment: Some(Color::from_hex(0x6d6d6d)),
    keyword: Some(Color::from_hex(0x550087)),
    string: Some(Color::from_hex(0x457b23)),
    function: Some(Color::from_hex(0x134eb2)),
    variable: Some(Color::from_hex(0xb7141e)),
    r#type: Some(Color::from_hex(0x53a4f3)),
    constant: Some(Color::from_hex(0xf5971d)),
    operator: Some(Color::from_hex(0xc3c3c3)),
    tag: Some(Color::from_hex(0xb7141e)),
    error: Some(Color::from_hex(0xb7141e)),
    warning: Some(Color::from_hex(0x53a4f3)),
    info: Some(Color::from_hex(0x134eb2)),
    success: Some(Color::from_hex(0x457b23)),
    red: Some(Color::from_hex(0xe83a3f)),
    orange: Some(Color::from_hex(0xf5971d)),
    yellow: Some(Color::from_hex(0xfee92e)),
    green: Some(Color::from_hex(0x7aba39)),
    cyan: Some(Color::from_hex(0x0e707c)),
    blue: Some(Color::from_hex(0x26bad1)),
    purple: Some(Color::from_hex(0x53a4f3)),
    magenta: Some(Color::from_hex(0xa94dbb)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0xeaeaea),
        base01: Color::from_hex(0x212121),
        base02: Color::from_hex(0x424242),
        base03: Color::from_hex(0x6d6d6d),
        base04: Color::from_hex(0x989898),
        base05: Color::from_hex(0xc3c3c3),
        base06: Color::from_hex(0xeeeeee),
        base07: Color::from_hex(0xd8d8d8),
        base08: Color::from_hex(0xb7141e),
        base09: Color::from_hex(0xf5971d),
        base0a: Color::from_hex(0x53a4f3),
        base0b: Color::from_hex(0x457b23),
        base0c: Color::from_hex(0x0e707c),
        base0d: Color::from_hex(0x134eb2),
        base0e: Color::from_hex(0x550087),
        base0f: Color::from_hex(0x5b0a0f),
    },
    base10: Color::from_hex(0x2c2c2c),
    base11: Color::from_hex(0x161616),
    base12: Color::from_hex(0xe83a3f),
    base13: Color::from_hex(0xfee92e),
    base14: Color::from_hex(0x7aba39),
    base15: Color::from_hex(0x26bad1),
    base16: Color::from_hex(0x53a4f3),
    base17: Color::from_hex(0xa94dbb),
};
