//! Medallion color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Medallion
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Medallion",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1d1808),
    fg: Color::from_hex(0xaea578),
    cursor: Some(Color::from_hex(0xaea578)),
    selection: Some(Color::from_hex(0x5e5118)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x786d38)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x938958)),
    comment: Some(Color::from_hex(0x786d38)),
    keyword: Some(Color::from_hex(0x8b5990)),
    string: Some(Color::from_hex(0x7c8a16)),
    function: Some(Color::from_hex(0x606baf)),
    variable: Some(Color::from_hex(0xb54c00)),
    r#type: Some(Color::from_hex(0xabb8ff)),
    constant: Some(Color::from_hex(0xd2bd25)),
    operator: Some(Color::from_hex(0xaea578)),
    tag: Some(Color::from_hex(0xb54c00)),
    error: Some(Color::from_hex(0xb54c00)),
    warning: Some(Color::from_hex(0xabb8ff)),
    info: Some(Color::from_hex(0x606baf)),
    success: Some(Color::from_hex(0x7c8a16)),
    red: Some(Color::from_hex(0xff9148)),
    orange: Some(Color::from_hex(0xd2bd25)),
    yellow: Some(Color::from_hex(0xffe449)),
    green: Some(Color::from_hex(0xb1c93a)),
    cyan: Some(Color::from_hex(0x906b25)),
    blue: Some(Color::from_hex(0xffbb51)),
    purple: Some(Color::from_hex(0xabb8ff)),
    magenta: Some(Color::from_hex(0xfe9fff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1d1808),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x5e5118),
        base03: Color::from_hex(0x786d38),
        base04: Color::from_hex(0x938958),
        base05: Color::from_hex(0xaea578),
        base06: Color::from_hex(0xc9c199),
        base07: Color::from_hex(0xfed597),
        base08: Color::from_hex(0xb54c00),
        base09: Color::from_hex(0xd2bd25),
        base0a: Color::from_hex(0xabb8ff),
        base0b: Color::from_hex(0x7c8a16),
        base0c: Color::from_hex(0x906b25),
        base0d: Color::from_hex(0x606baf),
        base0e: Color::from_hex(0x8b5990),
        base0f: Color::from_hex(0x5a2600),
    },
    base10: Color::from_hex(0x3e3610),
    base11: Color::from_hex(0x1f1b08),
    base12: Color::from_hex(0xff9148),
    base13: Color::from_hex(0xffe449),
    base14: Color::from_hex(0xb1c93a),
    base15: Color::from_hex(0xffbb51),
    base16: Color::from_hex(0xabb8ff),
    base17: Color::from_hex(0xfe9fff),
};
