//! Monokai Vivid color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Monokai Vivid
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Monokai Vivid"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xdfdfdf),
    cursor: Some(Color::from_hex(0xdfdfdf)),
    selection: Some(Color::from_hex(0x424242)),
    line_highlight: Some(Color::from_hex(0x323232)),
    gutter: Some(Color::from_hex(0x525252)),
    statusbar_bg: Some(Color::from_hex(0x323232)),
    statusbar_fg: Some(Color::from_hex(0xc0c0c0)),
    comment: Some(Color::from_hex(0x525252)),
    keyword: Some(Color::from_hex(0xf800f8)),
    string: Some(Color::from_hex(0x97e123)),
    function: Some(Color::from_hex(0x0442fe)),
    variable: Some(Color::from_hex(0xfa2834)),
    r#type: Some(Color::from_hex(0xfef20a)),
    constant: Some(Color::from_hex(0xfec50a)),
    operator: Some(Color::from_hex(0xdfdfdf)),
    tag: Some(Color::from_hex(0xfa2834)),
    error: Some(Color::from_hex(0xfa2834)),
    warning: Some(Color::from_hex(0xfef20a)),
    info: Some(Color::from_hex(0x0442fe)),
    success: Some(Color::from_hex(0x97e123)),
    red: Some(Color::from_hex(0xf5669c)),
    orange: Some(Color::from_hex(0xfec50a)),
    yellow: Some(Color::from_hex(0xfef26c)),
    green: Some(Color::from_hex(0xb0e05e)),
    cyan: Some(Color::from_hex(0x01b6ed)),
    blue: Some(Color::from_hex(0x50cdfe)),
    purple: Some(Color::from_hex(0x0442fe)),
    magenta: Some(Color::from_hex(0xf200f5)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x121212),
        base01: Color::from_hex(0x323232),
        base02: Color::from_hex(0x424242),
        base03: Color::from_hex(0x525252),
        base04: Color::from_hex(0xc0c0c0),
        base05: Color::from_hex(0xdfdfdf),
        base06: Color::from_hex(0xf1f1f1),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xfa2834),
        base09: Color::from_hex(0xfec50a),
        base0a: Color::from_hex(0xfef20a),
        base0b: Color::from_hex(0x97e123),
        base0c: Color::from_hex(0x01b6ed),
        base0d: Color::from_hex(0x0442fe),
        base0e: Color::from_hex(0xf800f8),
        base0f: Color::from_hex(0x7d141a),
    },
    base10: Color::from_hex(0x565656),
    base11: Color::from_hex(0x2b2b2b),
    base12: Color::from_hex(0xf5669c),
    base13: Color::from_hex(0xfef26c),
    base14: Color::from_hex(0xb0e05e),
    base15: Color::from_hex(0x50cdfe),
    base16: Color::from_hex(0x0442fe),
    base17: Color::from_hex(0xf200f5),
};
