//! One Light color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// One Light
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Light
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("One Light"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xe7e7e9),
    fg: Color::from_hex(0x383a42),
    cursor: Some(Color::from_hex(0x383a42)),
    selection: Some(Color::from_hex(0xcacace)),
    line_highlight: Some(Color::from_hex(0xdfdfe1)),
    gutter: Some(Color::from_hex(0xa0a1a7)),
    statusbar_bg: Some(Color::from_hex(0xdfdfe1)),
    statusbar_fg: Some(Color::from_hex(0x696c77)),
    comment: Some(Color::from_hex(0xa0a1a7)),
    keyword: Some(Color::from_hex(0xa626a4)),
    string: Some(Color::from_hex(0x50a14f)),
    function: Some(Color::from_hex(0x4078f2)),
    variable: Some(Color::from_hex(0xca1243)),
    r#type: Some(Color::from_hex(0xfebb2a)),
    constant: Some(Color::from_hex(0xc18401)),
    operator: Some(Color::from_hex(0x383a42)),
    tag: Some(Color::from_hex(0xca1243)),
    error: Some(Color::from_hex(0xca1243)),
    warning: Some(Color::from_hex(0xfebb2a)),
    info: Some(Color::from_hex(0x4078f2)),
    success: Some(Color::from_hex(0x50a14f)),
    red: Some(Color::from_hex(0xec2258)),
    orange: Some(Color::from_hex(0xc18401)),
    yellow: Some(Color::from_hex(0xf4a701)),
    green: Some(Color::from_hex(0x6db76c)),
    cyan: Some(Color::from_hex(0x0184bc)),
    blue: Some(Color::from_hex(0x01a7ef)),
    purple: Some(Color::from_hex(0x709af5)),
    magenta: Some(Color::from_hex(0xd02fcd)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0xe7e7e9),
        base01: Color::from_hex(0xdfdfe1),
        base02: Color::from_hex(0xcacace),
        base03: Color::from_hex(0xa0a1a7),
        base04: Color::from_hex(0x696c77),
        base05: Color::from_hex(0x383a42),
        base06: Color::from_hex(0x202227),
        base07: Color::from_hex(0x090a0b),
        base08: Color::from_hex(0xca1243),
        base09: Color::from_hex(0xc18401),
        base0a: Color::from_hex(0xfebb2a),
        base0b: Color::from_hex(0x50a14f),
        base0c: Color::from_hex(0x0184bc),
        base0d: Color::from_hex(0x4078f2),
        base0e: Color::from_hex(0xa626a4),
        base0f: Color::from_hex(0x986801),
    },
    base10: Color::from_hex(0xf0f0f1),
    base11: Color::from_hex(0xfafafa),
    base12: Color::from_hex(0xec2258),
    base13: Color::from_hex(0xf4a701),
    base14: Color::from_hex(0x6db76c),
    base15: Color::from_hex(0x01a7ef),
    base16: Color::from_hex(0x709af5),
    base17: Color::from_hex(0xd02fcd),
};
