//! One Half Light color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// One Half Light
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("One Half Light"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2a2b32),
    fg: Color::from_hex(0xcfd0d2),
    cursor: Some(Color::from_hex(0xcfd0d2)),
    selection: Some(Color::from_hex(0x4f525d)),
    line_highlight: Some(Color::from_hex(0x373942)),
    gutter: Some(Color::from_hex(0x797c84)),
    statusbar_bg: Some(Color::from_hex(0x373942)),
    statusbar_fg: Some(Color::from_hex(0xa4a6ab)),
    comment: Some(Color::from_hex(0x797c84)),
    keyword: Some(Color::from_hex(0xa625a4)),
    string: Some(Color::from_hex(0x4fa14f)),
    function: Some(Color::from_hex(0x0084bc)),
    variable: Some(Color::from_hex(0xe45649)),
    r#type: Some(Color::from_hex(0xc0aa00)),
    constant: Some(Color::from_hex(0xc08400)),
    operator: Some(Color::from_hex(0xcfd0d2)),
    tag: Some(Color::from_hex(0xe45649)),
    error: Some(Color::from_hex(0xe45649)),
    warning: Some(Color::from_hex(0xc0aa00)),
    info: Some(Color::from_hex(0x0084bc)),
    success: Some(Color::from_hex(0x4fa14f)),
    red: Some(Color::from_hex(0xdf6c75)),
    orange: Some(Color::from_hex(0xc08400)),
    yellow: Some(Color::from_hex(0xe4c07a)),
    green: Some(Color::from_hex(0x98c379)),
    cyan: Some(Color::from_hex(0x0996b3)),
    blue: Some(Color::from_hex(0x56b5c1)),
    purple: Some(Color::from_hex(0x61afef)),
    magenta: Some(Color::from_hex(0xc577dd)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x2a2b32),
        base01: Color::from_hex(0x373942),
        base02: Color::from_hex(0x4f525d),
        base03: Color::from_hex(0x797c84),
        base04: Color::from_hex(0xa4a6ab),
        base05: Color::from_hex(0xcfd0d2),
        base06: Color::from_hex(0xfafafa),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xe45649),
        base09: Color::from_hex(0xc08400),
        base0a: Color::from_hex(0xc0aa00),
        base0b: Color::from_hex(0x4fa14f),
        base0c: Color::from_hex(0x0996b3),
        base0d: Color::from_hex(0x0084bc),
        base0e: Color::from_hex(0xa625a4),
        base0f: Color::from_hex(0x722b24),
    },
    base10: Color::from_hex(0x34363e),
    base11: Color::from_hex(0x1a1b1f),
    base12: Color::from_hex(0xdf6c75),
    base13: Color::from_hex(0xe4c07a),
    base14: Color::from_hex(0x98c379),
    base15: Color::from_hex(0x56b5c1),
    base16: Color::from_hex(0x61afef),
    base17: Color::from_hex(0xc577dd),
};
