//! Purple Rain color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Purple Rain
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Purple Rain",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x20084a),
    fg: Color::from_hex(0xd3d4d4),
    cursor: Some(Color::from_hex(0xd3d4d4)),
    selection: Some(Color::from_hex(0x555555)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x7f7f7f)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0xa9aaaa)),
    comment: Some(Color::from_hex(0x7f7f7f)),
    keyword: Some(Color::from_hex(0x805bb5)),
    string: Some(Color::from_hex(0x9ae204)),
    function: Some(Color::from_hex(0x00a1f9)),
    variable: Some(Color::from_hex(0xff260d)),
    r#type: Some(Color::from_hex(0x00a5ff)),
    constant: Some(Color::from_hex(0xffc400)),
    operator: Some(Color::from_hex(0xd3d4d4)),
    tag: Some(Color::from_hex(0xff260d)),
    error: Some(Color::from_hex(0xff260d)),
    warning: Some(Color::from_hex(0x00a5ff)),
    info: Some(Color::from_hex(0x00a1f9)),
    success: Some(Color::from_hex(0x9ae204)),
    red: Some(Color::from_hex(0xff4250)),
    orange: Some(Color::from_hex(0xffc400)),
    yellow: Some(Color::from_hex(0xffd852)),
    green: Some(Color::from_hex(0xb8e36d)),
    cyan: Some(Color::from_hex(0x00ddef)),
    blue: Some(Color::from_hex(0x74fcf3)),
    purple: Some(Color::from_hex(0x00a5ff)),
    magenta: Some(Color::from_hex(0xab7aef)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x20084a),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x555555),
        base03: Color::from_hex(0x7f7f7f),
        base04: Color::from_hex(0xa9aaaa),
        base05: Color::from_hex(0xd3d4d4),
        base06: Color::from_hex(0xfeffff),
        base07: Color::from_hex(0xfeffff),
        base08: Color::from_hex(0xff260d),
        base09: Color::from_hex(0xffc400),
        base0a: Color::from_hex(0x00a5ff),
        base0b: Color::from_hex(0x9ae204),
        base0c: Color::from_hex(0x00ddef),
        base0d: Color::from_hex(0x00a1f9),
        base0e: Color::from_hex(0x805bb5),
        base0f: Color::from_hex(0x7f1306),
    },
    base10: Color::from_hex(0x383838),
    base11: Color::from_hex(0x1c1c1c),
    base12: Color::from_hex(0xff4250),
    base13: Color::from_hex(0xffd852),
    base14: Color::from_hex(0xb8e36d),
    base15: Color::from_hex(0x74fcf3),
    base16: Color::from_hex(0x00a5ff),
    base17: Color::from_hex(0xab7aef),
};
