//! Rebecca color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Rebecca
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Rebecca"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x292a44),
    fg: Color::from_hex(0xc3c3d4),
    cursor: Some(Color::from_hex(0xc3c3d4)),
    selection: Some(Color::from_hex(0x666699)),
    line_highlight: Some(Color::from_hex(0x12131d)),
    gutter: Some(Color::from_hex(0x8585ac)),
    statusbar_bg: Some(Color::from_hex(0x12131d)),
    statusbar_fg: Some(Color::from_hex(0xa4a4c0)),
    comment: Some(Color::from_hex(0x8585ac)),
    keyword: Some(Color::from_hex(0xbe9bf8)),
    string: Some(Color::from_hex(0x04dbb4)),
    function: Some(Color::from_hex(0x7aa5ff)),
    variable: Some(Color::from_hex(0xdd7655)),
    r#type: Some(Color::from_hex(0x69bffa)),
    constant: Some(Color::from_hex(0xf2e7b7)),
    operator: Some(Color::from_hex(0xc3c3d4)),
    tag: Some(Color::from_hex(0xdd7655)),
    error: Some(Color::from_hex(0xdd7655)),
    warning: Some(Color::from_hex(0x69bffa)),
    info: Some(Color::from_hex(0x7aa5ff)),
    success: Some(Color::from_hex(0x04dbb4)),
    red: Some(Color::from_hex(0xff91cd)),
    orange: Some(Color::from_hex(0xf2e7b7)),
    yellow: Some(Color::from_hex(0xfefca8)),
    green: Some(Color::from_hex(0x00e9c0)),
    cyan: Some(Color::from_hex(0x56d3c1)),
    blue: Some(Color::from_hex(0x8bfce1)),
    purple: Some(Color::from_hex(0x69bffa)),
    magenta: Some(Color::from_hex(0xc07ff8)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x292a44),
        base01: Color::from_hex(0x12131d),
        base02: Color::from_hex(0x666699),
        base03: Color::from_hex(0x8585ac),
        base04: Color::from_hex(0xa4a4c0),
        base05: Color::from_hex(0xc3c3d4),
        base06: Color::from_hex(0xe3e2e8),
        base07: Color::from_hex(0xf3f2f8),
        base08: Color::from_hex(0xdd7655),
        base09: Color::from_hex(0xf2e7b7),
        base0a: Color::from_hex(0x69bffa),
        base0b: Color::from_hex(0x04dbb4),
        base0c: Color::from_hex(0x56d3c1),
        base0d: Color::from_hex(0x7aa5ff),
        base0e: Color::from_hex(0xbe9bf8),
        base0f: Color::from_hex(0x6e3b2a),
    },
    base10: Color::from_hex(0x444466),
    base11: Color::from_hex(0x222233),
    base12: Color::from_hex(0xff91cd),
    base13: Color::from_hex(0xfefca8),
    base14: Color::from_hex(0x00e9c0),
    base15: Color::from_hex(0x8bfce1),
    base16: Color::from_hex(0x69bffa),
    base17: Color::from_hex(0xc07ff8),
};
