//! Red Sands color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Red Sands
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Low
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Red Sands",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x79241e),
    fg: Color::from_hex(0xa1a1a1),
    cursor: Some(Color::from_hex(0xa1a1a1)),
    selection: Some(Color::from_hex(0x555555)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x6e6e6e)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x888888)),
    comment: Some(Color::from_hex(0x6e6e6e)),
    keyword: Some(Color::from_hex(0xbb00bb)),
    string: Some(Color::from_hex(0x00bb00)),
    function: Some(Color::from_hex(0x0071ff)),
    variable: Some(Color::from_hex(0xff3f00)),
    r#type: Some(Color::from_hex(0x0071ae)),
    constant: Some(Color::from_hex(0xe7b000)),
    operator: Some(Color::from_hex(0xa1a1a1)),
    tag: Some(Color::from_hex(0xff3f00)),
    error: Some(Color::from_hex(0xff3f00)),
    warning: Some(Color::from_hex(0x0071ae)),
    info: Some(Color::from_hex(0x0071ff)),
    success: Some(Color::from_hex(0x00bb00)),
    red: Some(Color::from_hex(0xbb0000)),
    orange: Some(Color::from_hex(0xe7b000)),
    yellow: Some(Color::from_hex(0xe7b000)),
    green: Some(Color::from_hex(0x00bb00)),
    cyan: Some(Color::from_hex(0x00bbbb)),
    blue: Some(Color::from_hex(0x55ffff)),
    purple: Some(Color::from_hex(0x0071ae)),
    magenta: Some(Color::from_hex(0xff55ff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x79241e),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x555555),
        base03: Color::from_hex(0x6e6e6e),
        base04: Color::from_hex(0x888888),
        base05: Color::from_hex(0xa1a1a1),
        base06: Color::from_hex(0xbbbbbb),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xff3f00),
        base09: Color::from_hex(0xe7b000),
        base0a: Color::from_hex(0x0071ae),
        base0b: Color::from_hex(0x00bb00),
        base0c: Color::from_hex(0x00bbbb),
        base0d: Color::from_hex(0x0071ff),
        base0e: Color::from_hex(0xbb00bb),
        base0f: Color::from_hex(0x7f1f00),
    },
    base10: Color::from_hex(0x383838),
    base11: Color::from_hex(0x1c1c1c),
    base12: Color::from_hex(0xbb0000),
    base13: Color::from_hex(0xe7b000),
    base14: Color::from_hex(0x00bb00),
    base15: Color::from_hex(0x55ffff),
    base16: Color::from_hex(0x0071ae),
    base17: Color::from_hex(0xff55ff),
};
