//! Scarlet Protocol color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Scarlet Protocol
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Scarlet Protocol"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1b153c),
    fg: Color::from_hex(0xafafaf),
    cursor: Some(Color::from_hex(0xafafaf)),
    selection: Some(Color::from_hex(0x676767)),
    line_highlight: Some(Color::from_hex(0x101116)),
    gutter: Some(Color::from_hex(0x7f7f7f)),
    statusbar_bg: Some(Color::from_hex(0x101116)),
    statusbar_fg: Some(Color::from_hex(0x979797)),
    comment: Some(Color::from_hex(0x7f7f7f)),
    keyword: Some(Color::from_hex(0xc930c7)),
    string: Some(Color::from_hex(0x00dc84)),
    function: Some(Color::from_hex(0x0271b6)),
    variable: Some(Color::from_hex(0xff0051)),
    r#type: Some(Color::from_hex(0x6871ff)),
    constant: Some(Color::from_hex(0xfaf945)),
    operator: Some(Color::from_hex(0xafafaf)),
    tag: Some(Color::from_hex(0xff0051)),
    error: Some(Color::from_hex(0xff0051)),
    warning: Some(Color::from_hex(0x6871ff)),
    info: Some(Color::from_hex(0x0271b6)),
    success: Some(Color::from_hex(0x00dc84)),
    red: Some(Color::from_hex(0xff6d67)),
    orange: Some(Color::from_hex(0xfaf945)),
    yellow: Some(Color::from_hex(0xfefb67)),
    green: Some(Color::from_hex(0x5ff967)),
    cyan: Some(Color::from_hex(0x00c5c7)),
    blue: Some(Color::from_hex(0x5ffdff)),
    purple: Some(Color::from_hex(0x6871ff)),
    magenta: Some(Color::from_hex(0xbc35eb)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1b153c),
        base01: Color::from_hex(0x101116),
        base02: Color::from_hex(0x676767),
        base03: Color::from_hex(0x7f7f7f),
        base04: Color::from_hex(0x979797),
        base05: Color::from_hex(0xafafaf),
        base06: Color::from_hex(0xc7c7c7),
        base07: Color::from_hex(0xfeffff),
        base08: Color::from_hex(0xff0051),
        base09: Color::from_hex(0xfaf945),
        base0a: Color::from_hex(0x6871ff),
        base0b: Color::from_hex(0x00dc84),
        base0c: Color::from_hex(0x00c5c7),
        base0d: Color::from_hex(0x0271b6),
        base0e: Color::from_hex(0xc930c7),
        base0f: Color::from_hex(0x7f0028),
    },
    base10: Color::from_hex(0x444444),
    base11: Color::from_hex(0x222222),
    base12: Color::from_hex(0xff6d67),
    base13: Color::from_hex(0xfefb67),
    base14: Color::from_hex(0x5ff967),
    base15: Color::from_hex(0x5ffdff),
    base16: Color::from_hex(0x6871ff),
    base17: Color::from_hex(0xbc35eb),
};
