//! Shades Of Purple color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Shades Of Purple
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Shades Of Purple"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1e1d40),
    fg: Color::from_hex(0xafafaf),
    cursor: Some(Color::from_hex(0xafafaf)),
    selection: Some(Color::from_hex(0x676767)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x7f7f7f)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x979797)),
    comment: Some(Color::from_hex(0x7f7f7f)),
    keyword: Some(Color::from_hex(0xff2b70)),
    string: Some(Color::from_hex(0x3ad900)),
    function: Some(Color::from_hex(0x6943ff)),
    variable: Some(Color::from_hex(0xd90429)),
    r#type: Some(Color::from_hex(0x6871ff)),
    constant: Some(Color::from_hex(0xffe700)),
    operator: Some(Color::from_hex(0xafafaf)),
    tag: Some(Color::from_hex(0xd90429)),
    error: Some(Color::from_hex(0xd90429)),
    warning: Some(Color::from_hex(0x6871ff)),
    info: Some(Color::from_hex(0x6943ff)),
    success: Some(Color::from_hex(0x3ad900)),
    red: Some(Color::from_hex(0xf9291b)),
    orange: Some(Color::from_hex(0xffe700)),
    yellow: Some(Color::from_hex(0xf1d000)),
    green: Some(Color::from_hex(0x42d425)),
    cyan: Some(Color::from_hex(0x00c5c7)),
    blue: Some(Color::from_hex(0x79e7fa)),
    purple: Some(Color::from_hex(0x6871ff)),
    magenta: Some(Color::from_hex(0xff76ff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1e1d40),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x676767),
        base03: Color::from_hex(0x7f7f7f),
        base04: Color::from_hex(0x979797),
        base05: Color::from_hex(0xafafaf),
        base06: Color::from_hex(0xc7c7c7),
        base07: Color::from_hex(0xfeffff),
        base08: Color::from_hex(0xd90429),
        base09: Color::from_hex(0xffe700),
        base0a: Color::from_hex(0x6871ff),
        base0b: Color::from_hex(0x3ad900),
        base0c: Color::from_hex(0x00c5c7),
        base0d: Color::from_hex(0x6943ff),
        base0e: Color::from_hex(0xff2b70),
        base0f: Color::from_hex(0x6c0214),
    },
    base10: Color::from_hex(0x444444),
    base11: Color::from_hex(0x222222),
    base12: Color::from_hex(0xf9291b),
    base13: Color::from_hex(0xf1d000),
    base14: Color::from_hex(0x42d425),
    base15: Color::from_hex(0x79e7fa),
    base16: Color::from_hex(0x6871ff),
    base17: Color::from_hex(0xff76ff),
};
