//! Solarized Dark Patched color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Solarized Dark Patched
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Solarized Dark Patched",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x001e26),
    fg: Color::from_hex(0xc0c0b0),
    cursor: Some(Color::from_hex(0xc0c0b0)),
    selection: Some(Color::from_hex(0x465a61)),
    line_highlight: Some(Color::from_hex(0x002731)),
    gutter: Some(Color::from_hex(0x6e7c7b)),
    statusbar_bg: Some(Color::from_hex(0x002731)),
    statusbar_fg: Some(Color::from_hex(0x979e96)),
    comment: Some(Color::from_hex(0x6e7c7b)),
    keyword: Some(Color::from_hex(0xc61b6e)),
    string: Some(Color::from_hex(0x728905)),
    function: Some(Color::from_hex(0x2075c7)),
    variable: Some(Color::from_hex(0xd01b24)),
    r#type: Some(Color::from_hex(0x708183)),
    constant: Some(Color::from_hex(0xa57705)),
    operator: Some(Color::from_hex(0xc0c0b0)),
    tag: Some(Color::from_hex(0xd01b24)),
    error: Some(Color::from_hex(0xd01b24)),
    warning: Some(Color::from_hex(0x708183)),
    info: Some(Color::from_hex(0x2075c7)),
    success: Some(Color::from_hex(0x728905)),
    red: Some(Color::from_hex(0xbd3612)),
    orange: Some(Color::from_hex(0xa57705)),
    yellow: Some(Color::from_hex(0x52676f)),
    green: Some(Color::from_hex(0x465a61)),
    cyan: Some(Color::from_hex(0x259185)),
    blue: Some(Color::from_hex(0x81908f)),
    purple: Some(Color::from_hex(0x708183)),
    magenta: Some(Color::from_hex(0x5856b9)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x001e26),
        base01: Color::from_hex(0x002731),
        base02: Color::from_hex(0x465a61),
        base03: Color::from_hex(0x6e7c7b),
        base04: Color::from_hex(0x979e96),
        base05: Color::from_hex(0xc0c0b0),
        base06: Color::from_hex(0xe9e2cb),
        base07: Color::from_hex(0xfcf4dc),
        base08: Color::from_hex(0xd01b24),
        base09: Color::from_hex(0xa57705),
        base0a: Color::from_hex(0x708183),
        base0b: Color::from_hex(0x728905),
        base0c: Color::from_hex(0x259185),
        base0d: Color::from_hex(0x2075c7),
        base0e: Color::from_hex(0xc61b6e),
        base0f: Color::from_hex(0x680d12),
    },
    base10: Color::from_hex(0x2e3c40),
    base11: Color::from_hex(0x171e20),
    base12: Color::from_hex(0xbd3612),
    base13: Color::from_hex(0x52676f),
    base14: Color::from_hex(0x465a61),
    base15: Color::from_hex(0x81908f),
    base16: Color::from_hex(0x708183),
    base17: Color::from_hex(0x5856b9),
};
