//! Sundried color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// Sundried
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Sundried",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1a1818),
    fg: Color::from_hex(0xa9a9a7),
    cursor: Some(Color::from_hex(0xa9a9a7)),
    selection: Some(Color::from_hex(0x4d4d47)),
    line_highlight: Some(Color::from_hex(0x302b2a)),
    gutter: Some(Color::from_hex(0x6b6b67)),
    statusbar_bg: Some(Color::from_hex(0x302b2a)),
    statusbar_fg: Some(Color::from_hex(0x8a8a87)),
    comment: Some(Color::from_hex(0x6b6b67)),
    keyword: Some(Color::from_hex(0x854551)),
    string: Some(Color::from_hex(0x577644)),
    function: Some(Color::from_hex(0x485a98)),
    variable: Some(Color::from_hex(0xa6463d)),
    r#type: Some(Color::from_hex(0x7898f7)),
    constant: Some(Color::from_hex(0x9c5f2a)),
    operator: Some(Color::from_hex(0xa9a9a7)),
    tag: Some(Color::from_hex(0xa6463d)),
    error: Some(Color::from_hex(0xa6463d)),
    warning: Some(Color::from_hex(0x7898f7)),
    info: Some(Color::from_hex(0x485a98)),
    success: Some(Color::from_hex(0x577644)),
    red: Some(Color::from_hex(0xaa000c)),
    orange: Some(Color::from_hex(0x9c5f2a)),
    yellow: Some(Color::from_hex(0xfc6a20)),
    green: Some(Color::from_hex(0x128c20)),
    cyan: Some(Color::from_hex(0x9c814e)),
    blue: Some(Color::from_hex(0xfad384)),
    purple: Some(Color::from_hex(0x7898f7)),
    magenta: Some(Color::from_hex(0xfc89a0)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1a1818),
        base01: Color::from_hex(0x302b2a),
        base02: Color::from_hex(0x4d4d47),
        base03: Color::from_hex(0x6b6b67),
        base04: Color::from_hex(0x8a8a87),
        base05: Color::from_hex(0xa9a9a7),
        base06: Color::from_hex(0xc8c8c8),
        base07: Color::from_hex(0xfffefe),
        base08: Color::from_hex(0xa6463d),
        base09: Color::from_hex(0x9c5f2a),
        base0a: Color::from_hex(0x7898f7),
        base0b: Color::from_hex(0x577644),
        base0c: Color::from_hex(0x9c814e),
        base0d: Color::from_hex(0x485a98),
        base0e: Color::from_hex(0x854551),
        base0f: Color::from_hex(0x53231e),
    },
    base10: Color::from_hex(0x33332f),
    base11: Color::from_hex(0x191917),
    base12: Color::from_hex(0xaa000c),
    base13: Color::from_hex(0xfc6a20),
    base14: Color::from_hex(0x128c20),
    base15: Color::from_hex(0xfad384),
    base16: Color::from_hex(0x7898f7),
    base17: Color::from_hex(0xfc89a0),
};
