//! Thayer Bright color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Thayer Bright
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Thayer Bright"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1b1d1e),
    fg: Color::from_hex(0xadada9),
    cursor: Some(Color::from_hex(0xadada9)),
    selection: Some(Color::from_hex(0x505354)),
    line_highlight: Some(Color::from_hex(0x1b1d1e)),
    gutter: Some(Color::from_hex(0x6f7170)),
    statusbar_bg: Some(Color::from_hex(0x1b1d1e)),
    statusbar_fg: Some(Color::from_hex(0x8e8f8d)),
    comment: Some(Color::from_hex(0x6f7170)),
    keyword: Some(Color::from_hex(0x8c54fe)),
    string: Some(Color::from_hex(0x4df740)),
    function: Some(Color::from_hex(0x2656d6)),
    variable: Some(Color::from_hex(0xf92672)),
    r#type: Some(Color::from_hex(0x3f78ff)),
    constant: Some(Color::from_hex(0xf3fd21)),
    operator: Some(Color::from_hex(0xadada9)),
    tag: Some(Color::from_hex(0xf92672)),
    error: Some(Color::from_hex(0xf92672)),
    warning: Some(Color::from_hex(0x3f78ff)),
    info: Some(Color::from_hex(0x2656d6)),
    success: Some(Color::from_hex(0x4df740)),
    red: Some(Color::from_hex(0xff5995)),
    orange: Some(Color::from_hex(0xf3fd21)),
    yellow: Some(Color::from_hex(0xfeed6c)),
    green: Some(Color::from_hex(0xb6e354)),
    cyan: Some(Color::from_hex(0x37c8b4)),
    blue: Some(Color::from_hex(0x23ced4)),
    purple: Some(Color::from_hex(0x3f78ff)),
    magenta: Some(Color::from_hex(0x9e6ffe)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1b1d1e),
        base01: Color::from_hex(0x1b1d1e),
        base02: Color::from_hex(0x505354),
        base03: Color::from_hex(0x6f7170),
        base04: Color::from_hex(0x8e8f8d),
        base05: Color::from_hex(0xadada9),
        base06: Color::from_hex(0xccccc6),
        base07: Color::from_hex(0xf8f8f2),
        base08: Color::from_hex(0xf92672),
        base09: Color::from_hex(0xf3fd21),
        base0a: Color::from_hex(0x3f78ff),
        base0b: Color::from_hex(0x4df740),
        base0c: Color::from_hex(0x37c8b4),
        base0d: Color::from_hex(0x2656d6),
        base0e: Color::from_hex(0x8c54fe),
        base0f: Color::from_hex(0x7c1339),
    },
    base10: Color::from_hex(0x353738),
    base11: Color::from_hex(0x1a1b1c),
    base12: Color::from_hex(0xff5995),
    base13: Color::from_hex(0xfeed6c),
    base14: Color::from_hex(0xb6e354),
    base15: Color::from_hex(0x23ced4),
    base16: Color::from_hex(0x3f78ff),
    base17: Color::from_hex(0x9e6ffe),
};
