//! The Hulk color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};

/// The Hulk
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "The Hulk",
    author: "FredHappyface (https://github.com/fredHappyface)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1b1d1e),
    fg: Color::from_hex(0xb6b6b1),
    cursor: Some(Color::from_hex(0xb6b6b1)),
    selection: Some(Color::from_hex(0x505354)),
    line_highlight: Some(Color::from_hex(0x1b1d1e)),
    gutter: Some(Color::from_hex(0x727473)),
    statusbar_bg: Some(Color::from_hex(0x1b1d1e)),
    statusbar_fg: Some(Color::from_hex(0x949592)),
    comment: Some(Color::from_hex(0x727473)),
    keyword: Some(Color::from_hex(0x641e73)),
    string: Some(Color::from_hex(0x13ce2f)),
    function: Some(Color::from_hex(0x2424f4)),
    variable: Some(Color::from_hex(0x259d1a)),
    r#type: Some(Color::from_hex(0x4f6a95)),
    constant: Some(Color::from_hex(0x62e456)),
    operator: Some(Color::from_hex(0xb6b6b1)),
    tag: Some(Color::from_hex(0x259d1a)),
    error: Some(Color::from_hex(0x259d1a)),
    warning: Some(Color::from_hex(0x4f6a95)),
    info: Some(Color::from_hex(0x2424f4)),
    success: Some(Color::from_hex(0x13ce2f)),
    red: Some(Color::from_hex(0x8dff2a)),
    orange: Some(Color::from_hex(0x62e456)),
    yellow: Some(Color::from_hex(0x3afe15)),
    green: Some(Color::from_hex(0x48ff76)),
    cyan: Some(Color::from_hex(0x378ca9)),
    blue: Some(Color::from_hex(0x3f85a5)),
    purple: Some(Color::from_hex(0x4f6a95)),
    magenta: Some(Color::from_hex(0x72579d)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x1b1d1e),
        base01: Color::from_hex(0x1b1d1e),
        base02: Color::from_hex(0x505354),
        base03: Color::from_hex(0x727473),
        base04: Color::from_hex(0x949592),
        base05: Color::from_hex(0xb6b6b1),
        base06: Color::from_hex(0xd8d8d0),
        base07: Color::from_hex(0xe5e5e0),
        base08: Color::from_hex(0x259d1a),
        base09: Color::from_hex(0x62e456),
        base0a: Color::from_hex(0x4f6a95),
        base0b: Color::from_hex(0x13ce2f),
        base0c: Color::from_hex(0x378ca9),
        base0d: Color::from_hex(0x2424f4),
        base0e: Color::from_hex(0x641e73),
        base0f: Color::from_hex(0x124e0d),
    },
    base10: Color::from_hex(0x353738),
    base11: Color::from_hex(0x1a1b1c),
    base12: Color::from_hex(0x8dff2a),
    base13: Color::from_hex(0x3afe15),
    base14: Color::from_hex(0x48ff76),
    base15: Color::from_hex(0x3f85a5),
    base16: Color::from_hex(0x4f6a95),
    base17: Color::from_hex(0x72579d),
};
