//! Tokyo Night Moon color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Tokyo Night Moon
///
/// Author: Michaël Ball, based on Tokyo Night by enkia (https://github.com/enkia/tokyo-night-vscode-theme)
/// Variant: Dark
/// Contrast: High
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Tokyo Night Moon"),
    author: Cow::Borrowed(
        "Michaël Ball, based on Tokyo Night by enkia (https://github.com/enkia/tokyo-night-vscode-theme)",
    ),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x222436),
    fg: Color::from_hex(0xc8d3f5),
    cursor: Some(Color::from_hex(0xc8d3f5)),
    selection: Some(Color::from_hex(0x2f334d)),
    line_highlight: Some(Color::from_hex(0x1e2030)),
    gutter: Some(Color::from_hex(0x444a73)),
    statusbar_bg: Some(Color::from_hex(0x1e2030)),
    statusbar_fg: Some(Color::from_hex(0x828bb8)),
    comment: Some(Color::from_hex(0x444a73)),
    keyword: Some(Color::from_hex(0xfca7ea)),
    string: Some(Color::from_hex(0xc3e88d)),
    function: Some(Color::from_hex(0x82aaff)),
    variable: Some(Color::from_hex(0xc099ff)),
    r#type: Some(Color::from_hex(0xffc777)),
    constant: Some(Color::from_hex(0xffc777)),
    operator: Some(Color::from_hex(0xc8d3f5)),
    tag: Some(Color::from_hex(0xc099ff)),
    error: Some(Color::from_hex(0xc099ff)),
    warning: Some(Color::from_hex(0xffc777)),
    info: Some(Color::from_hex(0x82aaff)),
    success: Some(Color::from_hex(0xc3e88d)),
    red: Some(Color::from_hex(0xff757f)),
    orange: Some(Color::from_hex(0xffc777)),
    yellow: Some(Color::from_hex(0xffd793)),
    green: Some(Color::from_hex(0xc3e88d)),
    cyan: Some(Color::from_hex(0x86e1fc)),
    blue: Some(Color::from_hex(0x86e1fc)),
    purple: Some(Color::from_hex(0x82aaff)),
    magenta: Some(Color::from_hex(0xfca7ea)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x222436),
        base01: Color::from_hex(0x1e2030),
        base02: Color::from_hex(0x2f334d),
        base03: Color::from_hex(0x444a73),
        base04: Color::from_hex(0x828bb8),
        base05: Color::from_hex(0xc8d3f5),
        base06: Color::from_hex(0xb4c2f0),
        base07: Color::from_hex(0xc8d3f5),
        base08: Color::from_hex(0xc099ff),
        base09: Color::from_hex(0xffc777),
        base0a: Color::from_hex(0xffc777),
        base0b: Color::from_hex(0xc3e88d),
        base0c: Color::from_hex(0x86e1fc),
        base0d: Color::from_hex(0x82aaff),
        base0e: Color::from_hex(0xfca7ea),
        base0f: Color::from_hex(0xc53b53),
    },
    base10: Color::from_hex(0x1e2030),
    base11: Color::from_hex(0x1a1b2a),
    base12: Color::from_hex(0xff757f),
    base13: Color::from_hex(0xffd793),
    base14: Color::from_hex(0xc3e88d),
    base15: Color::from_hex(0x86e1fc),
    base16: Color::from_hex(0x82aaff),
    base17: Color::from_hex(0xfca7ea),
};
