//! Warm Neon color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Warm Neon
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Warm Neon"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x3f3f3f),
    fg: Color::from_hex(0xdcc9ba),
    cursor: Some(Color::from_hex(0xdcc9ba)),
    selection: Some(Color::from_hex(0xfdfcfc)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0xf2ebe6)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0xe7dad0)),
    comment: Some(Color::from_hex(0xf2ebe6)),
    keyword: Some(Color::from_hex(0xf81ffb)),
    string: Some(Color::from_hex(0x38b139)),
    function: Some(Color::from_hex(0x4260c5)),
    variable: Some(Color::from_hex(0xe24345)),
    r#type: Some(Color::from_hex(0x7a90d5)),
    constant: Some(Color::from_hex(0xdae145)),
    operator: Some(Color::from_hex(0xdcc9ba)),
    tag: Some(Color::from_hex(0xe24345)),
    error: Some(Color::from_hex(0xe24345)),
    warning: Some(Color::from_hex(0x7a90d5)),
    info: Some(Color::from_hex(0x4260c5)),
    success: Some(Color::from_hex(0x38b139)),
    red: Some(Color::from_hex(0xe86f71)),
    orange: Some(Color::from_hex(0xdae145)),
    yellow: Some(Color::from_hex(0xddd979)),
    green: Some(Color::from_hex(0x9bc08f)),
    cyan: Some(Color::from_hex(0x29bad3)),
    blue: Some(Color::from_hex(0x5ed1e4)),
    purple: Some(Color::from_hex(0x7a90d5)),
    magenta: Some(Color::from_hex(0xf674b9)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x3f3f3f),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0xfdfcfc),
        base03: Color::from_hex(0xf2ebe6),
        base04: Color::from_hex(0xe7dad0),
        base05: Color::from_hex(0xdcc9ba),
        base06: Color::from_hex(0xd0b8a3),
        base07: Color::from_hex(0xd8c8bb),
        base08: Color::from_hex(0xe24345),
        base09: Color::from_hex(0xdae145),
        base0a: Color::from_hex(0x7a90d5),
        base0b: Color::from_hex(0x38b139),
        base0c: Color::from_hex(0x29bad3),
        base0d: Color::from_hex(0x4260c5),
        base0e: Color::from_hex(0xf81ffb),
        base0f: Color::from_hex(0x712122),
    },
    base10: Color::from_hex(0xa8a8a8),
    base11: Color::from_hex(0x545454),
    base12: Color::from_hex(0xe86f71),
    base13: Color::from_hex(0xddd979),
    base14: Color::from_hex(0x9bc08f),
    base15: Color::from_hex(0x5ed1e4),
    base16: Color::from_hex(0x7a90d5),
    base17: Color::from_hex(0xf674b9),
};
