//! Wez color theme (base24).
//!
//! Auto-generated by `cargo xtask generate base24` — do not edit.

use crate::{Base16Palette, Base24Palette, Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Wez
///
/// Author: FredHappyface (https://github.com/fredHappyface)
/// Variant: Dark
/// Contrast: Normal
/// Source: base24 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Wez"),
    author: Cow::Borrowed("FredHappyface (https://github.com/fredHappyface)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xaeaeae),
    cursor: Some(Color::from_hex(0xaeaeae)),
    selection: Some(Color::from_hex(0x555555)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x727272)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0x909090)),
    comment: Some(Color::from_hex(0x727272)),
    keyword: Some(Color::from_hex(0xcc55cc)),
    string: Some(Color::from_hex(0x55cc55)),
    function: Some(Color::from_hex(0x5455cb)),
    variable: Some(Color::from_hex(0xcc5555)),
    r#type: Some(Color::from_hex(0x5555ff)),
    constant: Some(Color::from_hex(0xcdcd55)),
    operator: Some(Color::from_hex(0xaeaeae)),
    tag: Some(Color::from_hex(0xcc5555)),
    error: Some(Color::from_hex(0xcc5555)),
    warning: Some(Color::from_hex(0x5555ff)),
    info: Some(Color::from_hex(0x5455cb)),
    success: Some(Color::from_hex(0x55cc55)),
    red: Some(Color::from_hex(0xff5555)),
    orange: Some(Color::from_hex(0xcdcd55)),
    yellow: Some(Color::from_hex(0xffff55)),
    green: Some(Color::from_hex(0x55ff55)),
    cyan: Some(Color::from_hex(0x7acaca)),
    blue: Some(Color::from_hex(0x55ffff)),
    purple: Some(Color::from_hex(0x5555ff)),
    magenta: Some(Color::from_hex(0xff55ff)),
};

/// Full base24 palette with all 24 color slots.
pub const PALETTE: Base24Palette = Base24Palette {
    base: Base16Palette {
        base00: Color::from_hex(0x000000),
        base01: Color::from_hex(0x000000),
        base02: Color::from_hex(0x555555),
        base03: Color::from_hex(0x727272),
        base04: Color::from_hex(0x909090),
        base05: Color::from_hex(0xaeaeae),
        base06: Color::from_hex(0xcccccc),
        base07: Color::from_hex(0xffffff),
        base08: Color::from_hex(0xcc5555),
        base09: Color::from_hex(0xcdcd55),
        base0a: Color::from_hex(0x5555ff),
        base0b: Color::from_hex(0x55cc55),
        base0c: Color::from_hex(0x7acaca),
        base0d: Color::from_hex(0x5455cb),
        base0e: Color::from_hex(0xcc55cc),
        base0f: Color::from_hex(0x662a2a),
    },
    base10: Color::from_hex(0x383838),
    base11: Color::from_hex(0x1c1c1c),
    base12: Color::from_hex(0xff5555),
    base13: Color::from_hex(0xffff55),
    base14: Color::from_hex(0x55ff55),
    base15: Color::from_hex(0x55ffff),
    base16: Color::from_hex(0x5555ff),
    base17: Color::from_hex(0xff55ff),
};
