//! Apprentice color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Apprentice
///
/// Author: romainl
/// Variant: Dark
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Apprentice",
    author: "romainl",
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x262626),
    fg: Color::from_hex(0x5f5f87),
    cursor: Some(Color::from_hex(0x5f5f87)),
    selection: Some(Color::from_hex(0x5f875f)),
    line_highlight: Some(Color::from_hex(0xaf5f5f)),
    gutter: Some(Color::from_hex(0x87875f)),
    statusbar_bg: Some(Color::from_hex(0xaf5f5f)),
    statusbar_fg: Some(Color::from_hex(0x5f87af)),
    comment: Some(Color::from_hex(0x87875f)),
    keyword: Some(Color::from_hex(0x5fafaf)),
    string: Some(Color::from_hex(0xffffaf)),
    function: Some(Color::from_hex(0x8787af)),
    variable: Some(Color::from_hex(0x444444)),
    r#type: Some(Color::from_hex(0x87af87)),
    constant: Some(Color::from_hex(0xff8700)),
    operator: Some(Color::from_hex(0x5f5f87)),
    tag: Some(Color::from_hex(0x444444)),
    error: Some(Color::from_hex(0x444444)),
    warning: Some(Color::from_hex(0x87af87)),
    info: Some(Color::from_hex(0x8787af)),
    success: Some(Color::from_hex(0xffffaf)),
    red: Some(Color::from_hex(0x444444)),
    orange: Some(Color::from_hex(0xff8700)),
    yellow: Some(Color::from_hex(0x87af87)),
    green: Some(Color::from_hex(0xffffaf)),
    cyan: Some(Color::from_hex(0x87afd7)),
    blue: Some(Color::from_hex(0x8787af)),
    purple: Some(Color::from_hex(0x5fafaf)),
    magenta: Some(Color::from_hex(0xbcbcbc)),
};
