//! Ascendancy color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Ascendancy
///
/// Author: EmergentMind (https://github.com/emergentmind/ascendancy-scheme)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Ascendancy"),
    author: Cow::Borrowed("EmergentMind (https://github.com/emergentmind/ascendancy-scheme)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x282828),
    fg: Color::from_hex(0xd5c7a1),
    cursor: Some(Color::from_hex(0xd5c7a1)),
    selection: Some(Color::from_hex(0x504945)),
    line_highlight: Some(Color::from_hex(0x212f3d)),
    gutter: Some(Color::from_hex(0x928374)),
    statusbar_bg: Some(Color::from_hex(0x212f3d)),
    statusbar_fg: Some(Color::from_hex(0xbdae93)),
    comment: Some(Color::from_hex(0x928374)),
    keyword: Some(Color::from_hex(0xfabd2f)),
    string: Some(Color::from_hex(0xb8bb26)),
    function: Some(Color::from_hex(0x458588)),
    variable: Some(Color::from_hex(0xd05000)),
    r#type: Some(Color::from_hex(0xffcc1b)),
    constant: Some(Color::from_hex(0xfe8019)),
    operator: Some(Color::from_hex(0xd5c7a1)),
    tag: Some(Color::from_hex(0xd05000)),
    error: Some(Color::from_hex(0xd05000)),
    warning: Some(Color::from_hex(0xffcc1b)),
    info: Some(Color::from_hex(0x458588)),
    success: Some(Color::from_hex(0xb8bb26)),
    red: Some(Color::from_hex(0xd05000)),
    orange: Some(Color::from_hex(0xfe8019)),
    yellow: Some(Color::from_hex(0xffcc1b)),
    green: Some(Color::from_hex(0xb8bb26)),
    cyan: Some(Color::from_hex(0x8f3f71)),
    blue: Some(Color::from_hex(0x458588)),
    purple: Some(Color::from_hex(0xfabd2f)),
    magenta: Some(Color::from_hex(0xb59b4d)),
};
