//! Ashes color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Ashes
///
/// Author: Jannik Siebert (https://github.com/janniks)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Ashes",
    author: "Jannik Siebert (https://github.com/janniks)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1c2023),
    fg: Color::from_hex(0xc7ccd1),
    cursor: Some(Color::from_hex(0xc7ccd1)),
    selection: Some(Color::from_hex(0x565e65)),
    line_highlight: Some(Color::from_hex(0x393f45)),
    gutter: Some(Color::from_hex(0x747c84)),
    statusbar_bg: Some(Color::from_hex(0x393f45)),
    statusbar_fg: Some(Color::from_hex(0xadb3ba)),
    comment: Some(Color::from_hex(0x747c84)),
    keyword: Some(Color::from_hex(0xc795ae)),
    string: Some(Color::from_hex(0x95c7ae)),
    function: Some(Color::from_hex(0xae95c7)),
    variable: Some(Color::from_hex(0xc7ae95)),
    r#type: Some(Color::from_hex(0xaec795)),
    constant: Some(Color::from_hex(0xc7c795)),
    operator: Some(Color::from_hex(0xc7ccd1)),
    tag: Some(Color::from_hex(0xc7ae95)),
    error: Some(Color::from_hex(0xc7ae95)),
    warning: Some(Color::from_hex(0xaec795)),
    info: Some(Color::from_hex(0xae95c7)),
    success: Some(Color::from_hex(0x95c7ae)),
    red: Some(Color::from_hex(0xc7ae95)),
    orange: Some(Color::from_hex(0xc7c795)),
    yellow: Some(Color::from_hex(0xaec795)),
    green: Some(Color::from_hex(0x95c7ae)),
    cyan: Some(Color::from_hex(0x95aec7)),
    blue: Some(Color::from_hex(0xae95c7)),
    purple: Some(Color::from_hex(0xc795ae)),
    magenta: Some(Color::from_hex(0xc79595)),
};
