//! Atelier Sulphurpool Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Atelier Sulphurpool Light
///
/// Author: Bram de Haan (http://atelierbramdehaan.nl)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Atelier Sulphurpool Light"),
    author: Cow::Borrowed("Bram de Haan (http://atelierbramdehaan.nl)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf5f7ff),
    fg: Color::from_hex(0x5e6687),
    cursor: Some(Color::from_hex(0x5e6687)),
    selection: Some(Color::from_hex(0x979db4)),
    line_highlight: Some(Color::from_hex(0xdfe2f1)),
    gutter: Some(Color::from_hex(0x898ea4)),
    statusbar_bg: Some(Color::from_hex(0xdfe2f1)),
    statusbar_fg: Some(Color::from_hex(0x6b7394)),
    comment: Some(Color::from_hex(0x898ea4)),
    keyword: Some(Color::from_hex(0x6679cc)),
    string: Some(Color::from_hex(0xac9739)),
    function: Some(Color::from_hex(0x3d8fd1)),
    variable: Some(Color::from_hex(0xc94922)),
    r#type: Some(Color::from_hex(0xc08b30)),
    constant: Some(Color::from_hex(0xc76b29)),
    operator: Some(Color::from_hex(0x5e6687)),
    tag: Some(Color::from_hex(0xc94922)),
    error: Some(Color::from_hex(0xc94922)),
    warning: Some(Color::from_hex(0xc08b30)),
    info: Some(Color::from_hex(0x3d8fd1)),
    success: Some(Color::from_hex(0xac9739)),
    red: Some(Color::from_hex(0xc94922)),
    orange: Some(Color::from_hex(0xc76b29)),
    yellow: Some(Color::from_hex(0xc08b30)),
    green: Some(Color::from_hex(0xac9739)),
    cyan: Some(Color::from_hex(0x22a2c9)),
    blue: Some(Color::from_hex(0x3d8fd1)),
    purple: Some(Color::from_hex(0x6679cc)),
    magenta: Some(Color::from_hex(0x9c637a)),
};
