//! Atelier Dune Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Atelier Dune Light
///
/// Author: Bram de Haan (http://atelierbramdehaan.nl)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Atelier Dune Light"),
    author: Cow::Borrowed("Bram de Haan (http://atelierbramdehaan.nl)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xfefbec),
    fg: Color::from_hex(0x6e6b5e),
    cursor: Some(Color::from_hex(0x6e6b5e)),
    selection: Some(Color::from_hex(0xa6a28c)),
    line_highlight: Some(Color::from_hex(0xe8e4cf)),
    gutter: Some(Color::from_hex(0x999580)),
    statusbar_bg: Some(Color::from_hex(0xe8e4cf)),
    statusbar_fg: Some(Color::from_hex(0x7d7a68)),
    comment: Some(Color::from_hex(0x999580)),
    keyword: Some(Color::from_hex(0xb854d4)),
    string: Some(Color::from_hex(0x60ac39)),
    function: Some(Color::from_hex(0x6684e1)),
    variable: Some(Color::from_hex(0xd73737)),
    r#type: Some(Color::from_hex(0xae9513)),
    constant: Some(Color::from_hex(0xb65611)),
    operator: Some(Color::from_hex(0x6e6b5e)),
    tag: Some(Color::from_hex(0xd73737)),
    error: Some(Color::from_hex(0xd73737)),
    warning: Some(Color::from_hex(0xae9513)),
    info: Some(Color::from_hex(0x6684e1)),
    success: Some(Color::from_hex(0x60ac39)),
    red: Some(Color::from_hex(0xd73737)),
    orange: Some(Color::from_hex(0xb65611)),
    yellow: Some(Color::from_hex(0xae9513)),
    green: Some(Color::from_hex(0x60ac39)),
    cyan: Some(Color::from_hex(0x1fad83)),
    blue: Some(Color::from_hex(0x6684e1)),
    purple: Some(Color::from_hex(0xb854d4)),
    magenta: Some(Color::from_hex(0xd43552)),
};
