//! Atelier Cave Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Atelier Cave Light
///
/// Author: Bram de Haan (http://atelierbramdehaan.nl)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Atelier Cave Light"),
    author: Cow::Borrowed("Bram de Haan (http://atelierbramdehaan.nl)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xefecf4),
    fg: Color::from_hex(0x585260),
    cursor: Some(Color::from_hex(0x585260)),
    selection: Some(Color::from_hex(0x8b8792)),
    line_highlight: Some(Color::from_hex(0xe2dfe7)),
    gutter: Some(Color::from_hex(0x7e7887)),
    statusbar_bg: Some(Color::from_hex(0xe2dfe7)),
    statusbar_fg: Some(Color::from_hex(0x655f6d)),
    comment: Some(Color::from_hex(0x7e7887)),
    keyword: Some(Color::from_hex(0x955ae7)),
    string: Some(Color::from_hex(0x2a9292)),
    function: Some(Color::from_hex(0x576ddb)),
    variable: Some(Color::from_hex(0xbe4678)),
    r#type: Some(Color::from_hex(0xa06e3b)),
    constant: Some(Color::from_hex(0xaa573c)),
    operator: Some(Color::from_hex(0x585260)),
    tag: Some(Color::from_hex(0xbe4678)),
    error: Some(Color::from_hex(0xbe4678)),
    warning: Some(Color::from_hex(0xa06e3b)),
    info: Some(Color::from_hex(0x576ddb)),
    success: Some(Color::from_hex(0x2a9292)),
    red: Some(Color::from_hex(0xbe4678)),
    orange: Some(Color::from_hex(0xaa573c)),
    yellow: Some(Color::from_hex(0xa06e3b)),
    green: Some(Color::from_hex(0x2a9292)),
    cyan: Some(Color::from_hex(0x398bc6)),
    blue: Some(Color::from_hex(0x576ddb)),
    purple: Some(Color::from_hex(0x955ae7)),
    magenta: Some(Color::from_hex(0xbf40bf)),
};
