//! Atlas color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Atlas
///
/// Author: Alex Lende (https://ajlende.com)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Atlas"),
    author: Cow::Borrowed("Alex Lende (https://ajlende.com)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x002635),
    fg: Color::from_hex(0xa1a19a),
    cursor: Some(Color::from_hex(0xa1a19a)),
    selection: Some(Color::from_hex(0x517f8d)),
    line_highlight: Some(Color::from_hex(0x00384d)),
    gutter: Some(Color::from_hex(0x6c8b91)),
    statusbar_bg: Some(Color::from_hex(0x00384d)),
    statusbar_fg: Some(Color::from_hex(0x869696)),
    comment: Some(Color::from_hex(0x6c8b91)),
    keyword: Some(Color::from_hex(0x9a70a4)),
    string: Some(Color::from_hex(0x7fc06e)),
    function: Some(Color::from_hex(0x14747e)),
    variable: Some(Color::from_hex(0xff5a67)),
    r#type: Some(Color::from_hex(0xffcc1b)),
    constant: Some(Color::from_hex(0xf08e48)),
    operator: Some(Color::from_hex(0xa1a19a)),
    tag: Some(Color::from_hex(0xff5a67)),
    error: Some(Color::from_hex(0xff5a67)),
    warning: Some(Color::from_hex(0xffcc1b)),
    info: Some(Color::from_hex(0x14747e)),
    success: Some(Color::from_hex(0x7fc06e)),
    red: Some(Color::from_hex(0xff5a67)),
    orange: Some(Color::from_hex(0xf08e48)),
    yellow: Some(Color::from_hex(0xffcc1b)),
    green: Some(Color::from_hex(0x7fc06e)),
    cyan: Some(Color::from_hex(0x5dd7b9)),
    blue: Some(Color::from_hex(0x14747e)),
    purple: Some(Color::from_hex(0x9a70a4)),
    magenta: Some(Color::from_hex(0xc43060)),
};
