//! Ayu Dark color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Ayu Dark
///
/// Author: Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Ayu Dark",
    author: "Tinted Theming (https://github.com/tinted-theming), Ayu Theme (https://github.com/ayu-theme)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0b0e14),
    fg: Color::from_hex(0xe6e1cf),
    cursor: Some(Color::from_hex(0xe6e1cf)),
    selection: Some(Color::from_hex(0x202229)),
    line_highlight: Some(Color::from_hex(0x131721)),
    gutter: Some(Color::from_hex(0x3e4b59)),
    statusbar_bg: Some(Color::from_hex(0x131721)),
    statusbar_fg: Some(Color::from_hex(0xbfbdb6)),
    comment: Some(Color::from_hex(0x3e4b59)),
    keyword: Some(Color::from_hex(0xd2a6ff)),
    string: Some(Color::from_hex(0xaad94c)),
    function: Some(Color::from_hex(0x59c2ff)),
    variable: Some(Color::from_hex(0xf07178)),
    r#type: Some(Color::from_hex(0xffb454)),
    constant: Some(Color::from_hex(0xff8f40)),
    operator: Some(Color::from_hex(0xe6e1cf)),
    tag: Some(Color::from_hex(0xf07178)),
    error: Some(Color::from_hex(0xf07178)),
    warning: Some(Color::from_hex(0xffb454)),
    info: Some(Color::from_hex(0x59c2ff)),
    success: Some(Color::from_hex(0xaad94c)),
    red: Some(Color::from_hex(0xf07178)),
    orange: Some(Color::from_hex(0xff8f40)),
    yellow: Some(Color::from_hex(0xffb454)),
    green: Some(Color::from_hex(0xaad94c)),
    cyan: Some(Color::from_hex(0x95e6cb)),
    blue: Some(Color::from_hex(0x59c2ff)),
    purple: Some(Color::from_hex(0xd2a6ff)),
    magenta: Some(Color::from_hex(0xe6b450)),
};
