//! Aztec color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Aztec
///
/// Author: TheNeverMan (github.com/TheNeverMan)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Aztec",
    author: "TheNeverMan (github.com/TheNeverMan)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x101600),
    fg: Color::from_hex(0xffda51),
    cursor: Some(Color::from_hex(0xffda51)),
    selection: Some(Color::from_hex(0x242604)),
    line_highlight: Some(Color::from_hex(0x1a1e01)),
    gutter: Some(Color::from_hex(0x2e2e05)),
    statusbar_bg: Some(Color::from_hex(0x1a1e01)),
    statusbar_fg: Some(Color::from_hex(0xffd129)),
    comment: Some(Color::from_hex(0x2e2e05)),
    keyword: Some(Color::from_hex(0x883e9f)),
    string: Some(Color::from_hex(0x63d932)),
    function: Some(Color::from_hex(0x5b4a9f)),
    variable: Some(Color::from_hex(0xee2e00)),
    r#type: Some(Color::from_hex(0xeebb00)),
    constant: Some(Color::from_hex(0xee8800)),
    operator: Some(Color::from_hex(0xffda51)),
    tag: Some(Color::from_hex(0xee2e00)),
    error: Some(Color::from_hex(0xee2e00)),
    warning: Some(Color::from_hex(0xeebb00)),
    info: Some(Color::from_hex(0x5b4a9f)),
    success: Some(Color::from_hex(0x63d932)),
    red: Some(Color::from_hex(0xee2e00)),
    orange: Some(Color::from_hex(0xee8800)),
    yellow: Some(Color::from_hex(0xeebb00)),
    green: Some(Color::from_hex(0x63d932)),
    cyan: Some(Color::from_hex(0x3d94a5)),
    blue: Some(Color::from_hex(0x5b4a9f)),
    purple: Some(Color::from_hex(0x883e9f)),
    magenta: Some(Color::from_hex(0xa928b9)),
};
