//! Blueish color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Blueish
///
/// Author: Ben Mayoras
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Blueish"),
    author: Cow::Borrowed("Ben Mayoras"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x182430),
    fg: Color::from_hex(0xc8e1f8),
    cursor: Some(Color::from_hex(0xc8e1f8)),
    selection: Some(Color::from_hex(0x46290a)),
    line_highlight: Some(Color::from_hex(0x243c54)),
    gutter: Some(Color::from_hex(0x616d78)),
    statusbar_bg: Some(Color::from_hex(0x243c54)),
    statusbar_fg: Some(Color::from_hex(0x74afe7)),
    comment: Some(Color::from_hex(0x616d78)),
    keyword: Some(Color::from_hex(0xff84dd)),
    string: Some(Color::from_hex(0xc3e88d)),
    function: Some(Color::from_hex(0x82aaff)),
    variable: Some(Color::from_hex(0x4ce587)),
    r#type: Some(Color::from_hex(0xf6cd5c)),
    constant: Some(Color::from_hex(0xf6a85c)),
    operator: Some(Color::from_hex(0xc8e1f8)),
    tag: Some(Color::from_hex(0x4ce587)),
    error: Some(Color::from_hex(0x4ce587)),
    warning: Some(Color::from_hex(0xf6cd5c)),
    info: Some(Color::from_hex(0x82aaff)),
    success: Some(Color::from_hex(0xc3e88d)),
    red: Some(Color::from_hex(0x4ce587)),
    orange: Some(Color::from_hex(0xf6a85c)),
    yellow: Some(Color::from_hex(0xf6cd5c)),
    green: Some(Color::from_hex(0xc3e88d)),
    cyan: Some(Color::from_hex(0x5fd1ff)),
    blue: Some(Color::from_hex(0x82aaff)),
    purple: Some(Color::from_hex(0xff84dd)),
    magenta: Some(Color::from_hex(0xbbd2e8)),
};
