//! Blue Forest color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Blue Forest
///
/// Author: alonsodomin (https://github.com/alonsodomin)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Blue Forest"),
    author: Cow::Borrowed("alonsodomin (https://github.com/alonsodomin)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x141f2e),
    fg: Color::from_hex(0xffcc33),
    cursor: Some(Color::from_hex(0xffcc33)),
    selection: Some(Color::from_hex(0x273e5c)),
    line_highlight: Some(Color::from_hex(0x1e5c1e)),
    gutter: Some(Color::from_hex(0xa0ffa0)),
    statusbar_bg: Some(Color::from_hex(0x1e5c1e)),
    statusbar_fg: Some(Color::from_hex(0x1e5c1e)),
    comment: Some(Color::from_hex(0xa0ffa0)),
    keyword: Some(Color::from_hex(0x0099ff)),
    string: Some(Color::from_hex(0x80ff80)),
    function: Some(Color::from_hex(0xa2cff5)),
    variable: Some(Color::from_hex(0xfffab1)),
    r#type: Some(Color::from_hex(0x91ccff)),
    constant: Some(Color::from_hex(0xff8080)),
    operator: Some(Color::from_hex(0xffcc33)),
    tag: Some(Color::from_hex(0xfffab1)),
    error: Some(Color::from_hex(0xfffab1)),
    warning: Some(Color::from_hex(0x91ccff)),
    info: Some(Color::from_hex(0xa2cff5)),
    success: Some(Color::from_hex(0x80ff80)),
    red: Some(Color::from_hex(0xfffab1)),
    orange: Some(Color::from_hex(0xff8080)),
    yellow: Some(Color::from_hex(0x91ccff)),
    green: Some(Color::from_hex(0x80ff80)),
    cyan: Some(Color::from_hex(0x80ff80)),
    blue: Some(Color::from_hex(0xa2cff5)),
    purple: Some(Color::from_hex(0x0099ff)),
    magenta: Some(Color::from_hex(0xe7e7e7)),
};
