//! Brewer color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Brewer
///
/// Author: Timothée Poisot (http://github.com/tpoisot)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Brewer"),
    author: Cow::Borrowed("Timothée Poisot (http://github.com/tpoisot)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x0c0d0e),
    fg: Color::from_hex(0xb7b8b9),
    cursor: Some(Color::from_hex(0xb7b8b9)),
    selection: Some(Color::from_hex(0x515253)),
    line_highlight: Some(Color::from_hex(0x2e2f30)),
    gutter: Some(Color::from_hex(0x737475)),
    statusbar_bg: Some(Color::from_hex(0x2e2f30)),
    statusbar_fg: Some(Color::from_hex(0x959697)),
    comment: Some(Color::from_hex(0x737475)),
    keyword: Some(Color::from_hex(0x756bb1)),
    string: Some(Color::from_hex(0x31a354)),
    function: Some(Color::from_hex(0x3182bd)),
    variable: Some(Color::from_hex(0xe31a1c)),
    r#type: Some(Color::from_hex(0xdca060)),
    constant: Some(Color::from_hex(0xe6550d)),
    operator: Some(Color::from_hex(0xb7b8b9)),
    tag: Some(Color::from_hex(0xe31a1c)),
    error: Some(Color::from_hex(0xe31a1c)),
    warning: Some(Color::from_hex(0xdca060)),
    info: Some(Color::from_hex(0x3182bd)),
    success: Some(Color::from_hex(0x31a354)),
    red: Some(Color::from_hex(0xe31a1c)),
    orange: Some(Color::from_hex(0xe6550d)),
    yellow: Some(Color::from_hex(0xdca060)),
    green: Some(Color::from_hex(0x31a354)),
    cyan: Some(Color::from_hex(0x80b1d3)),
    blue: Some(Color::from_hex(0x3182bd)),
    purple: Some(Color::from_hex(0x756bb1)),
    magenta: Some(Color::from_hex(0xb15928)),
};
