//! Brogrammer color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Brogrammer
///
/// Author: Vik Ramanujam (http://github.com/piggyslasher)
/// Variant: Dark
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Brogrammer",
    author: "Vik Ramanujam (http://github.com/piggyslasher)",
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x1f1f1f),
    fg: Color::from_hex(0x4e5ab7),
    cursor: Some(Color::from_hex(0x4e5ab7)),
    selection: Some(Color::from_hex(0x2dc55e)),
    line_highlight: Some(Color::from_hex(0xf81118)),
    gutter: Some(Color::from_hex(0xecba0f)),
    statusbar_bg: Some(Color::from_hex(0xf81118)),
    statusbar_fg: Some(Color::from_hex(0x2a84d2)),
    comment: Some(Color::from_hex(0xecba0f)),
    keyword: Some(Color::from_hex(0x0f7ddb)),
    string: Some(Color::from_hex(0xf3bd09)),
    function: Some(Color::from_hex(0x5350b9)),
    variable: Some(Color::from_hex(0xd6dbe5)),
    r#type: Some(Color::from_hex(0x1dd361)),
    constant: Some(Color::from_hex(0xde352e)),
    operator: Some(Color::from_hex(0x4e5ab7)),
    tag: Some(Color::from_hex(0xd6dbe5)),
    error: Some(Color::from_hex(0xd6dbe5)),
    warning: Some(Color::from_hex(0x1dd361)),
    info: Some(Color::from_hex(0x5350b9)),
    success: Some(Color::from_hex(0xf3bd09)),
    red: Some(Color::from_hex(0xd6dbe5)),
    orange: Some(Color::from_hex(0xde352e)),
    yellow: Some(Color::from_hex(0x1dd361)),
    green: Some(Color::from_hex(0xf3bd09)),
    cyan: Some(Color::from_hex(0x1081d6)),
    blue: Some(Color::from_hex(0x5350b9)),
    purple: Some(Color::from_hex(0x0f7ddb)),
    magenta: Some(Color::from_hex(0xffffff)),
};
