//! Charcoal Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Charcoal Light
///
/// Author: Mubin Muhammad (https://github.com/mubin6th)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Charcoal Light"),
    author: Cow::Borrowed("Mubin Muhammad (https://github.com/mubin6th)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xcabda0),
    fg: Color::from_hex(0x382e1b),
    cursor: Some(Color::from_hex(0x382e1b)),
    selection: Some(Color::from_hex(0xaf9f7d)),
    line_highlight: Some(Color::from_hex(0xbcad8c)),
    gutter: Some(Color::from_hex(0x645538)),
    statusbar_bg: Some(Color::from_hex(0xbcad8c)),
    statusbar_fg: Some(Color::from_hex(0x110e06)),
    comment: Some(Color::from_hex(0x645538)),
    keyword: Some(Color::from_hex(0x382e1b)),
    string: Some(Color::from_hex(0x110e06)),
    function: Some(Color::from_hex(0x251e0f)),
    variable: Some(Color::from_hex(0x382e1b)),
    r#type: Some(Color::from_hex(0x110e06)),
    constant: Some(Color::from_hex(0x110e06)),
    operator: Some(Color::from_hex(0x382e1b)),
    tag: Some(Color::from_hex(0x382e1b)),
    error: Some(Color::from_hex(0x382e1b)),
    warning: Some(Color::from_hex(0x110e06)),
    info: Some(Color::from_hex(0x251e0f)),
    success: Some(Color::from_hex(0x110e06)),
    red: Some(Color::from_hex(0x382e1b)),
    orange: Some(Color::from_hex(0x110e06)),
    yellow: Some(Color::from_hex(0x110e06)),
    green: Some(Color::from_hex(0x110e06)),
    cyan: Some(Color::from_hex(0x110e06)),
    blue: Some(Color::from_hex(0x251e0f)),
    purple: Some(Color::from_hex(0x382e1b)),
    magenta: Some(Color::from_hex(0x4b3e26)),
};
