//! Chicago Day color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Chicago Day
///
/// Author: Wendell, Ryan <ryanjwendell@gmail.com>
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Chicago Day",
    author: "Wendell, Ryan <ryanjwendell@gmail.com>",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xe8f0ea),
    fg: Color::from_hex(0x364c40),
    cursor: Some(Color::from_hex(0x364c40)),
    selection: Some(Color::from_hex(0xb9d0c3)),
    line_highlight: Some(Color::from_hex(0xd1e0d7)),
    gutter: Some(Color::from_hex(0x8a9a91)),
    statusbar_bg: Some(Color::from_hex(0xd1e0d7)),
    statusbar_fg: Some(Color::from_hex(0x4b5a51)),
    comment: Some(Color::from_hex(0x8a9a91)),
    keyword: Some(Color::from_hex(0xe27ea6)),
    string: Some(Color::from_hex(0x009b3a)),
    function: Some(Color::from_hex(0x522398)),
    variable: Some(Color::from_hex(0xc60c30)),
    r#type: Some(Color::from_hex(0x968400)),
    constant: Some(Color::from_hex(0xf9461c)),
    operator: Some(Color::from_hex(0x364c40)),
    tag: Some(Color::from_hex(0xc60c30)),
    error: Some(Color::from_hex(0xc60c30)),
    warning: Some(Color::from_hex(0x968400)),
    info: Some(Color::from_hex(0x522398)),
    success: Some(Color::from_hex(0x009b3a)),
    red: Some(Color::from_hex(0xc60c30)),
    orange: Some(Color::from_hex(0xf9461c)),
    yellow: Some(Color::from_hex(0x968400)),
    green: Some(Color::from_hex(0x009b3a)),
    cyan: Some(Color::from_hex(0x00a1de)),
    blue: Some(Color::from_hex(0x522398)),
    purple: Some(Color::from_hex(0xe27ea6)),
    magenta: Some(Color::from_hex(0x62361b)),
};
