//! Dark Violet color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Dark Violet
///
/// Author: ruler501 (https://github.com/ruler501/base16-darkviolet)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Dark Violet"),
    author: Cow::Borrowed("ruler501 (https://github.com/ruler501/base16-darkviolet)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xb08ae6),
    cursor: Some(Color::from_hex(0xb08ae6)),
    selection: Some(Color::from_hex(0x432d59)),
    line_highlight: Some(Color::from_hex(0x231a40)),
    gutter: Some(Color::from_hex(0x593380)),
    statusbar_bg: Some(Color::from_hex(0x231a40)),
    statusbar_fg: Some(Color::from_hex(0x00ff00)),
    comment: Some(Color::from_hex(0x593380)),
    keyword: Some(Color::from_hex(0x7e5ce6)),
    string: Some(Color::from_hex(0x4595e6)),
    function: Some(Color::from_hex(0x4136d9)),
    variable: Some(Color::from_hex(0xa82ee6)),
    r#type: Some(Color::from_hex(0xf29df2)),
    constant: Some(Color::from_hex(0xbb66cc)),
    operator: Some(Color::from_hex(0xb08ae6)),
    tag: Some(Color::from_hex(0xa82ee6)),
    error: Some(Color::from_hex(0xa82ee6)),
    warning: Some(Color::from_hex(0xf29df2)),
    info: Some(Color::from_hex(0x4136d9)),
    success: Some(Color::from_hex(0x4595e6)),
    red: Some(Color::from_hex(0xa82ee6)),
    orange: Some(Color::from_hex(0xbb66cc)),
    yellow: Some(Color::from_hex(0xf29df2)),
    green: Some(Color::from_hex(0x4595e6)),
    cyan: Some(Color::from_hex(0x40dfff)),
    blue: Some(Color::from_hex(0x4136d9)),
    purple: Some(Color::from_hex(0x7e5ce6)),
    magenta: Some(Color::from_hex(0xa886bf)),
};
