//! Darktooth color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Darktooth
///
/// Author: Jason Milkins (https://github.com/jasonm23)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Darktooth",
    author: "Jason Milkins (https://github.com/jasonm23)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1d2021),
    fg: Color::from_hex(0xa89984),
    cursor: Some(Color::from_hex(0xa89984)),
    selection: Some(Color::from_hex(0x504945)),
    line_highlight: Some(Color::from_hex(0x32302f)),
    gutter: Some(Color::from_hex(0x665c54)),
    statusbar_bg: Some(Color::from_hex(0x32302f)),
    statusbar_fg: Some(Color::from_hex(0x928374)),
    comment: Some(Color::from_hex(0x665c54)),
    keyword: Some(Color::from_hex(0x8f4673)),
    string: Some(Color::from_hex(0x95c085)),
    function: Some(Color::from_hex(0x0d6678)),
    variable: Some(Color::from_hex(0xfb543f)),
    r#type: Some(Color::from_hex(0xfac03b)),
    constant: Some(Color::from_hex(0xfe8625)),
    operator: Some(Color::from_hex(0xa89984)),
    tag: Some(Color::from_hex(0xfb543f)),
    error: Some(Color::from_hex(0xfb543f)),
    warning: Some(Color::from_hex(0xfac03b)),
    info: Some(Color::from_hex(0x0d6678)),
    success: Some(Color::from_hex(0x95c085)),
    red: Some(Color::from_hex(0xfb543f)),
    orange: Some(Color::from_hex(0xfe8625)),
    yellow: Some(Color::from_hex(0xfac03b)),
    green: Some(Color::from_hex(0x95c085)),
    cyan: Some(Color::from_hex(0x8ba59b)),
    blue: Some(Color::from_hex(0x0d6678)),
    purple: Some(Color::from_hex(0x8f4673)),
    magenta: Some(Color::from_hex(0xa87322)),
};
