//! Deep Oceanic Next color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Deep Oceanic Next
///
/// Author: spearkkk (https://github.com/spearkkk)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Deep Oceanic Next"),
    author: Cow::Borrowed("spearkkk (https://github.com/spearkkk)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x001c1f),
    fg: Color::from_hex(0xd4e1e8),
    cursor: Some(Color::from_hex(0xd4e1e8)),
    selection: Some(Color::from_hex(0x003640)),
    line_highlight: Some(Color::from_hex(0x002931)),
    gutter: Some(Color::from_hex(0x004852)),
    statusbar_bg: Some(Color::from_hex(0x002931)),
    statusbar_fg: Some(Color::from_hex(0x0093a3)),
    comment: Some(Color::from_hex(0x004852)),
    keyword: Some(Color::from_hex(0x8b66d6)),
    string: Some(Color::from_hex(0x63b784)),
    function: Some(Color::from_hex(0x568ccf)),
    variable: Some(Color::from_hex(0xd3464d)),
    r#type: Some(Color::from_hex(0xf3b863)),
    constant: Some(Color::from_hex(0xe37552)),
    operator: Some(Color::from_hex(0xd4e1e8)),
    tag: Some(Color::from_hex(0xd3464d)),
    error: Some(Color::from_hex(0xd3464d)),
    warning: Some(Color::from_hex(0xf3b863)),
    info: Some(Color::from_hex(0x568ccf)),
    success: Some(Color::from_hex(0x63b784)),
    red: Some(Color::from_hex(0xd3464d)),
    orange: Some(Color::from_hex(0xe37552)),
    yellow: Some(Color::from_hex(0xf3b863)),
    green: Some(Color::from_hex(0x63b784)),
    cyan: Some(Color::from_hex(0x4fb7ae)),
    blue: Some(Color::from_hex(0x568ccf)),
    purple: Some(Color::from_hex(0x8b66d6)),
    magenta: Some(Color::from_hex(0xd0658e)),
};
