//! Digital Rain color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Digital Rain
///
/// Author: Nathan Byrd (https://github.com/cognitivegears)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Digital Rain"),
    author: Cow::Borrowed("Nathan Byrd (https://github.com/cognitivegears)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0x00ff00),
    cursor: Some(Color::from_hex(0x00ff00)),
    selection: Some(Color::from_hex(0x4a8d7e)),
    line_highlight: Some(Color::from_hex(0x4a806c)),
    gutter: Some(Color::from_hex(0x7c8d7c)),
    statusbar_bg: Some(Color::from_hex(0x4a806c)),
    statusbar_fg: Some(Color::from_hex(0x919893)),
    comment: Some(Color::from_hex(0x7c8d7c)),
    keyword: Some(Color::from_hex(0x9472b4)),
    string: Some(Color::from_hex(0x64c83c)),
    function: Some(Color::from_hex(0x5482af)),
    variable: Some(Color::from_hex(0xc85a46)),
    r#type: Some(Color::from_hex(0xa67a50)),
    constant: Some(Color::from_hex(0xc86428)),
    operator: Some(Color::from_hex(0x00ff00)),
    tag: Some(Color::from_hex(0xc85a46)),
    error: Some(Color::from_hex(0xc85a46)),
    warning: Some(Color::from_hex(0xa67a50)),
    info: Some(Color::from_hex(0x5482af)),
    success: Some(Color::from_hex(0x64c83c)),
    red: Some(Color::from_hex(0xc85a46)),
    orange: Some(Color::from_hex(0xc86428)),
    yellow: Some(Color::from_hex(0xa67a50)),
    green: Some(Color::from_hex(0x64c83c)),
    cyan: Some(Color::from_hex(0x468c78)),
    blue: Some(Color::from_hex(0x5482af)),
    purple: Some(Color::from_hex(0x9472b4)),
    magenta: Some(Color::from_hex(0xb37c5e)),
};
