//! Eldritch color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Eldritch
///
/// Author: https://github.com/eldritch-theme
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Eldritch"),
    author: Cow::Borrowed("https://github.com/eldritch-theme"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x212337),
    fg: Color::from_hex(0xebfafa),
    cursor: Some(Color::from_hex(0xebfafa)),
    selection: Some(Color::from_hex(0x3b4261)),
    line_highlight: Some(Color::from_hex(0x323449)),
    gutter: Some(Color::from_hex(0x7081d0)),
    statusbar_bg: Some(Color::from_hex(0x323449)),
    statusbar_fg: Some(Color::from_hex(0xa1abe0)),
    comment: Some(Color::from_hex(0x7081d0)),
    keyword: Some(Color::from_hex(0xa48cf2)),
    string: Some(Color::from_hex(0x37f499)),
    function: Some(Color::from_hex(0x39ddfd)),
    variable: Some(Color::from_hex(0xf16c75)),
    r#type: Some(Color::from_hex(0xf1fc79)),
    constant: Some(Color::from_hex(0xf7c67f)),
    operator: Some(Color::from_hex(0xebfafa)),
    tag: Some(Color::from_hex(0xf16c75)),
    error: Some(Color::from_hex(0xf16c75)),
    warning: Some(Color::from_hex(0xf1fc79)),
    info: Some(Color::from_hex(0x39ddfd)),
    success: Some(Color::from_hex(0x37f499)),
    red: Some(Color::from_hex(0xf16c75)),
    orange: Some(Color::from_hex(0xf7c67f)),
    yellow: Some(Color::from_hex(0xf1fc79)),
    green: Some(Color::from_hex(0x37f499)),
    cyan: Some(Color::from_hex(0x04d1f9)),
    blue: Some(Color::from_hex(0x39ddfd)),
    purple: Some(Color::from_hex(0xa48cf2)),
    magenta: Some(Color::from_hex(0xf265b5)),
};
