//! Embers Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Embers Light
///
/// Author: Jannik Siebert (https://github.com/janniks)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Embers Light"),
    author: Cow::Borrowed("Jannik Siebert (https://github.com/janniks)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xd1d6db),
    fg: Color::from_hex(0x323b43),
    cursor: Some(Color::from_hex(0x323b43)),
    selection: Some(Color::from_hex(0x909aa3)),
    line_highlight: Some(Color::from_hex(0xaeb6be)),
    gutter: Some(Color::from_hex(0x75808a)),
    statusbar_bg: Some(Color::from_hex(0xaeb6be)),
    statusbar_fg: Some(Color::from_hex(0x47505a)),
    comment: Some(Color::from_hex(0x75808a)),
    keyword: Some(Color::from_hex(0x6d5782)),
    string: Some(Color::from_hex(0x6d8257)),
    function: Some(Color::from_hex(0x82576d)),
    variable: Some(Color::from_hex(0x576d82)),
    r#type: Some(Color::from_hex(0x57826d)),
    constant: Some(Color::from_hex(0x578282)),
    operator: Some(Color::from_hex(0x323b43)),
    tag: Some(Color::from_hex(0x576d82)),
    error: Some(Color::from_hex(0x576d82)),
    warning: Some(Color::from_hex(0x57826d)),
    info: Some(Color::from_hex(0x82576d)),
    success: Some(Color::from_hex(0x6d8257)),
    red: Some(Color::from_hex(0x576d82)),
    orange: Some(Color::from_hex(0x578282)),
    yellow: Some(Color::from_hex(0x57826d)),
    green: Some(Color::from_hex(0x6d8257)),
    cyan: Some(Color::from_hex(0x826d57)),
    blue: Some(Color::from_hex(0x82576d)),
    purple: Some(Color::from_hex(0x6d5782)),
    magenta: Some(Color::from_hex(0x575782)),
};
