//! Espresso color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Espresso
///
/// Author: Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Espresso",
    author: "Unknown. Maintained by Alex Mirrington (https://github.com/alexmirrington)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2d2d2d),
    fg: Color::from_hex(0xcccccc),
    cursor: Some(Color::from_hex(0xcccccc)),
    selection: Some(Color::from_hex(0x515151)),
    line_highlight: Some(Color::from_hex(0x393939)),
    gutter: Some(Color::from_hex(0x777777)),
    statusbar_bg: Some(Color::from_hex(0x393939)),
    statusbar_fg: Some(Color::from_hex(0xb4b7b4)),
    comment: Some(Color::from_hex(0x777777)),
    keyword: Some(Color::from_hex(0xd197d9)),
    string: Some(Color::from_hex(0xa5c261)),
    function: Some(Color::from_hex(0x6c99bb)),
    variable: Some(Color::from_hex(0xd25252)),
    r#type: Some(Color::from_hex(0xffc66d)),
    constant: Some(Color::from_hex(0xf9a959)),
    operator: Some(Color::from_hex(0xcccccc)),
    tag: Some(Color::from_hex(0xd25252)),
    error: Some(Color::from_hex(0xd25252)),
    warning: Some(Color::from_hex(0xffc66d)),
    info: Some(Color::from_hex(0x6c99bb)),
    success: Some(Color::from_hex(0xa5c261)),
    red: Some(Color::from_hex(0xd25252)),
    orange: Some(Color::from_hex(0xf9a959)),
    yellow: Some(Color::from_hex(0xffc66d)),
    green: Some(Color::from_hex(0xa5c261)),
    cyan: Some(Color::from_hex(0xbed6ff)),
    blue: Some(Color::from_hex(0x6c99bb)),
    purple: Some(Color::from_hex(0xd197d9)),
    magenta: Some(Color::from_hex(0xf97394)),
};
