//! Evenok Dark color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Evenok Dark
///
/// Author: Mekeor Melire
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Evenok Dark",
    author: "Mekeor Melire",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xd0d0d0)),
    selection: Some(Color::from_hex(0x303030)),
    line_highlight: Some(Color::from_hex(0x202020)),
    gutter: Some(Color::from_hex(0x505050)),
    statusbar_bg: Some(Color::from_hex(0x202020)),
    statusbar_fg: Some(Color::from_hex(0xb0b0b0)),
    comment: Some(Color::from_hex(0x505050)),
    keyword: Some(Color::from_hex(0x9095ff)),
    string: Some(Color::from_hex(0x54bc5c)),
    function: Some(Color::from_hex(0x00aff2)),
    variable: Some(Color::from_hex(0xf5708a)),
    r#type: Some(Color::from_hex(0xb8a300)),
    constant: Some(Color::from_hex(0xee8122)),
    operator: Some(Color::from_hex(0xd0d0d0)),
    tag: Some(Color::from_hex(0xf5708a)),
    error: Some(Color::from_hex(0xf5708a)),
    warning: Some(Color::from_hex(0xb8a300)),
    info: Some(Color::from_hex(0x00aff2)),
    success: Some(Color::from_hex(0x54bc5c)),
    red: Some(Color::from_hex(0xf5708a)),
    orange: Some(Color::from_hex(0xee8122)),
    yellow: Some(Color::from_hex(0xb8a300)),
    green: Some(Color::from_hex(0x54bc5c)),
    cyan: Some(Color::from_hex(0x00bab3)),
    blue: Some(Color::from_hex(0x00aff2)),
    purple: Some(Color::from_hex(0x9095ff)),
    magenta: Some(Color::from_hex(0xd47ada)),
};
