//! Github color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Github
///
/// Author: Tinted Theming (https://github.com/tinted-theming)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Github"),
    author: Cow::Borrowed("Tinted Theming (https://github.com/tinted-theming)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xeaeef2),
    fg: Color::from_hex(0x424a53),
    cursor: Some(Color::from_hex(0x424a53)),
    selection: Some(Color::from_hex(0xafb8c1)),
    line_highlight: Some(Color::from_hex(0xd0d7de)),
    gutter: Some(Color::from_hex(0x8c959f)),
    statusbar_bg: Some(Color::from_hex(0xd0d7de)),
    statusbar_fg: Some(Color::from_hex(0x6e7781)),
    comment: Some(Color::from_hex(0x8c959f)),
    keyword: Some(Color::from_hex(0xa475f9)),
    string: Some(Color::from_hex(0x2da44e)),
    function: Some(Color::from_hex(0x218bff)),
    variable: Some(Color::from_hex(0xfa4549)),
    r#type: Some(Color::from_hex(0xbf8700)),
    constant: Some(Color::from_hex(0xe16f24)),
    operator: Some(Color::from_hex(0x424a53)),
    tag: Some(Color::from_hex(0xfa4549)),
    error: Some(Color::from_hex(0xfa4549)),
    warning: Some(Color::from_hex(0xbf8700)),
    info: Some(Color::from_hex(0x218bff)),
    success: Some(Color::from_hex(0x2da44e)),
    red: Some(Color::from_hex(0xfa4549)),
    orange: Some(Color::from_hex(0xe16f24)),
    yellow: Some(Color::from_hex(0xbf8700)),
    green: Some(Color::from_hex(0x2da44e)),
    cyan: Some(Color::from_hex(0x339d9b)),
    blue: Some(Color::from_hex(0x218bff)),
    purple: Some(Color::from_hex(0xa475f9)),
    magenta: Some(Color::from_hex(0x4d2d00)),
};
