//! Grayscale Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Grayscale Light
///
/// Author: Alexandre Gavioli (https://github.com/Alexx2/)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Grayscale Light"),
    author: Cow::Borrowed("Alexandre Gavioli (https://github.com/Alexx2/)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf7f7f7),
    fg: Color::from_hex(0x464646),
    cursor: Some(Color::from_hex(0x464646)),
    selection: Some(Color::from_hex(0xb9b9b9)),
    line_highlight: Some(Color::from_hex(0xe3e3e3)),
    gutter: Some(Color::from_hex(0xababab)),
    statusbar_bg: Some(Color::from_hex(0xe3e3e3)),
    statusbar_fg: Some(Color::from_hex(0x525252)),
    comment: Some(Color::from_hex(0xababab)),
    keyword: Some(Color::from_hex(0x747474)),
    string: Some(Color::from_hex(0x8e8e8e)),
    function: Some(Color::from_hex(0x686868)),
    variable: Some(Color::from_hex(0x7c7c7c)),
    r#type: Some(Color::from_hex(0xa0a0a0)),
    constant: Some(Color::from_hex(0x999999)),
    operator: Some(Color::from_hex(0x464646)),
    tag: Some(Color::from_hex(0x7c7c7c)),
    error: Some(Color::from_hex(0x7c7c7c)),
    warning: Some(Color::from_hex(0xa0a0a0)),
    info: Some(Color::from_hex(0x686868)),
    success: Some(Color::from_hex(0x8e8e8e)),
    red: Some(Color::from_hex(0x7c7c7c)),
    orange: Some(Color::from_hex(0x999999)),
    yellow: Some(Color::from_hex(0xa0a0a0)),
    green: Some(Color::from_hex(0x8e8e8e)),
    cyan: Some(Color::from_hex(0x868686)),
    blue: Some(Color::from_hex(0x686868)),
    purple: Some(Color::from_hex(0x747474)),
    magenta: Some(Color::from_hex(0x5e5e5e)),
};
