//! Green Screen color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Green Screen
///
/// Author: Chris Kempson (http://chriskempson.com)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Green Screen",
    author: "Chris Kempson (http://chriskempson.com)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x001100),
    fg: Color::from_hex(0x00bb00),
    cursor: Some(Color::from_hex(0x00bb00)),
    selection: Some(Color::from_hex(0x005500)),
    line_highlight: Some(Color::from_hex(0x003300)),
    gutter: Some(Color::from_hex(0x007700)),
    statusbar_bg: Some(Color::from_hex(0x003300)),
    statusbar_fg: Some(Color::from_hex(0x009900)),
    comment: Some(Color::from_hex(0x007700)),
    keyword: Some(Color::from_hex(0x00bb00)),
    string: Some(Color::from_hex(0x00bb00)),
    function: Some(Color::from_hex(0x009900)),
    variable: Some(Color::from_hex(0x007700)),
    r#type: Some(Color::from_hex(0x007700)),
    constant: Some(Color::from_hex(0x009900)),
    operator: Some(Color::from_hex(0x00bb00)),
    tag: Some(Color::from_hex(0x007700)),
    error: Some(Color::from_hex(0x007700)),
    warning: Some(Color::from_hex(0x007700)),
    info: Some(Color::from_hex(0x009900)),
    success: Some(Color::from_hex(0x00bb00)),
    red: Some(Color::from_hex(0x007700)),
    orange: Some(Color::from_hex(0x009900)),
    yellow: Some(Color::from_hex(0x007700)),
    green: Some(Color::from_hex(0x00bb00)),
    cyan: Some(Color::from_hex(0x005500)),
    blue: Some(Color::from_hex(0x009900)),
    purple: Some(Color::from_hex(0x00bb00)),
    magenta: Some(Color::from_hex(0x005500)),
};
