//! Gruber color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Gruber
///
/// Author: Patel, Nimai <nimai.m.patel@gmail.com>, colors from www.github.com/rexim/gruber-darker-theme
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Gruber"),
    author: Cow::Borrowed(
        "Patel, Nimai <nimai.m.patel@gmail.com>, colors from www.github.com/rexim/gruber-darker-theme",
    ),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x181818),
    fg: Color::from_hex(0xf4f4ff),
    cursor: Some(Color::from_hex(0xf4f4ff)),
    selection: Some(Color::from_hex(0x484848)),
    line_highlight: Some(Color::from_hex(0x453d41)),
    gutter: Some(Color::from_hex(0x52494e)),
    statusbar_bg: Some(Color::from_hex(0x453d41)),
    statusbar_fg: Some(Color::from_hex(0xe4e4ef)),
    comment: Some(Color::from_hex(0x52494e)),
    keyword: Some(Color::from_hex(0x9e95c7)),
    string: Some(Color::from_hex(0x73c936)),
    function: Some(Color::from_hex(0x96a6c8)),
    variable: Some(Color::from_hex(0xf43841)),
    r#type: Some(Color::from_hex(0xffdd33)),
    constant: Some(Color::from_hex(0xc73c3f)),
    operator: Some(Color::from_hex(0xf4f4ff)),
    tag: Some(Color::from_hex(0xf43841)),
    error: Some(Color::from_hex(0xf43841)),
    warning: Some(Color::from_hex(0xffdd33)),
    info: Some(Color::from_hex(0x96a6c8)),
    success: Some(Color::from_hex(0x73c936)),
    red: Some(Color::from_hex(0xf43841)),
    orange: Some(Color::from_hex(0xc73c3f)),
    yellow: Some(Color::from_hex(0xffdd33)),
    green: Some(Color::from_hex(0x73c936)),
    cyan: Some(Color::from_hex(0x95a99f)),
    blue: Some(Color::from_hex(0x96a6c8)),
    purple: Some(Color::from_hex(0x9e95c7)),
    magenta: Some(Color::from_hex(0xcc8c3c)),
};
