//! Gruvbox Material Dark, Medium color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Gruvbox Material Dark, Medium
///
/// Author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Gruvbox Material Dark, Medium"),
    author: Cow::Borrowed(
        "Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)",
    ),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x292828),
    fg: Color::from_hex(0xddc7a1),
    cursor: Some(Color::from_hex(0xddc7a1)),
    selection: Some(Color::from_hex(0x504945)),
    line_highlight: Some(Color::from_hex(0x32302f)),
    gutter: Some(Color::from_hex(0x665c54)),
    statusbar_bg: Some(Color::from_hex(0x32302f)),
    statusbar_fg: Some(Color::from_hex(0xbdae93)),
    comment: Some(Color::from_hex(0x665c54)),
    keyword: Some(Color::from_hex(0xd3869b)),
    string: Some(Color::from_hex(0xa9b665)),
    function: Some(Color::from_hex(0x7daea3)),
    variable: Some(Color::from_hex(0xea6962)),
    r#type: Some(Color::from_hex(0xd8a657)),
    constant: Some(Color::from_hex(0xe78a4e)),
    operator: Some(Color::from_hex(0xddc7a1)),
    tag: Some(Color::from_hex(0xea6962)),
    error: Some(Color::from_hex(0xea6962)),
    warning: Some(Color::from_hex(0xd8a657)),
    info: Some(Color::from_hex(0x7daea3)),
    success: Some(Color::from_hex(0xa9b665)),
    red: Some(Color::from_hex(0xea6962)),
    orange: Some(Color::from_hex(0xe78a4e)),
    yellow: Some(Color::from_hex(0xd8a657)),
    green: Some(Color::from_hex(0xa9b665)),
    cyan: Some(Color::from_hex(0x89b482)),
    blue: Some(Color::from_hex(0x7daea3)),
    purple: Some(Color::from_hex(0xd3869b)),
    magenta: Some(Color::from_hex(0xbd6f3e)),
};
