//! Gruvbox Material Light, Soft color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Gruvbox Material Light, Soft
///
/// Author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Gruvbox Material Light, Soft",
    author: "Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf2e5bc),
    fg: Color::from_hex(0x654735),
    cursor: Some(Color::from_hex(0x654735)),
    selection: Some(Color::from_hex(0xc9b99a)),
    line_highlight: Some(Color::from_hex(0xebdbb2)),
    gutter: Some(Color::from_hex(0xa89984)),
    statusbar_bg: Some(Color::from_hex(0xebdbb2)),
    statusbar_fg: Some(Color::from_hex(0x665c54)),
    comment: Some(Color::from_hex(0xa89984)),
    keyword: Some(Color::from_hex(0x945e80)),
    string: Some(Color::from_hex(0x6c782e)),
    function: Some(Color::from_hex(0x45707a)),
    variable: Some(Color::from_hex(0xc14a4a)),
    r#type: Some(Color::from_hex(0xb47109)),
    constant: Some(Color::from_hex(0xc35e0a)),
    operator: Some(Color::from_hex(0x654735)),
    tag: Some(Color::from_hex(0xc14a4a)),
    error: Some(Color::from_hex(0xc14a4a)),
    warning: Some(Color::from_hex(0xb47109)),
    info: Some(Color::from_hex(0x45707a)),
    success: Some(Color::from_hex(0x6c782e)),
    red: Some(Color::from_hex(0xc14a4a)),
    orange: Some(Color::from_hex(0xc35e0a)),
    yellow: Some(Color::from_hex(0xb47109)),
    green: Some(Color::from_hex(0x6c782e)),
    cyan: Some(Color::from_hex(0x4c7a5d)),
    blue: Some(Color::from_hex(0x45707a)),
    purple: Some(Color::from_hex(0x945e80)),
    magenta: Some(Color::from_hex(0xe78a4e)),
};
