//! Horizon Terminal Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Horizon Terminal Light
///
/// Author: Michaël Ball (http://github.com/michael-ball/)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Horizon Terminal Light"),
    author: Cow::Borrowed("Michaël Ball (http://github.com/michael-ball/)"),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xfdf0ed),
    fg: Color::from_hex(0x403c3d),
    cursor: Some(Color::from_hex(0x403c3d)),
    selection: Some(Color::from_hex(0xf9cbbe)),
    line_highlight: Some(Color::from_hex(0xfadad1)),
    gutter: Some(Color::from_hex(0xbdb3b1)),
    statusbar_bg: Some(Color::from_hex(0xfadad1)),
    statusbar_fg: Some(Color::from_hex(0x948c8a)),
    comment: Some(Color::from_hex(0xbdb3b1)),
    keyword: Some(Color::from_hex(0xee64ac)),
    string: Some(Color::from_hex(0x29d398)),
    function: Some(Color::from_hex(0x26bbd9)),
    variable: Some(Color::from_hex(0xe95678)),
    r#type: Some(Color::from_hex(0xfadad1)),
    constant: Some(Color::from_hex(0xf9cec3)),
    operator: Some(Color::from_hex(0x403c3d)),
    tag: Some(Color::from_hex(0xe95678)),
    error: Some(Color::from_hex(0xe95678)),
    warning: Some(Color::from_hex(0xfadad1)),
    info: Some(Color::from_hex(0x26bbd9)),
    success: Some(Color::from_hex(0x29d398)),
    red: Some(Color::from_hex(0xe95678)),
    orange: Some(Color::from_hex(0xf9cec3)),
    yellow: Some(Color::from_hex(0xfadad1)),
    green: Some(Color::from_hex(0x29d398)),
    cyan: Some(Color::from_hex(0x59e1e3)),
    blue: Some(Color::from_hex(0x26bbd9)),
    purple: Some(Color::from_hex(0xee64ac)),
    magenta: Some(Color::from_hex(0xf9cbbe)),
};
