//! Horizon Light color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Horizon Light
///
/// Author: Michaël Ball (http://github.com/michael-ball/)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Horizon Light",
    author: "Michaël Ball (http://github.com/michael-ball/)",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xfdf0ed),
    fg: Color::from_hex(0x403c3d),
    cursor: Some(Color::from_hex(0x403c3d)),
    selection: Some(Color::from_hex(0xf9cbbe)),
    line_highlight: Some(Color::from_hex(0xfadad1)),
    gutter: Some(Color::from_hex(0xbdb3b1)),
    statusbar_bg: Some(Color::from_hex(0xfadad1)),
    statusbar_fg: Some(Color::from_hex(0x948c8a)),
    comment: Some(Color::from_hex(0xbdb3b1)),
    keyword: Some(Color::from_hex(0x1d8991)),
    string: Some(Color::from_hex(0x94e1b0)),
    function: Some(Color::from_hex(0xda103f)),
    variable: Some(Color::from_hex(0xf7939b)),
    r#type: Some(Color::from_hex(0xfbe0d9)),
    constant: Some(Color::from_hex(0xf6661e)),
    operator: Some(Color::from_hex(0x403c3d)),
    tag: Some(Color::from_hex(0xf7939b)),
    error: Some(Color::from_hex(0xf7939b)),
    warning: Some(Color::from_hex(0xfbe0d9)),
    info: Some(Color::from_hex(0xda103f)),
    success: Some(Color::from_hex(0x94e1b0)),
    red: Some(Color::from_hex(0xf7939b)),
    orange: Some(Color::from_hex(0xf6661e)),
    yellow: Some(Color::from_hex(0xfbe0d9)),
    green: Some(Color::from_hex(0x94e1b0)),
    cyan: Some(Color::from_hex(0xdc3318)),
    blue: Some(Color::from_hex(0xda103f)),
    purple: Some(Color::from_hex(0x1d8991)),
    magenta: Some(Color::from_hex(0xe58c92)),
};
