//! Humanoid dark color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Humanoid dark
///
/// Author: Thomas (tasmo) Friese
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Humanoid dark"),
    author: Cow::Borrowed("Thomas (tasmo) Friese"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x232629),
    fg: Color::from_hex(0xf8f8f2),
    cursor: Some(Color::from_hex(0xf8f8f2)),
    selection: Some(Color::from_hex(0x484e54)),
    line_highlight: Some(Color::from_hex(0x333b3d)),
    gutter: Some(Color::from_hex(0x60615d)),
    statusbar_bg: Some(Color::from_hex(0x333b3d)),
    statusbar_fg: Some(Color::from_hex(0xc0c0bd)),
    comment: Some(Color::from_hex(0x60615d)),
    keyword: Some(Color::from_hex(0xf15ee3)),
    string: Some(Color::from_hex(0x02d849)),
    function: Some(Color::from_hex(0x00a6fb)),
    variable: Some(Color::from_hex(0xf11235)),
    r#type: Some(Color::from_hex(0xffb627)),
    constant: Some(Color::from_hex(0xff9505)),
    operator: Some(Color::from_hex(0xf8f8f2)),
    tag: Some(Color::from_hex(0xf11235)),
    error: Some(Color::from_hex(0xf11235)),
    warning: Some(Color::from_hex(0xffb627)),
    info: Some(Color::from_hex(0x00a6fb)),
    success: Some(Color::from_hex(0x02d849)),
    red: Some(Color::from_hex(0xf11235)),
    orange: Some(Color::from_hex(0xff9505)),
    yellow: Some(Color::from_hex(0xffb627)),
    green: Some(Color::from_hex(0x02d849)),
    cyan: Some(Color::from_hex(0x0dd9d6)),
    blue: Some(Color::from_hex(0x00a6fb)),
    purple: Some(Color::from_hex(0xf15ee3)),
    magenta: Some(Color::from_hex(0xb27701)),
};
