//! iA Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// iA Light
///
/// Author: iA Inc. (modified by aramisgithub)
/// Variant: Light
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "iA Light",
    author: "iA Inc. (modified by aramisgithub)",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xf6f6f6),
    fg: Color::from_hex(0x181818),
    cursor: Some(Color::from_hex(0x181818)),
    selection: Some(Color::from_hex(0xbde5f2)),
    line_highlight: Some(Color::from_hex(0xdedede)),
    gutter: Some(Color::from_hex(0x898989)),
    statusbar_bg: Some(Color::from_hex(0xdedede)),
    statusbar_fg: Some(Color::from_hex(0x767676)),
    comment: Some(Color::from_hex(0x898989)),
    keyword: Some(Color::from_hex(0xa94598)),
    string: Some(Color::from_hex(0x38781c)),
    function: Some(Color::from_hex(0x48bac2)),
    variable: Some(Color::from_hex(0x9c5a02)),
    r#type: Some(Color::from_hex(0xc48218)),
    constant: Some(Color::from_hex(0xc43e18)),
    operator: Some(Color::from_hex(0x181818)),
    tag: Some(Color::from_hex(0x9c5a02)),
    error: Some(Color::from_hex(0x9c5a02)),
    warning: Some(Color::from_hex(0xc48218)),
    info: Some(Color::from_hex(0x48bac2)),
    success: Some(Color::from_hex(0x38781c)),
    red: Some(Color::from_hex(0x9c5a02)),
    orange: Some(Color::from_hex(0xc43e18)),
    yellow: Some(Color::from_hex(0xc48218)),
    green: Some(Color::from_hex(0x38781c)),
    cyan: Some(Color::from_hex(0x2d6bb1)),
    blue: Some(Color::from_hex(0x48bac2)),
    purple: Some(Color::from_hex(0xa94598)),
    magenta: Some(Color::from_hex(0x8b6c37)),
};
