//! Isotope color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Isotope
///
/// Author: Jan T. Sott
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Isotope",
    author: "Jan T. Sott",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xd0d0d0)),
    selection: Some(Color::from_hex(0x606060)),
    line_highlight: Some(Color::from_hex(0x404040)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0x404040)),
    statusbar_fg: Some(Color::from_hex(0xc0c0c0)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0xcc00ff)),
    string: Some(Color::from_hex(0x33ff00)),
    function: Some(Color::from_hex(0x0066ff)),
    variable: Some(Color::from_hex(0xff0000)),
    r#type: Some(Color::from_hex(0xff0099)),
    constant: Some(Color::from_hex(0xff9900)),
    operator: Some(Color::from_hex(0xd0d0d0)),
    tag: Some(Color::from_hex(0xff0000)),
    error: Some(Color::from_hex(0xff0000)),
    warning: Some(Color::from_hex(0xff0099)),
    info: Some(Color::from_hex(0x0066ff)),
    success: Some(Color::from_hex(0x33ff00)),
    red: Some(Color::from_hex(0xff0000)),
    orange: Some(Color::from_hex(0xff9900)),
    yellow: Some(Color::from_hex(0xff0099)),
    green: Some(Color::from_hex(0x33ff00)),
    cyan: Some(Color::from_hex(0x00ffff)),
    blue: Some(Color::from_hex(0x0066ff)),
    purple: Some(Color::from_hex(0xcc00ff)),
    magenta: Some(Color::from_hex(0x3300ff)),
};
