//! Kimber color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Kimber
///
/// Author: Mishka Nguyen (https://github.com/akhsiM)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Kimber"),
    author: Cow::Borrowed("Mishka Nguyen (https://github.com/akhsiM)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x222222),
    fg: Color::from_hex(0xdedee7),
    cursor: Some(Color::from_hex(0xdedee7)),
    selection: Some(Color::from_hex(0x555d55)),
    line_highlight: Some(Color::from_hex(0x313131)),
    gutter: Some(Color::from_hex(0x644646)),
    statusbar_bg: Some(Color::from_hex(0x313131)),
    statusbar_fg: Some(Color::from_hex(0x5a5a5a)),
    comment: Some(Color::from_hex(0x644646)),
    keyword: Some(Color::from_hex(0x86cacd)),
    string: Some(Color::from_hex(0x99c899)),
    function: Some(Color::from_hex(0x537c9c)),
    variable: Some(Color::from_hex(0xc88c8c)),
    r#type: Some(Color::from_hex(0xd8b56d)),
    constant: Some(Color::from_hex(0x476c88)),
    operator: Some(Color::from_hex(0xdedee7)),
    tag: Some(Color::from_hex(0xc88c8c)),
    error: Some(Color::from_hex(0xc88c8c)),
    warning: Some(Color::from_hex(0xd8b56d)),
    info: Some(Color::from_hex(0x537c9c)),
    success: Some(Color::from_hex(0x99c899)),
    red: Some(Color::from_hex(0xc88c8c)),
    orange: Some(Color::from_hex(0x476c88)),
    yellow: Some(Color::from_hex(0xd8b56d)),
    green: Some(Color::from_hex(0x99c899)),
    cyan: Some(Color::from_hex(0x78b4b4)),
    blue: Some(Color::from_hex(0x537c9c)),
    purple: Some(Color::from_hex(0x86cacd)),
    magenta: Some(Color::from_hex(0x704f4f)),
};
