//! Macintosh color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Macintosh
///
/// Author: Rebecca Bettencourt (http://www.kreativekorp.com)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Macintosh"),
    author: Cow::Borrowed("Rebecca Bettencourt (http://www.kreativekorp.com)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0xc0c0c0)),
    selection: Some(Color::from_hex(0x404040)),
    line_highlight: Some(Color::from_hex(0x404040)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0x404040)),
    statusbar_fg: Some(Color::from_hex(0x808080)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0x4700a5)),
    string: Some(Color::from_hex(0x1fb714)),
    function: Some(Color::from_hex(0x0000d3)),
    variable: Some(Color::from_hex(0xdd0907)),
    r#type: Some(Color::from_hex(0xfbf305)),
    constant: Some(Color::from_hex(0xff6403)),
    operator: Some(Color::from_hex(0xc0c0c0)),
    tag: Some(Color::from_hex(0xdd0907)),
    error: Some(Color::from_hex(0xdd0907)),
    warning: Some(Color::from_hex(0xfbf305)),
    info: Some(Color::from_hex(0x0000d3)),
    success: Some(Color::from_hex(0x1fb714)),
    red: Some(Color::from_hex(0xdd0907)),
    orange: Some(Color::from_hex(0xff6403)),
    yellow: Some(Color::from_hex(0xfbf305)),
    green: Some(Color::from_hex(0x1fb714)),
    cyan: Some(Color::from_hex(0x02abea)),
    blue: Some(Color::from_hex(0x0000d3)),
    purple: Some(Color::from_hex(0x4700a5)),
    magenta: Some(Color::from_hex(0x90713a)),
};
