//! Marrakesh color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Marrakesh
///
/// Author: Alexandre Gavioli (http://github.com/Alexx2/)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Marrakesh",
    author: "Alexandre Gavioli (http://github.com/Alexx2/)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x201602),
    fg: Color::from_hex(0x948e48),
    cursor: Some(Color::from_hex(0x948e48)),
    selection: Some(Color::from_hex(0x5f5b17)),
    line_highlight: Some(Color::from_hex(0x302e00)),
    gutter: Some(Color::from_hex(0x6c6823)),
    statusbar_bg: Some(Color::from_hex(0x302e00)),
    statusbar_fg: Some(Color::from_hex(0x86813b)),
    comment: Some(Color::from_hex(0x6c6823)),
    keyword: Some(Color::from_hex(0x8868b3)),
    string: Some(Color::from_hex(0x18974e)),
    function: Some(Color::from_hex(0x477ca1)),
    variable: Some(Color::from_hex(0xc35359)),
    r#type: Some(Color::from_hex(0xa88339)),
    constant: Some(Color::from_hex(0xb36144)),
    operator: Some(Color::from_hex(0x948e48)),
    tag: Some(Color::from_hex(0xc35359)),
    error: Some(Color::from_hex(0xc35359)),
    warning: Some(Color::from_hex(0xa88339)),
    info: Some(Color::from_hex(0x477ca1)),
    success: Some(Color::from_hex(0x18974e)),
    red: Some(Color::from_hex(0xc35359)),
    orange: Some(Color::from_hex(0xb36144)),
    yellow: Some(Color::from_hex(0xa88339)),
    green: Some(Color::from_hex(0x18974e)),
    cyan: Some(Color::from_hex(0x75a738)),
    blue: Some(Color::from_hex(0x477ca1)),
    purple: Some(Color::from_hex(0x8868b3)),
    magenta: Some(Color::from_hex(0xb3588e)),
};
