//! Material Vivid color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Material Vivid
///
/// Author: joshyrobot
/// Variant: Dark
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Material Vivid"),
    author: Cow::Borrowed("joshyrobot"),
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x202124),
    fg: Color::from_hex(0x80868b),
    cursor: Some(Color::from_hex(0x80868b)),
    selection: Some(Color::from_hex(0x323639)),
    line_highlight: Some(Color::from_hex(0x27292c)),
    gutter: Some(Color::from_hex(0x44464d)),
    statusbar_bg: Some(Color::from_hex(0x27292c)),
    statusbar_fg: Some(Color::from_hex(0x676c71)),
    comment: Some(Color::from_hex(0x44464d)),
    keyword: Some(Color::from_hex(0x673ab7)),
    string: Some(Color::from_hex(0x00e676)),
    function: Some(Color::from_hex(0x2196f3)),
    variable: Some(Color::from_hex(0xf44336)),
    r#type: Some(Color::from_hex(0xffeb3b)),
    constant: Some(Color::from_hex(0xff9800)),
    operator: Some(Color::from_hex(0x80868b)),
    tag: Some(Color::from_hex(0xf44336)),
    error: Some(Color::from_hex(0xf44336)),
    warning: Some(Color::from_hex(0xffeb3b)),
    info: Some(Color::from_hex(0x2196f3)),
    success: Some(Color::from_hex(0x00e676)),
    red: Some(Color::from_hex(0xf44336)),
    orange: Some(Color::from_hex(0xff9800)),
    yellow: Some(Color::from_hex(0xffeb3b)),
    green: Some(Color::from_hex(0x00e676)),
    cyan: Some(Color::from_hex(0x00bcd4)),
    blue: Some(Color::from_hex(0x2196f3)),
    purple: Some(Color::from_hex(0x673ab7)),
    magenta: Some(Color::from_hex(0x8d6e63)),
};
