//! Material Palenight color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Material Palenight
///
/// Author: Nate Peterson
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Material Palenight",
    author: "Nate Peterson",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x292d3e),
    fg: Color::from_hex(0x959dcb),
    cursor: Some(Color::from_hex(0x959dcb)),
    selection: Some(Color::from_hex(0x32374d)),
    line_highlight: Some(Color::from_hex(0x444267)),
    gutter: Some(Color::from_hex(0x676e95)),
    statusbar_bg: Some(Color::from_hex(0x444267)),
    statusbar_fg: Some(Color::from_hex(0x8796b0)),
    comment: Some(Color::from_hex(0x676e95)),
    keyword: Some(Color::from_hex(0xc792ea)),
    string: Some(Color::from_hex(0xc3e88d)),
    function: Some(Color::from_hex(0x82aaff)),
    variable: Some(Color::from_hex(0xf07178)),
    r#type: Some(Color::from_hex(0xffcb6b)),
    constant: Some(Color::from_hex(0xf78c6c)),
    operator: Some(Color::from_hex(0x959dcb)),
    tag: Some(Color::from_hex(0xf07178)),
    error: Some(Color::from_hex(0xf07178)),
    warning: Some(Color::from_hex(0xffcb6b)),
    info: Some(Color::from_hex(0x82aaff)),
    success: Some(Color::from_hex(0xc3e88d)),
    red: Some(Color::from_hex(0xf07178)),
    orange: Some(Color::from_hex(0xf78c6c)),
    yellow: Some(Color::from_hex(0xffcb6b)),
    green: Some(Color::from_hex(0xc3e88d)),
    cyan: Some(Color::from_hex(0x89ddff)),
    blue: Some(Color::from_hex(0x82aaff)),
    purple: Some(Color::from_hex(0xc792ea)),
    magenta: Some(Color::from_hex(0xff5370)),
};
