//! Measured Dark color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Measured Dark
///
/// Author: Measured (https://measured.co)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Measured Dark"),
    author: Cow::Borrowed("Measured (https://measured.co)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x00211f),
    fg: Color::from_hex(0xdcdcdc),
    cursor: Some(Color::from_hex(0xdcdcdc)),
    selection: Some(Color::from_hex(0x005453)),
    line_highlight: Some(Color::from_hex(0x003a38)),
    gutter: Some(Color::from_hex(0xababab)),
    statusbar_bg: Some(Color::from_hex(0x003a38)),
    statusbar_fg: Some(Color::from_hex(0xc3c3c3)),
    comment: Some(Color::from_hex(0xababab)),
    keyword: Some(Color::from_hex(0xb39be0)),
    string: Some(Color::from_hex(0x56c16f)),
    function: Some(Color::from_hex(0x88b0da)),
    variable: Some(Color::from_hex(0xce7e8e)),
    r#type: Some(Color::from_hex(0xbfac4e)),
    constant: Some(Color::from_hex(0xdca37c)),
    operator: Some(Color::from_hex(0xdcdcdc)),
    tag: Some(Color::from_hex(0xce7e8e)),
    error: Some(Color::from_hex(0xce7e8e)),
    warning: Some(Color::from_hex(0xbfac4e)),
    info: Some(Color::from_hex(0x88b0da)),
    success: Some(Color::from_hex(0x56c16f)),
    red: Some(Color::from_hex(0xce7e8e)),
    orange: Some(Color::from_hex(0xdca37c)),
    yellow: Some(Color::from_hex(0xbfac4e)),
    green: Some(Color::from_hex(0x56c16f)),
    cyan: Some(Color::from_hex(0x62c0be)),
    blue: Some(Color::from_hex(0x88b0da)),
    purple: Some(Color::from_hex(0xb39be0)),
    magenta: Some(Color::from_hex(0xd89aba)),
};
