//! Mellow Purple color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Mellow Purple
///
/// Author: gidsi
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Mellow Purple",
    author: "gidsi",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1e0528),
    fg: Color::from_hex(0xffeeff),
    cursor: Some(Color::from_hex(0xffeeff)),
    selection: Some(Color::from_hex(0x331354)),
    line_highlight: Some(Color::from_hex(0x1a092d)),
    gutter: Some(Color::from_hex(0x320f55)),
    statusbar_bg: Some(Color::from_hex(0x1a092d)),
    statusbar_fg: Some(Color::from_hex(0x873582)),
    comment: Some(Color::from_hex(0x320f55)),
    keyword: Some(Color::from_hex(0x8991bb)),
    string: Some(Color::from_hex(0x05cb0d)),
    function: Some(Color::from_hex(0x550068)),
    variable: Some(Color::from_hex(0x00d9e9)),
    r#type: Some(Color::from_hex(0x955ae7)),
    constant: Some(Color::from_hex(0xaa00a3)),
    operator: Some(Color::from_hex(0xffeeff)),
    tag: Some(Color::from_hex(0x00d9e9)),
    error: Some(Color::from_hex(0x00d9e9)),
    warning: Some(Color::from_hex(0x955ae7)),
    info: Some(Color::from_hex(0x550068)),
    success: Some(Color::from_hex(0x05cb0d)),
    red: Some(Color::from_hex(0x00d9e9)),
    orange: Some(Color::from_hex(0xaa00a3)),
    yellow: Some(Color::from_hex(0x955ae7)),
    green: Some(Color::from_hex(0x05cb0d)),
    cyan: Some(Color::from_hex(0xb900b1)),
    blue: Some(Color::from_hex(0x550068)),
    purple: Some(Color::from_hex(0x8991bb)),
    magenta: Some(Color::from_hex(0x4d6fff)),
};
