//! Mocha color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Mocha
///
/// Author: Chris Kempson (http://chriskempson.com)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Mocha"),
    author: Cow::Borrowed("Chris Kempson (http://chriskempson.com)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x3b3228),
    fg: Color::from_hex(0xd0c8c6),
    cursor: Some(Color::from_hex(0xd0c8c6)),
    selection: Some(Color::from_hex(0x645240)),
    line_highlight: Some(Color::from_hex(0x534636)),
    gutter: Some(Color::from_hex(0x7e705a)),
    statusbar_bg: Some(Color::from_hex(0x534636)),
    statusbar_fg: Some(Color::from_hex(0xb8afad)),
    comment: Some(Color::from_hex(0x7e705a)),
    keyword: Some(Color::from_hex(0xa89bb9)),
    string: Some(Color::from_hex(0xbeb55b)),
    function: Some(Color::from_hex(0x8ab3b5)),
    variable: Some(Color::from_hex(0xcb6077)),
    r#type: Some(Color::from_hex(0xf4bc87)),
    constant: Some(Color::from_hex(0xd28b71)),
    operator: Some(Color::from_hex(0xd0c8c6)),
    tag: Some(Color::from_hex(0xcb6077)),
    error: Some(Color::from_hex(0xcb6077)),
    warning: Some(Color::from_hex(0xf4bc87)),
    info: Some(Color::from_hex(0x8ab3b5)),
    success: Some(Color::from_hex(0xbeb55b)),
    red: Some(Color::from_hex(0xcb6077)),
    orange: Some(Color::from_hex(0xd28b71)),
    yellow: Some(Color::from_hex(0xf4bc87)),
    green: Some(Color::from_hex(0xbeb55b)),
    cyan: Some(Color::from_hex(0x7bbda4)),
    blue: Some(Color::from_hex(0x8ab3b5)),
    purple: Some(Color::from_hex(0xa89bb9)),
    magenta: Some(Color::from_hex(0xbb9584)),
};
