//! Moonlight color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Moonlight
///
/// Author: Jeremy Swinarton (https://github.com/jswinarton)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Moonlight"),
    author: Cow::Borrowed("Jeremy Swinarton (https://github.com/jswinarton)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x212337),
    fg: Color::from_hex(0xa3ace1),
    cursor: Some(Color::from_hex(0xa3ace1)),
    selection: Some(Color::from_hex(0x596399)),
    line_highlight: Some(Color::from_hex(0x403c64)),
    gutter: Some(Color::from_hex(0x748cd6)),
    statusbar_bg: Some(Color::from_hex(0x403c64)),
    statusbar_fg: Some(Color::from_hex(0xa1abe0)),
    comment: Some(Color::from_hex(0x748cd6)),
    keyword: Some(Color::from_hex(0xb994f1)),
    string: Some(Color::from_hex(0x2df4c0)),
    function: Some(Color::from_hex(0x40ffff)),
    variable: Some(Color::from_hex(0xff5370)),
    r#type: Some(Color::from_hex(0xffc777)),
    constant: Some(Color::from_hex(0xf67f81)),
    operator: Some(Color::from_hex(0xa3ace1)),
    tag: Some(Color::from_hex(0xff5370)),
    error: Some(Color::from_hex(0xff5370)),
    warning: Some(Color::from_hex(0xffc777)),
    info: Some(Color::from_hex(0x40ffff)),
    success: Some(Color::from_hex(0x2df4c0)),
    red: Some(Color::from_hex(0xff5370)),
    orange: Some(Color::from_hex(0xf67f81)),
    yellow: Some(Color::from_hex(0xffc777)),
    green: Some(Color::from_hex(0x2df4c0)),
    cyan: Some(Color::from_hex(0x04d1f9)),
    blue: Some(Color::from_hex(0x40ffff)),
    purple: Some(Color::from_hex(0xb994f1)),
    magenta: Some(Color::from_hex(0xecb2f0)),
};
