//! Mountain color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Mountain
///
/// Author: gnsfujiwara (https://github.com/gnsfujiwara)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Mountain",
    author: "gnsfujiwara (https://github.com/gnsfujiwara)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0f0f0f),
    fg: Color::from_hex(0xcacaca),
    cursor: Some(Color::from_hex(0xcacaca)),
    selection: Some(Color::from_hex(0x262626)),
    line_highlight: Some(Color::from_hex(0x191919)),
    gutter: Some(Color::from_hex(0x393939)),
    statusbar_bg: Some(Color::from_hex(0x191919)),
    statusbar_fg: Some(Color::from_hex(0x4c4c4c)),
    comment: Some(Color::from_hex(0x393939)),
    keyword: Some(Color::from_hex(0xac8aac)),
    string: Some(Color::from_hex(0x8aac8b)),
    function: Some(Color::from_hex(0x8f8aac)),
    variable: Some(Color::from_hex(0xac8a8c)),
    r#type: Some(Color::from_hex(0xaca98a)),
    constant: Some(Color::from_hex(0xceb188)),
    operator: Some(Color::from_hex(0xcacaca)),
    tag: Some(Color::from_hex(0xac8a8c)),
    error: Some(Color::from_hex(0xac8a8c)),
    warning: Some(Color::from_hex(0xaca98a)),
    info: Some(Color::from_hex(0x8f8aac)),
    success: Some(Color::from_hex(0x8aac8b)),
    red: Some(Color::from_hex(0xac8a8c)),
    orange: Some(Color::from_hex(0xceb188)),
    yellow: Some(Color::from_hex(0xaca98a)),
    green: Some(Color::from_hex(0x8aac8b)),
    cyan: Some(Color::from_hex(0x8aabac)),
    blue: Some(Color::from_hex(0x8f8aac)),
    purple: Some(Color::from_hex(0xac8aac)),
    magenta: Some(Color::from_hex(0xac8a8c)),
};
