//! Nord Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Nord Light
///
/// Author: threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs)
/// Variant: Light
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Nord Light"),
    author: Cow::Borrowed("threddast, based on fuxialexander's doom-nord-light-theme (Doom Emacs)"),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xe5e9f0),
    fg: Color::from_hex(0x2e3440),
    cursor: Some(Color::from_hex(0x2e3440)),
    selection: Some(Color::from_hex(0xb8c5db)),
    line_highlight: Some(Color::from_hex(0xc2d0e7)),
    gutter: Some(Color::from_hex(0xaebacf)),
    statusbar_bg: Some(Color::from_hex(0xc2d0e7)),
    statusbar_fg: Some(Color::from_hex(0x60728c)),
    comment: Some(Color::from_hex(0xaebacf)),
    keyword: Some(Color::from_hex(0x97365b)),
    string: Some(Color::from_hex(0x4f894c)),
    function: Some(Color::from_hex(0x3b6ea8)),
    variable: Some(Color::from_hex(0x99324b)),
    r#type: Some(Color::from_hex(0x9a7500)),
    constant: Some(Color::from_hex(0xac4426)),
    operator: Some(Color::from_hex(0x2e3440)),
    tag: Some(Color::from_hex(0x99324b)),
    error: Some(Color::from_hex(0x99324b)),
    warning: Some(Color::from_hex(0x9a7500)),
    info: Some(Color::from_hex(0x3b6ea8)),
    success: Some(Color::from_hex(0x4f894c)),
    red: Some(Color::from_hex(0x99324b)),
    orange: Some(Color::from_hex(0xac4426)),
    yellow: Some(Color::from_hex(0x9a7500)),
    green: Some(Color::from_hex(0x4f894c)),
    cyan: Some(Color::from_hex(0x398eac)),
    blue: Some(Color::from_hex(0x3b6ea8)),
    purple: Some(Color::from_hex(0x97365b)),
    magenta: Some(Color::from_hex(0x5272af)),
};
