//! Outrun Dark color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Outrun Dark
///
/// Author: Hugo Delahousse (http://github.com/hugodelahousse/)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Outrun Dark",
    author: "Hugo Delahousse (http://github.com/hugodelahousse/)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x00002a),
    fg: Color::from_hex(0xd0d0fa),
    cursor: Some(Color::from_hex(0xd0d0fa)),
    selection: Some(Color::from_hex(0x30305a)),
    line_highlight: Some(Color::from_hex(0x20204a)),
    gutter: Some(Color::from_hex(0x50507a)),
    statusbar_bg: Some(Color::from_hex(0x20204a)),
    statusbar_fg: Some(Color::from_hex(0xb0b0da)),
    comment: Some(Color::from_hex(0x50507a)),
    keyword: Some(Color::from_hex(0xf10596)),
    string: Some(Color::from_hex(0x59f176)),
    function: Some(Color::from_hex(0x66b0ff)),
    variable: Some(Color::from_hex(0xff4242)),
    r#type: Some(Color::from_hex(0xf3e877)),
    constant: Some(Color::from_hex(0xfc8d28)),
    operator: Some(Color::from_hex(0xd0d0fa)),
    tag: Some(Color::from_hex(0xff4242)),
    error: Some(Color::from_hex(0xff4242)),
    warning: Some(Color::from_hex(0xf3e877)),
    info: Some(Color::from_hex(0x66b0ff)),
    success: Some(Color::from_hex(0x59f176)),
    red: Some(Color::from_hex(0xff4242)),
    orange: Some(Color::from_hex(0xfc8d28)),
    yellow: Some(Color::from_hex(0xf3e877)),
    green: Some(Color::from_hex(0x59f176)),
    cyan: Some(Color::from_hex(0x0ef0f0)),
    blue: Some(Color::from_hex(0x66b0ff)),
    purple: Some(Color::from_hex(0xf10596)),
    magenta: Some(Color::from_hex(0xf003ef)),
};
