//! Pasque color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Pasque
///
/// Author: Gabriel Fontes (https://github.com/Misterio77)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Pasque"),
    author: Cow::Borrowed("Gabriel Fontes (https://github.com/Misterio77)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x271c3a),
    fg: Color::from_hex(0xdedcdf),
    cursor: Some(Color::from_hex(0xdedcdf)),
    selection: Some(Color::from_hex(0x3e2d5c)),
    line_highlight: Some(Color::from_hex(0x100323)),
    gutter: Some(Color::from_hex(0x5d5766)),
    statusbar_bg: Some(Color::from_hex(0x100323)),
    statusbar_fg: Some(Color::from_hex(0xbebcbf)),
    comment: Some(Color::from_hex(0x5d5766)),
    keyword: Some(Color::from_hex(0x953b9d)),
    string: Some(Color::from_hex(0xc6914b)),
    function: Some(Color::from_hex(0x8e7dc6)),
    variable: Some(Color::from_hex(0xa92258)),
    r#type: Some(Color::from_hex(0x804ead)),
    constant: Some(Color::from_hex(0x918889)),
    operator: Some(Color::from_hex(0xdedcdf)),
    tag: Some(Color::from_hex(0xa92258)),
    error: Some(Color::from_hex(0xa92258)),
    warning: Some(Color::from_hex(0x804ead)),
    info: Some(Color::from_hex(0x8e7dc6)),
    success: Some(Color::from_hex(0xc6914b)),
    red: Some(Color::from_hex(0xa92258)),
    orange: Some(Color::from_hex(0x918889)),
    yellow: Some(Color::from_hex(0x804ead)),
    green: Some(Color::from_hex(0xc6914b)),
    cyan: Some(Color::from_hex(0x7263aa)),
    blue: Some(Color::from_hex(0x8e7dc6)),
    purple: Some(Color::from_hex(0x953b9d)),
    magenta: Some(Color::from_hex(0x59325c)),
};
