//! Penumbra Dark Contrast Plus Plus color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Penumbra Dark Contrast Plus Plus
///
/// Author: Zachary Weiss (https://github.com/zacharyweiss)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Penumbra Dark Contrast Plus Plus",
    author: "Zachary Weiss (https://github.com/zacharyweiss)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x0d0f13),
    fg: Color::from_hex(0xdedede),
    cursor: Some(Color::from_hex(0xdedede)),
    selection: Some(Color::from_hex(0x3e4044)),
    line_highlight: Some(Color::from_hex(0x181b1f)),
    gutter: Some(Color::from_hex(0x636363)),
    statusbar_bg: Some(Color::from_hex(0x181b1f)),
    statusbar_fg: Some(Color::from_hex(0xaeaeae)),
    comment: Some(Color::from_hex(0x636363)),
    keyword: Some(Color::from_hex(0xb69cf6)),
    string: Some(Color::from_hex(0x54c794)),
    function: Some(Color::from_hex(0x6eb2fd)),
    variable: Some(Color::from_hex(0xf58c81)),
    r#type: Some(Color::from_hex(0xa9b852)),
    constant: Some(Color::from_hex(0xe09f47)),
    operator: Some(Color::from_hex(0xdedede)),
    tag: Some(Color::from_hex(0xf58c81)),
    error: Some(Color::from_hex(0xf58c81)),
    warning: Some(Color::from_hex(0xa9b852)),
    info: Some(Color::from_hex(0x6eb2fd)),
    success: Some(Color::from_hex(0x54c794)),
    red: Some(Color::from_hex(0xf58c81)),
    orange: Some(Color::from_hex(0xe09f47)),
    yellow: Some(Color::from_hex(0xa9b852)),
    green: Some(Color::from_hex(0x54c794)),
    cyan: Some(Color::from_hex(0x00c4d7)),
    blue: Some(Color::from_hex(0x6eb2fd)),
    purple: Some(Color::from_hex(0xb69cf6)),
    magenta: Some(Color::from_hex(0xe58cc5)),
};
