//! Pico color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Pico
///
/// Author: PICO-8 (http://www.lexaloffle.com/pico-8.php)
/// Variant: Dark
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Pico",
    author: "PICO-8 (http://www.lexaloffle.com/pico-8.php)",
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0x5f574f),
    cursor: Some(Color::from_hex(0x5f574f)),
    selection: Some(Color::from_hex(0x7e2553)),
    line_highlight: Some(Color::from_hex(0x1d2b53)),
    gutter: Some(Color::from_hex(0x008751)),
    statusbar_bg: Some(Color::from_hex(0x1d2b53)),
    statusbar_fg: Some(Color::from_hex(0xab5236)),
    comment: Some(Color::from_hex(0x008751)),
    keyword: Some(Color::from_hex(0xff77a8)),
    string: Some(Color::from_hex(0x00e756)),
    function: Some(Color::from_hex(0x83769c)),
    variable: Some(Color::from_hex(0xff004d)),
    r#type: Some(Color::from_hex(0xfff024)),
    constant: Some(Color::from_hex(0xffa300)),
    operator: Some(Color::from_hex(0x5f574f)),
    tag: Some(Color::from_hex(0xff004d)),
    error: Some(Color::from_hex(0xff004d)),
    warning: Some(Color::from_hex(0xfff024)),
    info: Some(Color::from_hex(0x83769c)),
    success: Some(Color::from_hex(0x00e756)),
    red: Some(Color::from_hex(0xff004d)),
    orange: Some(Color::from_hex(0xffa300)),
    yellow: Some(Color::from_hex(0xfff024)),
    green: Some(Color::from_hex(0x00e756)),
    cyan: Some(Color::from_hex(0x29adff)),
    blue: Some(Color::from_hex(0x83769c)),
    purple: Some(Color::from_hex(0xff77a8)),
    magenta: Some(Color::from_hex(0xffccaa)),
};
