//! pinky color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// pinky
///
/// Author: Benjamin (https://github.com/b3nj5m1n)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "pinky",
    author: "Benjamin (https://github.com/b3nj5m1n)",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x171517),
    fg: Color::from_hex(0xf5f5f5),
    cursor: Some(Color::from_hex(0xf5f5f5)),
    selection: Some(Color::from_hex(0x1d1b1d)),
    line_highlight: Some(Color::from_hex(0x1b181b)),
    gutter: Some(Color::from_hex(0x383338)),
    statusbar_bg: Some(Color::from_hex(0x1b181b)),
    statusbar_fg: Some(Color::from_hex(0xe7dbdb)),
    comment: Some(Color::from_hex(0x383338)),
    keyword: Some(Color::from_hex(0x007fff)),
    string: Some(Color::from_hex(0xff0066)),
    function: Some(Color::from_hex(0x00ffff)),
    variable: Some(Color::from_hex(0xffa600)),
    r#type: Some(Color::from_hex(0x20df6c)),
    constant: Some(Color::from_hex(0x00ff66)),
    operator: Some(Color::from_hex(0xf5f5f5)),
    tag: Some(Color::from_hex(0xffa600)),
    error: Some(Color::from_hex(0xffa600)),
    warning: Some(Color::from_hex(0x20df6c)),
    info: Some(Color::from_hex(0x00ffff)),
    success: Some(Color::from_hex(0xff0066)),
    red: Some(Color::from_hex(0xffa600)),
    orange: Some(Color::from_hex(0x00ff66)),
    yellow: Some(Color::from_hex(0x20df6c)),
    green: Some(Color::from_hex(0xff0066)),
    cyan: Some(Color::from_hex(0x6600ff)),
    blue: Some(Color::from_hex(0x00ffff)),
    purple: Some(Color::from_hex(0x007fff)),
    magenta: Some(Color::from_hex(0xdf206c)),
};
