//! Pop color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Pop
///
/// Author: Chris Kempson (http://chriskempson.com)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Pop"),
    author: Cow::Borrowed("Chris Kempson (http://chriskempson.com)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xd0d0d0)),
    selection: Some(Color::from_hex(0x303030)),
    line_highlight: Some(Color::from_hex(0x202020)),
    gutter: Some(Color::from_hex(0x505050)),
    statusbar_bg: Some(Color::from_hex(0x202020)),
    statusbar_fg: Some(Color::from_hex(0xb0b0b0)),
    comment: Some(Color::from_hex(0x505050)),
    keyword: Some(Color::from_hex(0xb31e8d)),
    string: Some(Color::from_hex(0x37b349)),
    function: Some(Color::from_hex(0x0e5a94)),
    variable: Some(Color::from_hex(0xeb008a)),
    r#type: Some(Color::from_hex(0xf8ca12)),
    constant: Some(Color::from_hex(0xf29333)),
    operator: Some(Color::from_hex(0xd0d0d0)),
    tag: Some(Color::from_hex(0xeb008a)),
    error: Some(Color::from_hex(0xeb008a)),
    warning: Some(Color::from_hex(0xf8ca12)),
    info: Some(Color::from_hex(0x0e5a94)),
    success: Some(Color::from_hex(0x37b349)),
    red: Some(Color::from_hex(0xeb008a)),
    orange: Some(Color::from_hex(0xf29333)),
    yellow: Some(Color::from_hex(0xf8ca12)),
    green: Some(Color::from_hex(0x37b349)),
    cyan: Some(Color::from_hex(0x00aabb)),
    blue: Some(Color::from_hex(0x0e5a94)),
    purple: Some(Color::from_hex(0xb31e8d)),
    magenta: Some(Color::from_hex(0x7a2d00)),
};
