//! Porple color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Porple
///
/// Author: Niek den Breeje (https://github.com/AuditeMarlow)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Porple"),
    author: Cow::Borrowed("Niek den Breeje (https://github.com/AuditeMarlow)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x292c36),
    fg: Color::from_hex(0xd8d8d8),
    cursor: Some(Color::from_hex(0xd8d8d8)),
    selection: Some(Color::from_hex(0x474160)),
    line_highlight: Some(Color::from_hex(0x333344)),
    gutter: Some(Color::from_hex(0x65568a)),
    statusbar_bg: Some(Color::from_hex(0x333344)),
    statusbar_fg: Some(Color::from_hex(0xb8b8b8)),
    comment: Some(Color::from_hex(0x65568a)),
    keyword: Some(Color::from_hex(0xb74989)),
    string: Some(Color::from_hex(0x95c76f)),
    function: Some(Color::from_hex(0x8485ce)),
    variable: Some(Color::from_hex(0xf84547)),
    r#type: Some(Color::from_hex(0xefa16b)),
    constant: Some(Color::from_hex(0xd28e5d)),
    operator: Some(Color::from_hex(0xd8d8d8)),
    tag: Some(Color::from_hex(0xf84547)),
    error: Some(Color::from_hex(0xf84547)),
    warning: Some(Color::from_hex(0xefa16b)),
    info: Some(Color::from_hex(0x8485ce)),
    success: Some(Color::from_hex(0x95c76f)),
    red: Some(Color::from_hex(0xf84547)),
    orange: Some(Color::from_hex(0xd28e5d)),
    yellow: Some(Color::from_hex(0xefa16b)),
    green: Some(Color::from_hex(0x95c76f)),
    cyan: Some(Color::from_hex(0x64878f)),
    blue: Some(Color::from_hex(0x8485ce)),
    purple: Some(Color::from_hex(0xb74989)),
    magenta: Some(Color::from_hex(0x986841)),
};
