//! Precious Light White color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Precious Light White
///
/// Author: 4lex4 <4lex49@zoho.com>
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Precious Light White",
    author: "4lex4 <4lex49@zoho.com>",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x555555),
    cursor: Some(Color::from_hex(0x555555)),
    selection: Some(Color::from_hex(0xdbdbdb)),
    line_highlight: Some(Color::from_hex(0xededed)),
    gutter: Some(Color::from_hex(0x848484)),
    statusbar_bg: Some(Color::from_hex(0xededed)),
    statusbar_fg: Some(Color::from_hex(0x636363)),
    comment: Some(Color::from_hex(0x848484)),
    keyword: Some(Color::from_hex(0x7b4ecb)),
    string: Some(Color::from_hex(0x557301)),
    function: Some(Color::from_hex(0x186daa)),
    variable: Some(Color::from_hex(0xaf4947)),
    r#type: Some(Color::from_hex(0x876500)),
    constant: Some(Color::from_hex(0xa0570d)),
    operator: Some(Color::from_hex(0x555555)),
    tag: Some(Color::from_hex(0xaf4947)),
    error: Some(Color::from_hex(0xaf4947)),
    warning: Some(Color::from_hex(0x876500)),
    info: Some(Color::from_hex(0x186daa)),
    success: Some(Color::from_hex(0x557301)),
    red: Some(Color::from_hex(0xaf4947)),
    orange: Some(Color::from_hex(0xa0570d)),
    yellow: Some(Color::from_hex(0x876500)),
    green: Some(Color::from_hex(0x557301)),
    cyan: Some(Color::from_hex(0x087767)),
    blue: Some(Color::from_hex(0x186daa)),
    purple: Some(Color::from_hex(0x7b4ecb)),
    magenta: Some(Color::from_hex(0xa93e93)),
};
