//! Primer Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Primer Light
///
/// Author: Jimmy Lin
/// Variant: Light
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Primer Light",
    author: "Jimmy Lin",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xfafbfc),
    fg: Color::from_hex(0x2f363d),
    cursor: Some(Color::from_hex(0x2f363d)),
    selection: Some(Color::from_hex(0xd1d5da)),
    line_highlight: Some(Color::from_hex(0xe1e4e8)),
    gutter: Some(Color::from_hex(0x959da5)),
    statusbar_bg: Some(Color::from_hex(0xe1e4e8)),
    statusbar_fg: Some(Color::from_hex(0x444d56)),
    comment: Some(Color::from_hex(0x959da5)),
    keyword: Some(Color::from_hex(0xea4aaa)),
    string: Some(Color::from_hex(0x28a745)),
    function: Some(Color::from_hex(0x0366d6)),
    variable: Some(Color::from_hex(0xd73a49)),
    r#type: Some(Color::from_hex(0xffd33d)),
    constant: Some(Color::from_hex(0xf66a0a)),
    operator: Some(Color::from_hex(0x2f363d)),
    tag: Some(Color::from_hex(0xd73a49)),
    error: Some(Color::from_hex(0xd73a49)),
    warning: Some(Color::from_hex(0xffd33d)),
    info: Some(Color::from_hex(0x0366d6)),
    success: Some(Color::from_hex(0x28a745)),
    red: Some(Color::from_hex(0xd73a49)),
    orange: Some(Color::from_hex(0xf66a0a)),
    yellow: Some(Color::from_hex(0xffd33d)),
    green: Some(Color::from_hex(0x28a745)),
    cyan: Some(Color::from_hex(0x79b8ff)),
    blue: Some(Color::from_hex(0x0366d6)),
    purple: Some(Color::from_hex(0xea4aaa)),
    magenta: Some(Color::from_hex(0xa04100)),
};
