//! Qualia color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Qualia
///
/// Author: isaacwhanson
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Qualia"),
    author: Cow::Borrowed("isaacwhanson"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x101010),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0xc0c0c0)),
    selection: Some(Color::from_hex(0x454545)),
    line_highlight: Some(Color::from_hex(0x454545)),
    gutter: Some(Color::from_hex(0x454545)),
    statusbar_bg: Some(Color::from_hex(0x454545)),
    statusbar_fg: Some(Color::from_hex(0x808080)),
    comment: Some(Color::from_hex(0x454545)),
    keyword: Some(Color::from_hex(0xe0af85)),
    string: Some(Color::from_hex(0x80c990)),
    function: Some(Color::from_hex(0x50cacd)),
    variable: Some(Color::from_hex(0xefa6a2)),
    r#type: Some(Color::from_hex(0xe6a3dc)),
    constant: Some(Color::from_hex(0xa3b8ef)),
    operator: Some(Color::from_hex(0xc0c0c0)),
    tag: Some(Color::from_hex(0xefa6a2)),
    error: Some(Color::from_hex(0xefa6a2)),
    warning: Some(Color::from_hex(0xe6a3dc)),
    info: Some(Color::from_hex(0x50cacd)),
    success: Some(Color::from_hex(0x80c990)),
    red: Some(Color::from_hex(0xefa6a2)),
    orange: Some(Color::from_hex(0xa3b8ef)),
    yellow: Some(Color::from_hex(0xe6a3dc)),
    green: Some(Color::from_hex(0x80c990)),
    cyan: Some(Color::from_hex(0xc8c874)),
    blue: Some(Color::from_hex(0x50cacd)),
    purple: Some(Color::from_hex(0xe0af85)),
    magenta: Some(Color::from_hex(0x808080)),
};
