//! Sakura color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Sakura
///
/// Author: Misterio77 (http://github.com/Misterio77)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Sakura",
    author: "Misterio77 (http://github.com/Misterio77)",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xfeedf3),
    fg: Color::from_hex(0x564448),
    cursor: Some(Color::from_hex(0x564448)),
    selection: Some(Color::from_hex(0xe0ccd1)),
    line_highlight: Some(Color::from_hex(0xf8e2e7)),
    gutter: Some(Color::from_hex(0x755f64)),
    statusbar_bg: Some(Color::from_hex(0xf8e2e7)),
    statusbar_fg: Some(Color::from_hex(0x665055)),
    comment: Some(Color::from_hex(0x755f64)),
    keyword: Some(Color::from_hex(0x5e2180)),
    string: Some(Color::from_hex(0x2e916d)),
    function: Some(Color::from_hex(0x006e93)),
    variable: Some(Color::from_hex(0xdf2d52)),
    r#type: Some(Color::from_hex(0xc29461)),
    constant: Some(Color::from_hex(0xf6661e)),
    operator: Some(Color::from_hex(0x564448)),
    tag: Some(Color::from_hex(0xdf2d52)),
    error: Some(Color::from_hex(0xdf2d52)),
    warning: Some(Color::from_hex(0xc29461)),
    info: Some(Color::from_hex(0x006e93)),
    success: Some(Color::from_hex(0x2e916d)),
    red: Some(Color::from_hex(0xdf2d52)),
    orange: Some(Color::from_hex(0xf6661e)),
    yellow: Some(Color::from_hex(0xc29461)),
    green: Some(Color::from_hex(0x2e916d)),
    cyan: Some(Color::from_hex(0x1d8991)),
    blue: Some(Color::from_hex(0x006e93)),
    purple: Some(Color::from_hex(0x5e2180)),
    magenta: Some(Color::from_hex(0xba0d35)),
};
