//! Terracotta Dark color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Terracotta Dark
///
/// Author: Alexander Rossell Hayes (https://github.com/rossellhayes)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Terracotta Dark",
    author: "Alexander Rossell Hayes (https://github.com/rossellhayes)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x241d1a),
    fg: Color::from_hex(0xb8a59d),
    cursor: Some(Color::from_hex(0xb8a59d)),
    selection: Some(Color::from_hex(0x473933)),
    line_highlight: Some(Color::from_hex(0x362b27)),
    gutter: Some(Color::from_hex(0x594740)),
    statusbar_bg: Some(Color::from_hex(0x362b27)),
    statusbar_fg: Some(Color::from_hex(0xa78e84)),
    comment: Some(Color::from_hex(0x594740)),
    keyword: Some(Color::from_hex(0xd8a2b0)),
    string: Some(Color::from_hex(0xb6c68a)),
    function: Some(Color::from_hex(0xb0a4c3)),
    variable: Some(Color::from_hex(0xf6998f)),
    r#type: Some(Color::from_hex(0xffc37a)),
    constant: Some(Color::from_hex(0xffa888)),
    operator: Some(Color::from_hex(0xb8a59d)),
    tag: Some(Color::from_hex(0xf6998f)),
    error: Some(Color::from_hex(0xf6998f)),
    warning: Some(Color::from_hex(0xffc37a)),
    info: Some(Color::from_hex(0xb0a4c3)),
    success: Some(Color::from_hex(0xb6c68a)),
    red: Some(Color::from_hex(0xf6998f)),
    orange: Some(Color::from_hex(0xffa888)),
    yellow: Some(Color::from_hex(0xffc37a)),
    green: Some(Color::from_hex(0xb6c68a)),
    cyan: Some(Color::from_hex(0xc0bcdb)),
    blue: Some(Color::from_hex(0xb0a4c3)),
    purple: Some(Color::from_hex(0xd8a2b0)),
    magenta: Some(Color::from_hex(0xf1ae97)),
};
