//! Tokyo Night Terminal Storm color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Tokyo Night Terminal Storm
///
/// Author: Michaël Ball
/// Variant: Dark
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Tokyo Night Terminal Storm"),
    author: Cow::Borrowed("Michaël Ball"),
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x24283b),
    fg: Color::from_hex(0x787c99),
    cursor: Some(Color::from_hex(0x787c99)),
    selection: Some(Color::from_hex(0x343a52)),
    line_highlight: Some(Color::from_hex(0x1a1b26)),
    gutter: Some(Color::from_hex(0x444b6a)),
    statusbar_bg: Some(Color::from_hex(0x1a1b26)),
    statusbar_fg: Some(Color::from_hex(0x787c99)),
    comment: Some(Color::from_hex(0x444b6a)),
    keyword: Some(Color::from_hex(0xbb9af7)),
    string: Some(Color::from_hex(0x41a6b5)),
    function: Some(Color::from_hex(0x7aa2f7)),
    variable: Some(Color::from_hex(0xf7768e)),
    r#type: Some(Color::from_hex(0xe0af68)),
    constant: Some(Color::from_hex(0xff9e64)),
    operator: Some(Color::from_hex(0x787c99)),
    tag: Some(Color::from_hex(0xf7768e)),
    error: Some(Color::from_hex(0xf7768e)),
    warning: Some(Color::from_hex(0xe0af68)),
    info: Some(Color::from_hex(0x7aa2f7)),
    success: Some(Color::from_hex(0x41a6b5)),
    red: Some(Color::from_hex(0xf7768e)),
    orange: Some(Color::from_hex(0xff9e64)),
    yellow: Some(Color::from_hex(0xe0af68)),
    green: Some(Color::from_hex(0x41a6b5)),
    cyan: Some(Color::from_hex(0x7dcfff)),
    blue: Some(Color::from_hex(0x7aa2f7)),
    purple: Some(Color::from_hex(0xbb9af7)),
    magenta: Some(Color::from_hex(0xd18616)),
};
