//! Tokyo City Dark color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Tokyo City Dark
///
/// Author: Michaël Ball
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Tokyo City Dark",
    author: "Michaël Ball",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x171d23),
    fg: Color::from_hex(0xd8e2ec),
    cursor: Some(Color::from_hex(0xd8e2ec)),
    selection: Some(Color::from_hex(0x28323a)),
    line_highlight: Some(Color::from_hex(0x1d252c)),
    gutter: Some(Color::from_hex(0x526270)),
    statusbar_bg: Some(Color::from_hex(0x1d252c)),
    statusbar_fg: Some(Color::from_hex(0xb7c5d3)),
    comment: Some(Color::from_hex(0x526270)),
    keyword: Some(Color::from_hex(0xbb9af7)),
    string: Some(Color::from_hex(0x9ece6a)),
    function: Some(Color::from_hex(0x7aa2f7)),
    variable: Some(Color::from_hex(0xf7768e)),
    r#type: Some(Color::from_hex(0xb7c5d3)),
    constant: Some(Color::from_hex(0xff9e64)),
    operator: Some(Color::from_hex(0xd8e2ec)),
    tag: Some(Color::from_hex(0xf7768e)),
    error: Some(Color::from_hex(0xf7768e)),
    warning: Some(Color::from_hex(0xb7c5d3)),
    info: Some(Color::from_hex(0x7aa2f7)),
    success: Some(Color::from_hex(0x9ece6a)),
    red: Some(Color::from_hex(0xf7768e)),
    orange: Some(Color::from_hex(0xff9e64)),
    yellow: Some(Color::from_hex(0xb7c5d3)),
    green: Some(Color::from_hex(0x9ece6a)),
    cyan: Some(Color::from_hex(0x89ddff)),
    blue: Some(Color::from_hex(0x7aa2f7)),
    purple: Some(Color::from_hex(0xbb9af7)),
    magenta: Some(Color::from_hex(0xbb9af7)),
};
