//! Tokyodark Terminal color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Tokyodark Terminal
///
/// Author: Tiagovla (https://github.com/tiagovla/)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Tokyodark Terminal",
    author: "Tiagovla (https://github.com/tiagovla/)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x11121d),
    fg: Color::from_hex(0xa0a8cd),
    cursor: Some(Color::from_hex(0xa0a8cd)),
    selection: Some(Color::from_hex(0x212234)),
    line_highlight: Some(Color::from_hex(0x1a1b2a)),
    gutter: Some(Color::from_hex(0x282c34)),
    statusbar_bg: Some(Color::from_hex(0x1a1b2a)),
    statusbar_fg: Some(Color::from_hex(0x4a5057)),
    comment: Some(Color::from_hex(0x282c34)),
    keyword: Some(Color::from_hex(0xa485dd)),
    string: Some(Color::from_hex(0x95c561)),
    function: Some(Color::from_hex(0x7199ee)),
    variable: Some(Color::from_hex(0xee6d85)),
    r#type: Some(Color::from_hex(0xd7a65f)),
    constant: Some(Color::from_hex(0xf6955b)),
    operator: Some(Color::from_hex(0xa0a8cd)),
    tag: Some(Color::from_hex(0xee6d85)),
    error: Some(Color::from_hex(0xee6d85)),
    warning: Some(Color::from_hex(0xd7a65f)),
    info: Some(Color::from_hex(0x7199ee)),
    success: Some(Color::from_hex(0x95c561)),
    red: Some(Color::from_hex(0xee6d85)),
    orange: Some(Color::from_hex(0xf6955b)),
    yellow: Some(Color::from_hex(0xd7a65f)),
    green: Some(Color::from_hex(0x95c561)),
    cyan: Some(Color::from_hex(0x38a89d)),
    blue: Some(Color::from_hex(0x7199ee)),
    purple: Some(Color::from_hex(0xa485dd)),
    magenta: Some(Color::from_hex(0x773440)),
};
