//! Tokyo Night Light color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Tokyo Night Light
///
/// Author: Michaël Ball
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Tokyo Night Light",
    author: "Michaël Ball",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xd5d6db),
    fg: Color::from_hex(0x343b59),
    cursor: Some(Color::from_hex(0x343b59)),
    selection: Some(Color::from_hex(0xdfe0e5)),
    line_highlight: Some(Color::from_hex(0xcbccd1)),
    gutter: Some(Color::from_hex(0x9699a3)),
    statusbar_bg: Some(Color::from_hex(0xcbccd1)),
    statusbar_fg: Some(Color::from_hex(0x4c505e)),
    comment: Some(Color::from_hex(0x9699a3)),
    keyword: Some(Color::from_hex(0x5a4a78)),
    string: Some(Color::from_hex(0x485e30)),
    function: Some(Color::from_hex(0x34548a)),
    variable: Some(Color::from_hex(0x343b58)),
    r#type: Some(Color::from_hex(0x166775)),
    constant: Some(Color::from_hex(0x965027)),
    operator: Some(Color::from_hex(0x343b59)),
    tag: Some(Color::from_hex(0x343b58)),
    error: Some(Color::from_hex(0x343b58)),
    warning: Some(Color::from_hex(0x166775)),
    info: Some(Color::from_hex(0x34548a)),
    success: Some(Color::from_hex(0x485e30)),
    red: Some(Color::from_hex(0x343b58)),
    orange: Some(Color::from_hex(0x965027)),
    yellow: Some(Color::from_hex(0x166775)),
    green: Some(Color::from_hex(0x485e30)),
    cyan: Some(Color::from_hex(0x3e6968)),
    blue: Some(Color::from_hex(0x34548a)),
    purple: Some(Color::from_hex(0x5a4a78)),
    magenta: Some(Color::from_hex(0x8c4351)),
};
