//! Tokyo City Light color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Tokyo City Light
///
/// Author: Michaël Ball
/// Variant: Light
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Tokyo City Light"),
    author: Cow::Borrowed("Michaël Ball"),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xfbfbfd),
    fg: Color::from_hex(0x343b59),
    cursor: Some(Color::from_hex(0x343b59)),
    selection: Some(Color::from_hex(0xedeff6)),
    line_highlight: Some(Color::from_hex(0xf6f6f8)),
    gutter: Some(Color::from_hex(0x9699a3)),
    statusbar_bg: Some(Color::from_hex(0xf6f6f8)),
    statusbar_fg: Some(Color::from_hex(0x4c505e)),
    comment: Some(Color::from_hex(0x9699a3)),
    keyword: Some(Color::from_hex(0x5a4a78)),
    string: Some(Color::from_hex(0x485e30)),
    function: Some(Color::from_hex(0x34548a)),
    variable: Some(Color::from_hex(0x8c4351)),
    r#type: Some(Color::from_hex(0x4c505e)),
    constant: Some(Color::from_hex(0x965027)),
    operator: Some(Color::from_hex(0x343b59)),
    tag: Some(Color::from_hex(0x8c4351)),
    error: Some(Color::from_hex(0x8c4351)),
    warning: Some(Color::from_hex(0x4c505e)),
    info: Some(Color::from_hex(0x34548a)),
    success: Some(Color::from_hex(0x485e30)),
    red: Some(Color::from_hex(0x8c4351)),
    orange: Some(Color::from_hex(0x965027)),
    yellow: Some(Color::from_hex(0x4c505e)),
    green: Some(Color::from_hex(0x485e30)),
    cyan: Some(Color::from_hex(0x4c505e)),
    blue: Some(Color::from_hex(0x34548a)),
    purple: Some(Color::from_hex(0x5a4a78)),
    magenta: Some(Color::from_hex(0x5a4a78)),
};
