//! Tomorrow Night color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Tomorrow Night
///
/// Author: Chris Kempson (http://chriskempson.com)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Tomorrow Night",
    author: "Chris Kempson (http://chriskempson.com)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1d1f21),
    fg: Color::from_hex(0xc5c8c6),
    cursor: Some(Color::from_hex(0xc5c8c6)),
    selection: Some(Color::from_hex(0x373b41)),
    line_highlight: Some(Color::from_hex(0x282a2e)),
    gutter: Some(Color::from_hex(0x969896)),
    statusbar_bg: Some(Color::from_hex(0x282a2e)),
    statusbar_fg: Some(Color::from_hex(0xb4b7b4)),
    comment: Some(Color::from_hex(0x969896)),
    keyword: Some(Color::from_hex(0xb294bb)),
    string: Some(Color::from_hex(0xb5bd68)),
    function: Some(Color::from_hex(0x81a2be)),
    variable: Some(Color::from_hex(0xcc6666)),
    r#type: Some(Color::from_hex(0xf0c674)),
    constant: Some(Color::from_hex(0xde935f)),
    operator: Some(Color::from_hex(0xc5c8c6)),
    tag: Some(Color::from_hex(0xcc6666)),
    error: Some(Color::from_hex(0xcc6666)),
    warning: Some(Color::from_hex(0xf0c674)),
    info: Some(Color::from_hex(0x81a2be)),
    success: Some(Color::from_hex(0xb5bd68)),
    red: Some(Color::from_hex(0xcc6666)),
    orange: Some(Color::from_hex(0xde935f)),
    yellow: Some(Color::from_hex(0xf0c674)),
    green: Some(Color::from_hex(0xb5bd68)),
    cyan: Some(Color::from_hex(0x8abeb7)),
    blue: Some(Color::from_hex(0x81a2be)),
    purple: Some(Color::from_hex(0xb294bb)),
    magenta: Some(Color::from_hex(0xa3685a)),
};
