//! Twilight color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Twilight
///
/// Author: David Hart (https://github.com/hartbit)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Twilight"),
    author: Cow::Borrowed("David Hart (https://github.com/hartbit)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1e1e1e),
    fg: Color::from_hex(0xa7a7a7),
    cursor: Some(Color::from_hex(0xa7a7a7)),
    selection: Some(Color::from_hex(0x464b50)),
    line_highlight: Some(Color::from_hex(0x323537)),
    gutter: Some(Color::from_hex(0x5f5a60)),
    statusbar_bg: Some(Color::from_hex(0x323537)),
    statusbar_fg: Some(Color::from_hex(0x838184)),
    comment: Some(Color::from_hex(0x5f5a60)),
    keyword: Some(Color::from_hex(0x9b859d)),
    string: Some(Color::from_hex(0x8f9d6a)),
    function: Some(Color::from_hex(0x7587a6)),
    variable: Some(Color::from_hex(0xcf6a4c)),
    r#type: Some(Color::from_hex(0xf9ee98)),
    constant: Some(Color::from_hex(0xcda869)),
    operator: Some(Color::from_hex(0xa7a7a7)),
    tag: Some(Color::from_hex(0xcf6a4c)),
    error: Some(Color::from_hex(0xcf6a4c)),
    warning: Some(Color::from_hex(0xf9ee98)),
    info: Some(Color::from_hex(0x7587a6)),
    success: Some(Color::from_hex(0x8f9d6a)),
    red: Some(Color::from_hex(0xcf6a4c)),
    orange: Some(Color::from_hex(0xcda869)),
    yellow: Some(Color::from_hex(0xf9ee98)),
    green: Some(Color::from_hex(0x8f9d6a)),
    cyan: Some(Color::from_hex(0xafc4db)),
    blue: Some(Color::from_hex(0x7587a6)),
    purple: Some(Color::from_hex(0x9b859d)),
    magenta: Some(Color::from_hex(0x9b703f)),
};
