//! Unikitty Dark color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Unikitty Dark
///
/// Author: Josh W Lewis (@joshwlewis)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Unikitty Dark",
    author: "Josh W Lewis (@joshwlewis)",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2e2a31),
    fg: Color::from_hex(0xbcbabe),
    cursor: Some(Color::from_hex(0xbcbabe)),
    selection: Some(Color::from_hex(0x666369)),
    line_highlight: Some(Color::from_hex(0x4a464d)),
    gutter: Some(Color::from_hex(0x838085)),
    statusbar_bg: Some(Color::from_hex(0x4a464d)),
    statusbar_fg: Some(Color::from_hex(0x9f9da2)),
    comment: Some(Color::from_hex(0x838085)),
    keyword: Some(Color::from_hex(0xbb60ea)),
    string: Some(Color::from_hex(0x17ad98)),
    function: Some(Color::from_hex(0x796af5)),
    variable: Some(Color::from_hex(0xd8137f)),
    r#type: Some(Color::from_hex(0xdc8a0e)),
    constant: Some(Color::from_hex(0xd65407)),
    operator: Some(Color::from_hex(0xbcbabe)),
    tag: Some(Color::from_hex(0xd8137f)),
    error: Some(Color::from_hex(0xd8137f)),
    warning: Some(Color::from_hex(0xdc8a0e)),
    info: Some(Color::from_hex(0x796af5)),
    success: Some(Color::from_hex(0x17ad98)),
    red: Some(Color::from_hex(0xd8137f)),
    orange: Some(Color::from_hex(0xd65407)),
    yellow: Some(Color::from_hex(0xdc8a0e)),
    green: Some(Color::from_hex(0x17ad98)),
    cyan: Some(Color::from_hex(0x149bda)),
    blue: Some(Color::from_hex(0x796af5)),
    purple: Some(Color::from_hex(0xbb60ea)),
    magenta: Some(Color::from_hex(0xc720ca)),
};
