//! Valua color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Valua
///
/// Author: Nonetrix (https://github.com/nonetrix)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Valua"),
    author: Cow::Borrowed("Nonetrix (https://github.com/nonetrix)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x131f1f),
    fg: Color::from_hex(0x98c1a3),
    cursor: Some(Color::from_hex(0x98c1a3)),
    selection: Some(Color::from_hex(0x273d3c)),
    line_highlight: Some(Color::from_hex(0x213132)),
    gutter: Some(Color::from_hex(0x3e5c53)),
    statusbar_bg: Some(Color::from_hex(0x213132)),
    statusbar_fg: Some(Color::from_hex(0x6d9877)),
    comment: Some(Color::from_hex(0x3e5c53)),
    keyword: Some(Color::from_hex(0xa874e0)),
    string: Some(Color::from_hex(0x59d678)),
    function: Some(Color::from_hex(0x4ed2d2)),
    variable: Some(Color::from_hex(0xd7586e)),
    r#type: Some(Color::from_hex(0xdfe754)),
    constant: Some(Color::from_hex(0xe6b466)),
    operator: Some(Color::from_hex(0x98c1a3)),
    tag: Some(Color::from_hex(0xd7586e)),
    error: Some(Color::from_hex(0xd7586e)),
    warning: Some(Color::from_hex(0xdfe754)),
    info: Some(Color::from_hex(0x4ed2d2)),
    success: Some(Color::from_hex(0x59d678)),
    red: Some(Color::from_hex(0xd7586e)),
    orange: Some(Color::from_hex(0xe6b466)),
    yellow: Some(Color::from_hex(0xdfe754)),
    green: Some(Color::from_hex(0x59d678)),
    cyan: Some(Color::from_hex(0x76dbd2)),
    blue: Some(Color::from_hex(0x4ed2d2)),
    purple: Some(Color::from_hex(0xa874e0)),
    magenta: Some(Color::from_hex(0xc05a8f)),
};
