//! Windows NT Light color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Windows NT Light
///
/// Author: Fergus Collins (https://github.com/ferguscollins)
/// Variant: Light
/// Contrast: Low
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Windows NT Light",
    author: "Fergus Collins (https://github.com/ferguscollins)",
    variant: Variant::Light,
    contrast: Contrast::Low,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x808080),
    cursor: Some(Color::from_hex(0x808080)),
    selection: Some(Color::from_hex(0xd5d5d5)),
    line_highlight: Some(Color::from_hex(0xeaeaea)),
    gutter: Some(Color::from_hex(0xc0c0c0)),
    statusbar_bg: Some(Color::from_hex(0xeaeaea)),
    statusbar_fg: Some(Color::from_hex(0xa0a0a0)),
    comment: Some(Color::from_hex(0xc0c0c0)),
    keyword: Some(Color::from_hex(0x800080)),
    string: Some(Color::from_hex(0x008000)),
    function: Some(Color::from_hex(0x000080)),
    variable: Some(Color::from_hex(0x800000)),
    r#type: Some(Color::from_hex(0x808000)),
    constant: Some(Color::from_hex(0xffff00)),
    operator: Some(Color::from_hex(0x808080)),
    tag: Some(Color::from_hex(0x800000)),
    error: Some(Color::from_hex(0x800000)),
    warning: Some(Color::from_hex(0x808000)),
    info: Some(Color::from_hex(0x000080)),
    success: Some(Color::from_hex(0x008000)),
    red: Some(Color::from_hex(0x800000)),
    orange: Some(Color::from_hex(0xffff00)),
    yellow: Some(Color::from_hex(0x808000)),
    green: Some(Color::from_hex(0x008000)),
    cyan: Some(Color::from_hex(0x008080)),
    blue: Some(Color::from_hex(0x000080)),
    purple: Some(Color::from_hex(0x800080)),
    magenta: Some(Color::from_hex(0x00ff00)),
};
