//! Windows High Contrast color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Windows High Contrast
///
/// Author: Fergus Collins (https://github.com/ferguscollins)
/// Variant: Dark
/// Contrast: High
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Windows High Contrast"),
    author: Cow::Borrowed("Fergus Collins (https://github.com/ferguscollins)"),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0xc0c0c0)),
    selection: Some(Color::from_hex(0x383838)),
    line_highlight: Some(Color::from_hex(0x1c1c1c)),
    gutter: Some(Color::from_hex(0x545454)),
    statusbar_bg: Some(Color::from_hex(0x1c1c1c)),
    statusbar_fg: Some(Color::from_hex(0xa2a2a2)),
    comment: Some(Color::from_hex(0x545454)),
    keyword: Some(Color::from_hex(0xfc54fc)),
    string: Some(Color::from_hex(0x54fc54)),
    function: Some(Color::from_hex(0x5454fc)),
    variable: Some(Color::from_hex(0xfc5454)),
    r#type: Some(Color::from_hex(0xfcfc54)),
    constant: Some(Color::from_hex(0x808000)),
    operator: Some(Color::from_hex(0xc0c0c0)),
    tag: Some(Color::from_hex(0xfc5454)),
    error: Some(Color::from_hex(0xfc5454)),
    warning: Some(Color::from_hex(0xfcfc54)),
    info: Some(Color::from_hex(0x5454fc)),
    success: Some(Color::from_hex(0x54fc54)),
    red: Some(Color::from_hex(0xfc5454)),
    orange: Some(Color::from_hex(0x808000)),
    yellow: Some(Color::from_hex(0xfcfc54)),
    green: Some(Color::from_hex(0x54fc54)),
    cyan: Some(Color::from_hex(0x54fcfc)),
    blue: Some(Color::from_hex(0x5454fc)),
    purple: Some(Color::from_hex(0xfc54fc)),
    magenta: Some(Color::from_hex(0x008000)),
};
