//! Windows 95 Light color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Windows 95 Light
///
/// Author: Fergus Collins (https://github.com/ferguscollins)
/// Variant: Light
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: "Windows 95 Light",
    author: "Fergus Collins (https://github.com/ferguscollins)",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xfcfcfc),
    fg: Color::from_hex(0x545454),
    cursor: Some(Color::from_hex(0x545454)),
    selection: Some(Color::from_hex(0xc4c4c4)),
    line_highlight: Some(Color::from_hex(0xe0e0e0)),
    gutter: Some(Color::from_hex(0xa8a8a8)),
    statusbar_bg: Some(Color::from_hex(0xe0e0e0)),
    statusbar_fg: Some(Color::from_hex(0x7e7e7e)),
    comment: Some(Color::from_hex(0xa8a8a8)),
    keyword: Some(Color::from_hex(0xa800a8)),
    string: Some(Color::from_hex(0x00a800)),
    function: Some(Color::from_hex(0x0000a8)),
    variable: Some(Color::from_hex(0xa80000)),
    r#type: Some(Color::from_hex(0xa85400)),
    constant: Some(Color::from_hex(0xfcfc54)),
    operator: Some(Color::from_hex(0x545454)),
    tag: Some(Color::from_hex(0xa80000)),
    error: Some(Color::from_hex(0xa80000)),
    warning: Some(Color::from_hex(0xa85400)),
    info: Some(Color::from_hex(0x0000a8)),
    success: Some(Color::from_hex(0x00a800)),
    red: Some(Color::from_hex(0xa80000)),
    orange: Some(Color::from_hex(0xfcfc54)),
    yellow: Some(Color::from_hex(0xa85400)),
    green: Some(Color::from_hex(0x00a800)),
    cyan: Some(Color::from_hex(0x00a8a8)),
    blue: Some(Color::from_hex(0x0000a8)),
    purple: Some(Color::from_hex(0xa800a8)),
    magenta: Some(Color::from_hex(0x54fc54)),
};
