//! Woodland color theme.
//!
//! Auto-generated by `cargo xtask generate base16` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// Woodland
///
/// Author: Jay Cornwall (https://jcornwall.com)
/// Variant: Dark
/// Contrast: Normal
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("Woodland"),
    author: Cow::Borrowed("Jay Cornwall (https://jcornwall.com)"),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x231e18),
    fg: Color::from_hex(0xcabcb1),
    cursor: Some(Color::from_hex(0xcabcb1)),
    selection: Some(Color::from_hex(0x48413a)),
    line_highlight: Some(Color::from_hex(0x302b25)),
    gutter: Some(Color::from_hex(0x9d8b70)),
    statusbar_bg: Some(Color::from_hex(0x302b25)),
    statusbar_fg: Some(Color::from_hex(0xb4a490)),
    comment: Some(Color::from_hex(0x9d8b70)),
    keyword: Some(Color::from_hex(0xbb90e2)),
    string: Some(Color::from_hex(0xb7ba53)),
    function: Some(Color::from_hex(0x88a4d3)),
    variable: Some(Color::from_hex(0xd35c5c)),
    r#type: Some(Color::from_hex(0xe0ac16)),
    constant: Some(Color::from_hex(0xca7f32)),
    operator: Some(Color::from_hex(0xcabcb1)),
    tag: Some(Color::from_hex(0xd35c5c)),
    error: Some(Color::from_hex(0xd35c5c)),
    warning: Some(Color::from_hex(0xe0ac16)),
    info: Some(Color::from_hex(0x88a4d3)),
    success: Some(Color::from_hex(0xb7ba53)),
    red: Some(Color::from_hex(0xd35c5c)),
    orange: Some(Color::from_hex(0xca7f32)),
    yellow: Some(Color::from_hex(0xe0ac16)),
    green: Some(Color::from_hex(0xb7ba53)),
    cyan: Some(Color::from_hex(0x6eb958)),
    blue: Some(Color::from_hex(0x88a4d3)),
    purple: Some(Color::from_hex(0xbb90e2)),
    magenta: Some(Color::from_hex(0xb49368)),
};
