use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Return the project root directory (parent of xtask/).
pub fn project_root() -> PathBuf {
    let mut path = Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf();
    path.pop();
    path
}

/// Sanitize a name into a valid Rust module name (lowercase, underscored).
pub fn sanitize_module_name(name: &str) -> String {
    let sanitized: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect();
    let mut result = String::new();
    let mut prev_underscore = true;
    for c in sanitized.chars() {
        if c == '_' {
            if !prev_underscore {
                result.push('_');
            }
            prev_underscore = true;
        } else {
            result.push(c);
            prev_underscore = false;
        }
    }
    let result = result.trim_matches('_').to_string();
    if result.starts_with(|c: char| c.is_ascii_digit()) {
        format!("_{result}")
    } else {
        result
    }
}

/// Sanitize a name into a valid Rust SCREAMING_SNAKE_CASE constant name.
pub fn sanitize_const_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Write content to a file only if it differs from the current content.
/// Returns `true` if the file was written, `false` if unchanged.
pub fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.exists() {
        let existing =
            fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        if existing == content {
            return Ok(false);
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

/// Generate the standard file preamble comment for a generated module.
pub fn preamble(collection: &str) -> String {
    format!("//! Auto-generated by `cargo xtask generate {collection}` — do not edit.\n")
}

/// Parse a hex color string (with or without `#` prefix) into a u32.
pub fn parse_hex_to_u32(hex: &str) -> Result<u32> {
    let hex = hex.strip_prefix('#').unwrap_or(hex);
    u32::from_str_radix(hex, 16).with_context(|| format!("invalid hex color: '{hex}'"))
}

// --- WCAG contrast detection ---

pub fn srgb_to_linear(c: f64) -> f64 {
    if c <= 0.03928 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

pub fn luminance(hex: u32) -> f64 {
    let r = srgb_to_linear(((hex >> 16) & 0xFF) as f64 / 255.0);
    let g = srgb_to_linear(((hex >> 8) & 0xFF) as f64 / 255.0);
    let b = srgb_to_linear((hex & 0xFF) as f64 / 255.0);
    0.2126 * r + 0.7152 * g + 0.0722 * b
}

pub fn contrast_ratio(hex1: u32, hex2: u32) -> f64 {
    let l1 = luminance(hex1);
    let l2 = luminance(hex2);
    let (lighter, darker) = if l1 > l2 { (l1, l2) } else { (l2, l1) };
    (lighter + 0.05) / (darker + 0.05)
}

pub fn classify_contrast(bg_hex: u32, fg_hex: u32) -> &'static str {
    let ratio = contrast_ratio(bg_hex, fg_hex);
    if ratio >= 10.0 {
        "High"
    } else if ratio >= 4.5 {
        "Normal"
    } else {
        "Low"
    }
}

/// Detect variant from background luminance.
pub fn detect_variant(bg_hex: u32) -> &'static str {
    let lum = luminance(bg_hex);
    if lum > 0.5 { "Light" } else { "Dark" }
}
