use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct Base16Scheme {
    #[allow(dead_code)]
    system: Option<String>,
    name: String,
    author: String,
    variant: Option<String>,
    palette: BTreeMap<String, String>,
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let command = args.get(1).map(|s| s.as_str());

    match command {
        Some("generate") => generate(),
        Some(other) => {
            eprintln!("Unknown command: {other}");
            eprintln!("Usage: cargo xtask generate");
            std::process::exit(1);
        }
        None => {
            eprintln!("Usage: cargo xtask generate");
            std::process::exit(1);
        }
    }
}

fn generate() {
    let project_root = project_root();
    let data_dir = project_root.join("data").join("base16");
    let output_dir = project_root.join("src").join("base16");

    if !data_dir.exists() {
        eprintln!("No data/base16/ directory found at {}", data_dir.display());
        std::process::exit(1);
    }

    let mut generated_modules: Vec<(String, String)> = Vec::new();

    for entry in fs::read_dir(&data_dir).expect("failed to read data/base16/") {
        let entry = entry.expect("failed to read directory entry");
        let path = entry.path();

        if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
            continue;
        }

        let content = fs::read_to_string(&path).expect("failed to read YAML file");
        let scheme: Base16Scheme =
            serde_yaml::from_str(&content).expect("failed to parse YAML scheme");

        let file_stem = path
            .file_stem()
            .unwrap()
            .to_str()
            .unwrap();
        let module_name = sanitize_module_name(file_stem);
        let const_name = sanitize_const_name(&scheme.name);
        let variant = scheme
            .variant
            .as_deref()
            .unwrap_or("dark");

        let rust_code = generate_theme_const(&scheme, &const_name, variant);
        let output_path = output_dir.join(format!("{module_name}.rs"));

        fs::write(&output_path, rust_code).unwrap_or_else(|e| {
            panic!(
                "failed to write {}: {e}",
                output_path.display()
            )
        });

        println!("  Generated: src/base16/{module_name}.rs ({const_name})");
        generated_modules.push((module_name, const_name));
    }

    // Update src/base16/mod.rs
    let mod_content = generate_mod_rs(&generated_modules);
    let mod_path = output_dir.join("mod.rs");
    fs::write(&mod_path, mod_content).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", mod_path.display())
    });

    println!(
        "\nGenerated {} base16 theme(s). Updated src/base16/mod.rs.",
        generated_modules.len()
    );
}

fn generate_theme_const(scheme: &Base16Scheme, _const_name: &str, variant: &str) -> String {
    let get_hex = |key: &str| -> String {
        let hex = scheme
            .palette
            .get(key)
            .or_else(|| scheme.palette.get(&key.to_uppercase()))
            .or_else(|| {
                // Handle mixed case: base0A, base0B, etc.
                let lower = key.to_lowercase();
                scheme.palette.get(&lower)
            })
            .unwrap_or_else(|| panic!("missing palette key {key} in scheme {}", scheme.name));
        // Strip leading '#' if present
        let hex = hex.strip_prefix('#').unwrap_or(hex);
        format!("0x{hex}")
    };

    let variant_enum = match variant {
        "light" => "Light",
        _ => "Dark",
    };

    // Classify contrast based on bg/fg hex distance (simplified)
    let contrast_enum = "Normal";

    let name = &scheme.name;
    let author = &scheme.author;

    let base00 = get_hex("base00");
    let base01 = get_hex("base01");
    let base02 = get_hex("base02");
    let base03 = get_hex("base03");
    let base04 = get_hex("base04");
    let base05 = get_hex("base05");
    let _base06 = get_hex("base06");
    let _base07 = get_hex("base07");
    let base08 = get_hex("base08");
    let base09 = get_hex("base09");
    let base0a = get_hex("base0A");
    let base0b = get_hex("base0B");
    let base0c = get_hex("base0C");
    let base0d = get_hex("base0D");
    let base0e = get_hex("base0E");
    let base0f = get_hex("base0F");

    format!(
        r#"//! {name} color theme.
//!
//! Auto-generated by `cargo xtask generate` — do not edit.

use crate::{{Color, Contrast, Theme, Variant}};

/// {name}
///
/// Author: {author}
/// Variant: {variant_enum}
/// Contrast: {contrast_enum}
/// Source: base16 (tinted-theming/schemes)
pub const THEME: Theme = Theme {{
    name: "{name}",
    author: "{author}",
    variant: Variant::{variant_enum},
    contrast: Contrast::{contrast_enum},
    bg: Color::from_hex({base00}),
    fg: Color::from_hex({base05}),
    cursor: Some(Color::from_hex({base05})),
    selection: Some(Color::from_hex({base02})),
    line_highlight: Some(Color::from_hex({base01})),
    gutter: Some(Color::from_hex({base03})),
    statusbar_bg: Some(Color::from_hex({base01})),
    statusbar_fg: Some(Color::from_hex({base04})),
    comment: Some(Color::from_hex({base03})),
    keyword: Some(Color::from_hex({base0e})),
    string: Some(Color::from_hex({base0b})),
    function: Some(Color::from_hex({base0d})),
    variable: Some(Color::from_hex({base08})),
    r#type: Some(Color::from_hex({base0a})),
    constant: Some(Color::from_hex({base09})),
    operator: Some(Color::from_hex({base05})),
    tag: Some(Color::from_hex({base08})),
    error: Some(Color::from_hex({base08})),
    warning: Some(Color::from_hex({base0a})),
    info: Some(Color::from_hex({base0d})),
    success: Some(Color::from_hex({base0b})),
    red: Some(Color::from_hex({base08})),
    orange: Some(Color::from_hex({base09})),
    yellow: Some(Color::from_hex({base0a})),
    green: Some(Color::from_hex({base0b})),
    cyan: Some(Color::from_hex({base0c})),
    blue: Some(Color::from_hex({base0d})),
    purple: Some(Color::from_hex({base0e})),
    magenta: Some(Color::from_hex({base0f})),
}};
"#
    )
}

fn generate_mod_rs(modules: &[(String, String)]) -> String {
    let mut output = String::from(
        "//! Base16 color themes (~305 schemes).\n\
         //!\n\
         //! Themes sourced from [tinted-theming/schemes](https://github.com/tinted-theming/schemes).\n\
         //! Each theme provides the standard 16 base16 palette slots mapped to\n\
         //! semantic color roles.\n\
         //!\n\
         //! Enable with the `base16` feature flag.\n\
         //!\n\
         //! Auto-generated by `cargo xtask generate` — do not edit.\n\n\
         use crate::Theme;\n\n",
    );

    for (module_name, _) in modules {
        output.push_str(&format!("pub mod {module_name};\n"));
    }

    output.push_str("\n/// All themes in the `base16` collection.\n");
    output.push_str("pub static THEMES: &[&Theme] = &[\n");
    for (module_name, _) in modules {
        output.push_str(&format!("    &{module_name}::THEME,\n"));
    }
    output.push_str("];\n");

    output
}

fn sanitize_module_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

fn sanitize_const_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_uppercase() } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

fn project_root() -> PathBuf {
    let mut path = Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf();
    path.pop(); // Go up from xtask/ to project root
    path
}
