//! anderson color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// anderson
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("anderson"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x363432),
    fg: Color::from_hex(0xc5beba),
    cursor: Some(Color::from_hex(0xa8c1c5)),
    selection: Some(Color::from_hex(0x645d59)),
    line_highlight: Some(Color::from_hex(0x645d59)),
    gutter: Some(Color::from_hex(0x645d59)),
    statusbar_bg: Some(Color::from_hex(0x645d59)),
    statusbar_fg: Some(Color::from_hex(0xc5beba)),
    comment: Some(Color::from_hex(0x837d7a)),
    keyword: Some(Color::from_hex(0xd7ae38)),
    string: Some(Color::from_hex(0x88a2a4)),
    function: Some(Color::from_hex(0x7bb292)),
    variable: Some(Color::from_hex(0xa8c1c5)),
    r#type: Some(Color::from_hex(0xc4c18b)),
    constant: Some(Color::from_hex(0xc7a095)),
    operator: Some(Color::from_hex(0xa8c1c5)),
    tag: Some(Color::from_hex(0xf0a4af)),
    error: Some(Color::from_hex(0xbe503e)),
    warning: Some(Color::from_hex(0xd7ae38)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xbe503e)),
    orange: None,
    yellow: Some(Color::from_hex(0xd7ae38)),
    green: Some(Color::from_hex(0x88a2a4)),
    cyan: Some(Color::from_hex(0xc4c18b)),
    blue: Some(Color::from_hex(0x7bb292)),
    purple: Some(Color::from_hex(0xd7ae38)),
    magenta: Some(Color::from_hex(0xe7c6be)),
};
