//! argonaut color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// argonaut
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "argonaut",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x0e111d),
    fg: Color::from_hex(0xb2b2b2),
    cursor: Some(Color::from_hex(0xff2200)),
    selection: Some(Color::from_hex(0x002f53)),
    line_highlight: Some(Color::from_hex(0x000c16)),
    gutter: Some(Color::from_hex(0x606268)),
    statusbar_bg: Some(Color::from_hex(0x2d3039)),
    statusbar_fg: Some(Color::from_hex(0xb2b2b2)),
    comment: Some(Color::from_hex(0x00a6ff)),
    keyword: Some(Color::from_hex(0xffffff)),
    string: Some(Color::from_hex(0x6497c5)),
    function: Some(Color::from_hex(0xffca00)),
    variable: Some(Color::from_hex(0xffffff)),
    r#type: None,
    constant: Some(Color::from_hex(0xa4ed2d)),
    operator: Some(Color::from_hex(0xffffff)),
    tag: Some(Color::from_hex(0x0065d3)),
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x6497c5)),
    cyan: None,
    blue: Some(Color::from_hex(0xffca00)),
    purple: Some(Color::from_hex(0xffffff)),
    magenta: Some(Color::from_hex(0xffffff)),
};
