//! atom color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// atom
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "atom",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x304050),
    fg: Color::from_hex(0xe8ecf0),
    cursor: None,
    selection: Some(Color::from_hex(0xd04040)),
    line_highlight: Some(Color::from_hex(0x203040)),
    gutter: Some(Color::from_hex(0x556575)),
    statusbar_bg: Some(Color::from_hex(0x102030)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x8090a0)),
    keyword: Some(Color::from_hex(0x6699d0)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x70d080)),
    r#type: Some(Color::from_hex(0x8cd0d3)),
    constant: Some(Color::from_hex(0xff6070)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0x304050)),
    orange: None,
    yellow: Some(Color::from_hex(0xecad2b)),
    green: None,
    cyan: Some(Color::from_hex(0x8cd0d3)),
    blue: None,
    purple: Some(Color::from_hex(0x6699d0)),
    magenta: None,
};
