//! behelit color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// behelit
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "behelit",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x101010),
    fg: Color::from_hex(0x5fff5f),
    cursor: Some(Color::from_hex(0x5fff5f)),
    selection: Some(Color::from_hex(0x1c1c1c)),
    line_highlight: Some(Color::from_hex(0x1c1c1c)),
    gutter: Some(Color::from_hex(0x5f87af)),
    statusbar_bg: Some(Color::from_hex(0x1c1c1c)),
    statusbar_fg: Some(Color::from_hex(0x5f5faf)),
    comment: Some(Color::from_hex(0x585858)),
    keyword: Some(Color::from_hex(0xd7005f)),
    string: Some(Color::from_hex(0xffff87)),
    function: Some(Color::from_hex(0xaf87ff)),
    variable: Some(Color::from_hex(0x5f87d7)),
    r#type: Some(Color::from_hex(0x5f87d7)),
    constant: Some(Color::from_hex(0xaf87ff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xd7005f)),
    warning: Some(Color::from_hex(0xff5f5f)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd7005f)),
    orange: None,
    yellow: Some(Color::from_hex(0xff5f5f)),
    green: Some(Color::from_hex(0xffff87)),
    cyan: Some(Color::from_hex(0x5f87d7)),
    blue: Some(Color::from_hex(0xaf87ff)),
    purple: Some(Color::from_hex(0xd7005f)),
    magenta: Some(Color::from_hex(0x87ff5f)),
};
