//! benlight color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// benlight
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "benlight",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x141414),
    fg: Color::from_hex(0xf8f8f8),
    cursor: Some(Color::from_hex(0xa7a7a7)),
    selection: Some(Color::from_hex(0x3c4043)),
    line_highlight: Some(Color::from_hex(0x2b2b2b)),
    gutter: Some(Color::from_hex(0x868686)),
    statusbar_bg: Some(Color::from_hex(0x565656)),
    statusbar_fg: Some(Color::from_hex(0xf8f8f8)),
    comment: Some(Color::from_hex(0x5f5a60)),
    keyword: Some(Color::from_hex(0xcda869)),
    string: Some(Color::from_hex(0x8f9d6a)),
    function: Some(Color::from_hex(0x9b703f)),
    variable: Some(Color::from_hex(0xf9ee98)),
    r#type: Some(Color::from_hex(0x9b703f)),
    constant: Some(Color::from_hex(0xcf6a4c)),
    operator: Some(Color::from_hex(0xcda869)),
    tag: Some(Color::from_hex(0x9b703f)),
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xf8f8f8)),
    green: Some(Color::from_hex(0x8f9d6a)),
    cyan: Some(Color::from_hex(0x9b703f)),
    blue: Some(Color::from_hex(0x9b703f)),
    purple: Some(Color::from_hex(0xcda869)),
    magenta: Some(Color::from_hex(0xcda869)),
};
