//! blackboard color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// blackboard
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "blackboard",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x090b18),
    fg: Color::from_hex(0xeeeeee),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: Some(Color::from_hex(0x333333)),
    statusbar_bg: Some(Color::from_hex(0xc2bfa5)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x585858)),
    keyword: Some(Color::from_hex(0xff6600)),
    string: Some(Color::from_hex(0x99ec5c)),
    function: Some(Color::from_hex(0xffde00)),
    variable: Some(Color::from_hex(0xff9900)),
    r#type: Some(Color::from_hex(0x61c3fe)),
    constant: Some(Color::from_hex(0xcbfe29)),
    operator: Some(Color::from_hex(0xff9900)),
    tag: None,
    error: Some(Color::from_hex(0x990000)),
    warning: Some(Color::from_hex(0x990000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x990000)),
    orange: None,
    yellow: Some(Color::from_hex(0x990000)),
    green: Some(Color::from_hex(0x99ec5c)),
    cyan: Some(Color::from_hex(0x61c3fe)),
    blue: Some(Color::from_hex(0xffde00)),
    purple: Some(Color::from_hex(0xff6600)),
    magenta: None,
};
