//! blacklight color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// blacklight
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("blacklight"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x262626),
    fg: Color::from_hex(0x00afff),
    cursor: Some(Color::from_hex(0x00ff5f)),
    selection: None,
    line_highlight: None,
    gutter: Some(Color::from_hex(0x808000)),
    statusbar_bg: Some(Color::from_hex(0xc2bfa5)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0xc6c6c6)),
    keyword: Some(Color::from_hex(0xffff87)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x00ff00)),
    r#type: Some(Color::from_hex(0xafffff)),
    constant: Some(Color::from_hex(0xd700ff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xc0c0c0)),
    warning: Some(Color::from_hex(0x800000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xc0c0c0)),
    orange: None,
    yellow: Some(Color::from_hex(0x800000)),
    green: None,
    cyan: Some(Color::from_hex(0xafffff)),
    blue: None,
    purple: Some(Color::from_hex(0xffff87)),
    magenta: Some(Color::from_hex(0xd7ff00)),
};
