//! blue color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// blue
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "blue",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000087),
    fg: Color::from_hex(0xffd700),
    cursor: Some(Color::from_hex(0x00ff00)),
    selection: Some(Color::from_hex(0x008787)),
    line_highlight: Some(Color::from_hex(0x005faf)),
    gutter: Some(Color::from_hex(0x5fffff)),
    statusbar_bg: Some(Color::from_hex(0x5fffff)),
    statusbar_fg: Some(Color::from_hex(0x000087)),
    comment: Some(Color::from_hex(0x878787)),
    keyword: Some(Color::from_hex(0xffffff)),
    string: Some(Color::from_hex(0x5fffff)),
    function: Some(Color::from_hex(0xbcbcbc)),
    variable: Some(Color::from_hex(0xbcbcbc)),
    r#type: Some(Color::from_hex(0xffa500)),
    constant: Some(Color::from_hex(0x5fffff)),
    operator: Some(Color::from_hex(0xffa500)),
    tag: Some(Color::from_hex(0xd787d7)),
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xd787d7)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xd787d7)),
    green: Some(Color::from_hex(0x5fffff)),
    cyan: Some(Color::from_hex(0xffa500)),
    blue: Some(Color::from_hex(0xbcbcbc)),
    purple: Some(Color::from_hex(0xffffff)),
    magenta: Some(Color::from_hex(0x00ff00)),
};
