//! nes color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// nes
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "nes",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x2a2a2a),
    fg: Color::from_hex(0xdddddd),
    cursor: Some(Color::from_hex(0xcccccc)),
    selection: Some(Color::from_hex(0xccff99)),
    line_highlight: Some(Color::from_hex(0x1a1a1a)),
    gutter: Some(Color::from_hex(0x555555)),
    statusbar_bg: Some(Color::from_hex(0x000044)),
    statusbar_fg: Some(Color::from_hex(0x9999ff)),
    comment: Some(Color::from_hex(0xbbdd77)),
    keyword: Some(Color::from_hex(0xffffff)),
    string: Some(Color::from_hex(0xdddddd)),
    function: Some(Color::from_hex(0xcccccc)),
    variable: Some(Color::from_hex(0xcccccc)),
    r#type: Some(Color::from_hex(0xcccccc)),
    constant: Some(Color::from_hex(0xffffff)),
    operator: Some(Color::from_hex(0x00bbff)),
    tag: None,
    error: Some(Color::from_hex(0x2a2a2a)),
    warning: Some(Color::from_hex(0x2a2a2a)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x2a2a2a)),
    orange: None,
    yellow: Some(Color::from_hex(0x2a2a2a)),
    green: Some(Color::from_hex(0xdddddd)),
    cyan: Some(Color::from_hex(0xcccccc)),
    blue: Some(Color::from_hex(0xcccccc)),
    purple: Some(Color::from_hex(0xffffff)),
    magenta: Some(Color::from_hex(0xcccc99)),
};
