//! blueprint color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// blueprint
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "blueprint",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x0e4072),
    fg: Color::from_hex(0xcccccc),
    cursor: Some(Color::from_hex(0xffaf38)),
    selection: None,
    line_highlight: None,
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x80a0ff)),
    keyword: None,
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x40ffff)),
    r#type: None,
    constant: Some(Color::from_hex(0xffa0a0)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: None,
    green: None,
    cyan: None,
    blue: None,
    purple: None,
    magenta: Some(Color::from_hex(0x999999)),
};
