//! bluish color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// bluish
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "bluish",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x101848),
    fg: Color::from_hex(0xffff00),
    cursor: None,
    selection: Some(Color::from_hex(0xffffff)),
    line_highlight: Some(Color::from_hex(0x282850)),
    gutter: Some(Color::from_hex(0xbcbcbc)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x00d7af)),
    keyword: Some(Color::from_hex(0xeeeeee)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xafff00)),
    r#type: Some(Color::from_hex(0x87d7ff)),
    constant: Some(Color::from_hex(0xd7ffff)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xeeeeee)),
    green: None,
    cyan: Some(Color::from_hex(0x87d7ff)),
    blue: None,
    purple: Some(Color::from_hex(0xeeeeee)),
    magenta: None,
};
