//! bubblegum-256-dark color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// bubblegum-256-dark
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "bubblegum-256-dark",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x262626),
    fg: Color::from_hex(0xb2b2b2),
    cursor: None,
    selection: Some(Color::from_hex(0x87d7ff)),
    line_highlight: Some(Color::from_hex(0x3a3a3a)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0x3a3a3a)),
    statusbar_fg: Some(Color::from_hex(0xb2b2b2)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0x87afd7)),
    string: Some(Color::from_hex(0xd7d7af)),
    function: Some(Color::from_hex(0xd7afd7)),
    variable: Some(Color::from_hex(0xd7afd7)),
    r#type: Some(Color::from_hex(0xafafd7)),
    constant: Some(Color::from_hex(0xd7d787)),
    operator: Some(Color::from_hex(0x87afd7)),
    tag: Some(Color::from_hex(0xd78787)),
    error: Some(Color::from_hex(0xff8787)),
    warning: Some(Color::from_hex(0xaf87d7)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff8787)),
    orange: None,
    yellow: Some(Color::from_hex(0xaf87d7)),
    green: Some(Color::from_hex(0xd7d7af)),
    cyan: Some(Color::from_hex(0xafafd7)),
    blue: Some(Color::from_hex(0xd7afd7)),
    purple: Some(Color::from_hex(0x87afd7)),
    magenta: Some(Color::from_hex(0xafd787)),
};
