//! bubblegum color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// bubblegum
///
/// Variant: Light
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("bubblegum"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x626262),
    cursor: None,
    selection: Some(Color::from_hex(0x005f87)),
    line_highlight: Some(Color::from_hex(0xe4e4e4)),
    gutter: Some(Color::from_hex(0x949494)),
    statusbar_bg: Some(Color::from_hex(0xe4e4e4)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x949494)),
    keyword: Some(Color::from_hex(0x0087d7)),
    string: Some(Color::from_hex(0x87875f)),
    function: Some(Color::from_hex(0xaf5faf)),
    variable: Some(Color::from_hex(0xaf5faf)),
    r#type: Some(Color::from_hex(0x5f5faf)),
    constant: Some(Color::from_hex(0x5f8700)),
    operator: Some(Color::from_hex(0x0087d7)),
    tag: Some(Color::from_hex(0xd75f5f)),
    error: Some(Color::from_hex(0xff005f)),
    warning: Some(Color::from_hex(0xaf5fd7)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff005f)),
    orange: None,
    yellow: Some(Color::from_hex(0xaf5fd7)),
    green: Some(Color::from_hex(0x87875f)),
    cyan: Some(Color::from_hex(0x5f5faf)),
    blue: Some(Color::from_hex(0xaf5faf)),
    purple: Some(Color::from_hex(0x0087d7)),
    magenta: Some(Color::from_hex(0x005f00)),
};
