//! burnttoast256 color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// burnttoast256
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("burnttoast256"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xffaf00)),
    selection: Some(Color::from_hex(0xafd7ff)),
    line_highlight: Some(Color::from_hex(0x262626)),
    gutter: Some(Color::from_hex(0x7f7f7f)),
    statusbar_bg: Some(Color::from_hex(0x4e4e4e)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x00af87)),
    keyword: Some(Color::from_hex(0x5fafff)),
    string: Some(Color::from_hex(0xffafaf)),
    function: None,
    variable: Some(Color::from_hex(0xaf5fd7)),
    r#type: Some(Color::from_hex(0xafafd7)),
    constant: Some(Color::from_hex(0xffff5f)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xd78787)),
    green: Some(Color::from_hex(0xffafaf)),
    cyan: Some(Color::from_hex(0xafafd7)),
    blue: None,
    purple: Some(Color::from_hex(0x5fafff)),
    magenta: Some(Color::from_hex(0xafd787)),
};
