//! busybee color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// busybee
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "busybee",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x202020),
    fg: Color::from_hex(0xe2e2e5),
    cursor: Some(Color::from_hex(0x626262)),
    selection: Some(Color::from_hex(0x3c414c)),
    line_highlight: Some(Color::from_hex(0x202020)),
    gutter: Some(Color::from_hex(0x303030)),
    statusbar_bg: Some(Color::from_hex(0x303030)),
    statusbar_fg: Some(Color::from_hex(0xd3d3d5)),
    comment: Some(Color::from_hex(0x3f3f3f)),
    keyword: Some(Color::from_hex(0xff9800)),
    string: Some(Color::from_hex(0x606060)),
    function: Some(Color::from_hex(0xffff00)),
    variable: Some(Color::from_hex(0xb1d631)),
    r#type: Some(Color::from_hex(0x7e8aa2)),
    constant: Some(Color::from_hex(0xff9800)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xff9800)),
    green: Some(Color::from_hex(0x606060)),
    cyan: Some(Color::from_hex(0x7e8aa2)),
    blue: Some(Color::from_hex(0xffff00)),
    purple: Some(Color::from_hex(0xff9800)),
    magenta: Some(Color::from_hex(0xfaf4c6)),
};
