//! C64 color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// C64
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "C64",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x4242c6),
    fg: Color::from_hex(0xcecece),
    cursor: Some(Color::from_hex(0x9c9cf7)),
    selection: Some(Color::from_hex(0x7b7b7b)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x4242c6)),
    statusbar_bg: Some(Color::from_hex(0x9c9cf7)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0xa5ffa5)),
    keyword: Some(Color::from_hex(0xff9c9c)),
    string: Some(Color::from_hex(0x73f7f7)),
    function: Some(Color::from_hex(0xffffff)),
    variable: Some(Color::from_hex(0xffffff)),
    r#type: Some(Color::from_hex(0xffffff)),
    constant: Some(Color::from_hex(0xff9c9c)),
    operator: Some(Color::from_hex(0xffffff)),
    tag: None,
    error: Some(Color::from_hex(0x000000)),
    warning: Some(Color::from_hex(0x000000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x000000)),
    orange: None,
    yellow: Some(Color::from_hex(0x000000)),
    green: Some(Color::from_hex(0x73f7f7)),
    cyan: Some(Color::from_hex(0xffffff)),
    blue: Some(Color::from_hex(0xffffff)),
    purple: Some(Color::from_hex(0xff9c9c)),
    magenta: Some(Color::from_hex(0xffffff)),
};
