//! candycode color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// candycode
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("candycode"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x050505),
    fg: Color::from_hex(0xffffff),
    cursor: Some(Color::from_hex(0xffff99)),
    selection: Some(Color::from_hex(0x606070)),
    line_highlight: Some(Color::from_hex(0x1b1b1b)),
    gutter: Some(Color::from_hex(0x928c75)),
    statusbar_bg: Some(Color::from_hex(0xc2bfa5)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xff9922)),
    keyword: Some(Color::from_hex(0x66d077)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xeecc44)),
    r#type: Some(Color::from_hex(0x4093cc)),
    constant: Some(Color::from_hex(0xff6050)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xccae22)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xccae22)),
    green: Some(Color::from_hex(0xffffff)),
    cyan: Some(Color::from_hex(0x4093cc)),
    blue: None,
    purple: Some(Color::from_hex(0x66d077)),
    magenta: Some(Color::from_hex(0xbb88dd)),
};
