//! chlordane color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// chlordane
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "chlordane",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0x55af66),
    cursor: Some(Color::from_hex(0x77dd88)),
    selection: Some(Color::from_hex(0x448844)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x446644)),
    statusbar_bg: Some(Color::from_hex(0x447f55)),
    statusbar_fg: Some(Color::from_hex(0x88ee99)),
    comment: Some(Color::from_hex(0x446644)),
    keyword: Some(Color::from_hex(0x88ee99)),
    string: Some(Color::from_hex(0x77dd88)),
    function: Some(Color::from_hex(0x77dd88)),
    variable: Some(Color::from_hex(0x77dd88)),
    r#type: Some(Color::from_hex(0x77dd88)),
    constant: Some(Color::from_hex(0x88ee99)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xee1111)),
    warning: Some(Color::from_hex(0x77dd88)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xee1111)),
    orange: None,
    yellow: Some(Color::from_hex(0x77dd88)),
    green: Some(Color::from_hex(0x77dd88)),
    cyan: Some(Color::from_hex(0x77dd88)),
    blue: Some(Color::from_hex(0x77dd88)),
    purple: Some(Color::from_hex(0x88ee99)),
    magenta: Some(Color::from_hex(0x77dd88)),
};
