//! cool color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// cool
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("cool"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x102040),
    fg: Color::from_hex(0x77bbff),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x112233)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0xffffff)),
    statusbar_bg: Some(Color::from_hex(0x553333)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0xeeeeee)),
    keyword: Some(Color::from_hex(0xff8080)),
    string: Some(Color::from_hex(0x99ffaa)),
    function: Some(Color::from_hex(0xdddddd)),
    variable: None,
    r#type: Some(Color::from_hex(0xffffff)),
    constant: None,
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xccaa55)),
    green: Some(Color::from_hex(0x99ffaa)),
    cyan: Some(Color::from_hex(0xffffff)),
    blue: Some(Color::from_hex(0xdddddd)),
    purple: Some(Color::from_hex(0xff8080)),
    magenta: Some(Color::from_hex(0x77bbff)),
};
