//! darker-robin color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// darker-robin
///
/// Variant: Dark
/// Contrast: Low
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "darker-robin",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Low,
    bg: Color::from_hex(0x101010),
    fg: Color::from_hex(0x807057),
    cursor: None,
    selection: None,
    line_highlight: None,
    gutter: Some(Color::from_hex(0x909000)),
    statusbar_bg: Some(Color::from_hex(0x606050)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x606099)),
    keyword: Some(Color::from_hex(0xb05a50)),
    string: Some(Color::from_hex(0xa0644d)),
    function: None,
    variable: Some(Color::from_hex(0x70b970)),
    r#type: Some(Color::from_hex(0x70b970)),
    constant: Some(Color::from_hex(0x8da0a0)),
    operator: Some(Color::from_hex(0xc0ba98)),
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xa0644d)),
    cyan: Some(Color::from_hex(0x70b970)),
    blue: None,
    purple: Some(Color::from_hex(0xb05a50)),
    magenta: Some(Color::from_hex(0x70b970)),
};
