//! darkbone color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// darkbone
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "darkbone",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xa0a0c0),
    cursor: Some(Color::from_hex(0xa0a0c0)),
    selection: Some(Color::from_hex(0x707090)),
    line_highlight: Some(Color::from_hex(0x303050)),
    gutter: Some(Color::from_hex(0x606080)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0xc0c0ff)),
    comment: Some(Color::from_hex(0x606080)),
    keyword: Some(Color::from_hex(0x8090f0)),
    string: Some(Color::from_hex(0xd0e080)),
    function: Some(Color::from_hex(0xf0b040)),
    variable: Some(Color::from_hex(0x8090f0)),
    r#type: Some(Color::from_hex(0xe0e0ff)),
    constant: Some(Color::from_hex(0xf0a0b0)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xee1111)),
    warning: Some(Color::from_hex(0xee1111)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xee1111)),
    orange: None,
    yellow: Some(Color::from_hex(0xee1111)),
    green: Some(Color::from_hex(0xd0e080)),
    cyan: Some(Color::from_hex(0xe0e0ff)),
    blue: Some(Color::from_hex(0xf0b040)),
    purple: Some(Color::from_hex(0x8090f0)),
    magenta: Some(Color::from_hex(0xe0e0ff)),
};
