//! despacio color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// despacio
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "despacio",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x080808),
    fg: Color::from_hex(0xdfdfdf),
    cursor: None,
    selection: Some(Color::from_hex(0x5f8787)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x4e4e4e)),
    statusbar_bg: Some(Color::from_hex(0x121212)),
    statusbar_fg: Some(Color::from_hex(0xeeeeee)),
    comment: Some(Color::from_hex(0x4e4e4e)),
    keyword: Some(Color::from_hex(0xaf875f)),
    string: Some(Color::from_hex(0xffffdf)),
    function: Some(Color::from_hex(0xffdfaf)),
    variable: Some(Color::from_hex(0xffdfaf)),
    r#type: Some(Color::from_hex(0xff875f)),
    constant: Some(Color::from_hex(0xd75f00)),
    operator: Some(Color::from_hex(0xdfaf87)),
    tag: None,
    error: Some(Color::from_hex(0xd75f5f)),
    warning: Some(Color::from_hex(0xff875f)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd75f5f)),
    orange: None,
    yellow: Some(Color::from_hex(0xff875f)),
    green: Some(Color::from_hex(0xffffdf)),
    cyan: Some(Color::from_hex(0xff875f)),
    blue: Some(Color::from_hex(0xffdfaf)),
    purple: Some(Color::from_hex(0xaf875f)),
    magenta: Some(Color::from_hex(0xff875f)),
};
