//! deveiate color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// deveiate
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("deveiate"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x00000f),
    fg: Color::from_hex(0xf6dfb2),
    cursor: None,
    selection: Some(Color::from_hex(0x001632)),
    line_highlight: Some(Color::from_hex(0x171520)),
    gutter: Some(Color::from_hex(0x333333)),
    statusbar_bg: Some(Color::from_hex(0xd4d2cb)),
    statusbar_fg: Some(Color::from_hex(0x292087)),
    comment: Some(Color::from_hex(0xa82419)),
    keyword: Some(Color::from_hex(0x00cbcd)),
    string: Some(Color::from_hex(0xda8d53)),
    function: Some(Color::from_hex(0x9b859d)),
    variable: Some(Color::from_hex(0x9bda8b)),
    r#type: None,
    constant: Some(Color::from_hex(0x76a3d7)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf8f8f8)),
    orange: None,
    yellow: Some(Color::from_hex(0xda8d53)),
    green: Some(Color::from_hex(0xda8d53)),
    cyan: None,
    blue: Some(Color::from_hex(0x9b859d)),
    purple: Some(Color::from_hex(0x00cbcd)),
    magenta: Some(Color::from_hex(0x00cbcd)),
};
