//! diokai color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// diokai
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("diokai"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x272822),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xd0d0d0)),
    selection: Some(Color::from_hex(0x444444)),
    line_highlight: Some(Color::from_hex(0x32322f)),
    gutter: Some(Color::from_hex(0x585858)),
    statusbar_bg: Some(Color::from_hex(0x444444)),
    statusbar_fg: Some(Color::from_hex(0xffffd7)),
    comment: Some(Color::from_hex(0x875f87)),
    keyword: Some(Color::from_hex(0xffd75f)),
    string: Some(Color::from_hex(0xafaf87)),
    function: Some(Color::from_hex(0x878787)),
    variable: Some(Color::from_hex(0xd7ff87)),
    r#type: Some(Color::from_hex(0x87af5f)),
    constant: Some(Color::from_hex(0xd7875f)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xff2026)),
    warning: Some(Color::from_hex(0xff5f55)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff2026)),
    orange: None,
    yellow: Some(Color::from_hex(0xff5f55)),
    green: Some(Color::from_hex(0xafaf87)),
    cyan: Some(Color::from_hex(0x87af5f)),
    blue: Some(Color::from_hex(0x878787)),
    purple: Some(Color::from_hex(0xffd75f)),
    magenta: Some(Color::from_hex(0xd7005f)),
};
