//! dw_yellow color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// dw_yellow
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "dw_yellow",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0x444444)),
    selection: Some(Color::from_hex(0xdddd00)),
    line_highlight: Some(Color::from_hex(0x181800)),
    gutter: Some(Color::from_hex(0x888800)),
    statusbar_bg: Some(Color::from_hex(0xffff00)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x696969)),
    keyword: Some(Color::from_hex(0xffff00)),
    string: Some(Color::from_hex(0xbbbb00)),
    function: Some(Color::from_hex(0xffff00)),
    variable: Some(Color::from_hex(0xcccc00)),
    r#type: Some(Color::from_hex(0xffffff)),
    constant: Some(Color::from_hex(0xffff00)),
    operator: Some(Color::from_hex(0x696969)),
    tag: None,
    error: Some(Color::from_hex(0x000000)),
    warning: Some(Color::from_hex(0x000000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x000000)),
    orange: None,
    yellow: Some(Color::from_hex(0x000000)),
    green: Some(Color::from_hex(0xbbbb00)),
    cyan: Some(Color::from_hex(0xffffff)),
    blue: Some(Color::from_hex(0xffff00)),
    purple: Some(Color::from_hex(0xffff00)),
    magenta: Some(Color::from_hex(0xffffff)),
};
