//! earth color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// earth
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("earth"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0x99cc99),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0xd86020)),
    selection: Some(Color::from_hex(0x6060d0)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x669966)),
    statusbar_bg: Some(Color::from_hex(0xd0d0e0)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x996666)),
    keyword: Some(Color::from_hex(0xcc9900)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x669966)),
    r#type: Some(Color::from_hex(0x993300)),
    constant: Some(Color::from_hex(0x990066)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x60ff60)),
    cyan: Some(Color::from_hex(0x993300)),
    blue: None,
    purple: Some(Color::from_hex(0xcc9900)),
    magenta: Some(Color::from_hex(0x009900)),
};
