//! Edo_sea color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Edo_sea
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "Edo_sea",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x303060),
    fg: Color::from_hex(0xf0f0f8),
    cursor: Some(Color::from_hex(0xd86020)),
    selection: Some(Color::from_hex(0x6060f0)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x7070e8)),
    statusbar_bg: Some(Color::from_hex(0xd0d0e0)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xb0b0b8)),
    keyword: Some(Color::from_hex(0xf0d050)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xd0c0f0)),
    r#type: Some(Color::from_hex(0x40f080)),
    constant: Some(Color::from_hex(0x50f0d0)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xf0f0f0)),
    warning: Some(Color::from_hex(0xf0f0f0)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf0f0f0)),
    orange: None,
    yellow: Some(Color::from_hex(0xf0f0f0)),
    green: Some(Color::from_hex(0x60f060)),
    cyan: Some(Color::from_hex(0x40f080)),
    blue: None,
    purple: Some(Color::from_hex(0xf0d050)),
    magenta: Some(Color::from_hex(0xf0b0f0)),
};
