//! ego color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// ego
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "ego",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x18191f),
    fg: Color::from_hex(0xf6f6f6),
    cursor: Some(Color::from_hex(0x8da1a1)),
    selection: Some(Color::from_hex(0xffffff)),
    line_highlight: Some(Color::from_hex(0x3d4646)),
    gutter: Some(Color::from_hex(0x686868)),
    statusbar_bg: Some(Color::from_hex(0x484848)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xc8f482)),
    keyword: Some(Color::from_hex(0xc67c48)),
    string: Some(Color::from_hex(0xe38081)),
    function: Some(Color::from_hex(0x82c057)),
    variable: Some(Color::from_hex(0x82c057)),
    r#type: Some(Color::from_hex(0x82c057)),
    constant: Some(Color::from_hex(0x95d5f1)),
    operator: Some(Color::from_hex(0xf6da7b)),
    tag: Some(Color::from_hex(0x55747c)),
    error: Some(Color::from_hex(0xffff99)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffff99)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0xe38081)),
    cyan: Some(Color::from_hex(0x82c057)),
    blue: Some(Color::from_hex(0x82c057)),
    purple: Some(Color::from_hex(0xc67c48)),
    magenta: Some(Color::from_hex(0xc67c48)),
};
