//! evening color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// evening
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "evening",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x333333),
    fg: Color::from_hex(0xffffff),
    cursor: Some(Color::from_hex(0x00ff00)),
    selection: Some(Color::from_hex(0x999999)),
    line_highlight: Some(Color::from_hex(0x666666)),
    gutter: Some(Color::from_hex(0xffff00)),
    statusbar_bg: Some(Color::from_hex(0xffffff)),
    statusbar_fg: Some(Color::from_hex(0x333333)),
    comment: Some(Color::from_hex(0x80a0ff)),
    keyword: Some(Color::from_hex(0xffff60)),
    string: Some(Color::from_hex(0xffa0a0)),
    function: Some(Color::from_hex(0x00ffff)),
    variable: Some(Color::from_hex(0x00ffff)),
    r#type: Some(Color::from_hex(0x00ff00)),
    constant: Some(Color::from_hex(0xffa0a0)),
    operator: Some(Color::from_hex(0xffff60)),
    tag: Some(Color::from_hex(0xffa500)),
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0xffa0a0)),
    cyan: Some(Color::from_hex(0x00ff00)),
    blue: Some(Color::from_hex(0x00ffff)),
    purple: Some(Color::from_hex(0xffff60)),
    magenta: Some(Color::from_hex(0xff80ff)),
};
