//! evokai color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// evokai
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "evokai",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1b1b13),
    fg: Color::from_hex(0xefefef),
    cursor: Some(Color::from_hex(0xff027f)),
    selection: Some(Color::from_hex(0xefefef)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x444444)),
    statusbar_bg: Some(Color::from_hex(0x222222)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x75715e)),
    keyword: Some(Color::from_hex(0xff027f)),
    string: Some(Color::from_hex(0xfff600)),
    function: Some(Color::from_hex(0x00d5dd)),
    variable: Some(Color::from_hex(0x00d5dd)),
    r#type: Some(Color::from_hex(0x3cff00)),
    constant: Some(Color::from_hex(0x99f6fa)),
    operator: Some(Color::from_hex(0xff027f)),
    tag: Some(Color::from_hex(0x36a6ff)),
    error: Some(Color::from_hex(0xe60000)),
    warning: Some(Color::from_hex(0xfff600)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xe60000)),
    orange: None,
    yellow: Some(Color::from_hex(0xfff600)),
    green: Some(Color::from_hex(0xfff600)),
    cyan: Some(Color::from_hex(0x3cff00)),
    blue: Some(Color::from_hex(0x00d5dd)),
    purple: Some(Color::from_hex(0xff027f)),
    magenta: Some(Color::from_hex(0x75715e)),
};
