//! flatlandia color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// flatlandia
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "flatlandia",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x26292c),
    fg: Color::from_hex(0xe0e0e0),
    cursor: Some(Color::from_hex(0xcceeff)),
    selection: Some(Color::from_hex(0x414549)),
    line_highlight: Some(Color::from_hex(0x2d3033)),
    gutter: Some(Color::from_hex(0x515253)),
    statusbar_bg: Some(Color::from_hex(0x292c2f)),
    statusbar_fg: Some(Color::from_hex(0xf8f8f8)),
    comment: Some(Color::from_hex(0x60666b)),
    keyword: Some(Color::from_hex(0xfa9a4b)),
    string: Some(Color::from_hex(0x9298a1)),
    function: Some(Color::from_hex(0x72aaca)),
    variable: Some(Color::from_hex(0xf6f080)),
    r#type: Some(Color::from_hex(0x8ac8db)),
    constant: Some(Color::from_hex(0xb8d977)),
    operator: Some(Color::from_hex(0xfa9a4b)),
    tag: Some(Color::from_hex(0x72aaca)),
    error: Some(Color::from_hex(0xf8f8f8)),
    warning: Some(Color::from_hex(0xf8f8f8)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf8f8f8)),
    orange: None,
    yellow: Some(Color::from_hex(0xf8f8f8)),
    green: Some(Color::from_hex(0x9298a1)),
    cyan: Some(Color::from_hex(0x8ac8db)),
    blue: Some(Color::from_hex(0x72aaca)),
    purple: Some(Color::from_hex(0xfa9a4b)),
    magenta: Some(Color::from_hex(0xfa9a4b)),
};
