//! freya color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// freya
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("freya"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x2a2a2a),
    fg: Color::from_hex(0xdcdccc),
    cursor: None,
    selection: Some(Color::from_hex(0x5f5f5f)),
    line_highlight: Some(Color::from_hex(0x3f3f3f)),
    gutter: Some(Color::from_hex(0x9f8f80)),
    statusbar_bg: Some(Color::from_hex(0x736559)),
    statusbar_fg: Some(Color::from_hex(0xf7f7f1)),
    comment: Some(Color::from_hex(0xc2b680)),
    keyword: Some(Color::from_hex(0xe0af91)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xdabfa5)),
    r#type: Some(Color::from_hex(0xdabfa5)),
    constant: Some(Color::from_hex(0xafe091)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xf07070)),
    warning: Some(Color::from_hex(0xf07070)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf07070)),
    orange: None,
    yellow: Some(Color::from_hex(0xf07070)),
    green: None,
    cyan: Some(Color::from_hex(0xdabfa5)),
    blue: None,
    purple: Some(Color::from_hex(0xe0af91)),
    magenta: Some(Color::from_hex(0xc2aed0)),
};
