//! gentooish color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// gentooish
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("gentooish"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x191919),
    fg: Color::from_hex(0xcccccc),
    cursor: Some(Color::from_hex(0x8bff95)),
    selection: Some(Color::from_hex(0x6e4287)),
    line_highlight: Some(Color::from_hex(0x222222)),
    gutter: Some(Color::from_hex(0xbbbbbb)),
    statusbar_bg: Some(Color::from_hex(0x333333)),
    statusbar_fg: Some(Color::from_hex(0xcccccc)),
    comment: Some(Color::from_hex(0x666666)),
    keyword: Some(Color::from_hex(0x4cd169)),
    string: Some(Color::from_hex(0x5dff9e)),
    function: None,
    variable: Some(Color::from_hex(0x4cbbd1)),
    r#type: Some(Color::from_hex(0xc476f1)),
    constant: Some(Color::from_hex(0xb8bb00)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xcccccc)),
    warning: Some(Color::from_hex(0xcccccc)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xcccccc)),
    orange: None,
    yellow: Some(Color::from_hex(0xcccccc)),
    green: Some(Color::from_hex(0x5dff9e)),
    cyan: Some(Color::from_hex(0xc476f1)),
    blue: None,
    purple: Some(Color::from_hex(0x4cd169)),
    magenta: Some(Color::from_hex(0x9a383a)),
};
