//! getafe color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// getafe
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "getafe",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1b1d1e),
    fg: Color::from_hex(0xf8fff9),
    cursor: Some(Color::from_hex(0xff358b)),
    selection: Some(Color::from_hex(0xff358b)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x5a7085)),
    statusbar_bg: Some(Color::from_hex(0x01b0f0)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x5a7085)),
    keyword: Some(Color::from_hex(0x69c3ff)),
    string: Some(Color::from_hex(0xaeee00)),
    function: Some(Color::from_hex(0x01b0f0)),
    variable: Some(Color::from_hex(0x01b0f0)),
    r#type: Some(Color::from_hex(0xaeee00)),
    constant: Some(Color::from_hex(0xb994ff)),
    operator: Some(Color::from_hex(0x69c3ff)),
    tag: Some(Color::from_hex(0xf8fff9)),
    error: Some(Color::from_hex(0x000000)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x000000)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0xaeee00)),
    cyan: Some(Color::from_hex(0xaeee00)),
    blue: Some(Color::from_hex(0x01b0f0)),
    purple: Some(Color::from_hex(0x69c3ff)),
    magenta: Some(Color::from_hex(0xf8fff9)),
};
