//! gravity color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// gravity
///
/// Variant: Light
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "gravity",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf0f0f0),
    fg: Color::from_hex(0x404040),
    cursor: None,
    selection: Some(Color::from_hex(0xa00000)),
    line_highlight: Some(Color::from_hex(0xc0d0e0)),
    gutter: Some(Color::from_hex(0xffffff)),
    statusbar_bg: Some(Color::from_hex(0x2a3a57)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0x909090)),
    keyword: Some(Color::from_hex(0x2a9400)),
    string: Some(Color::from_hex(0xc40020)),
    function: Some(Color::from_hex(0xd8008e)),
    variable: Some(Color::from_hex(0x7800c4)),
    r#type: Some(Color::from_hex(0x00a0a0)),
    constant: Some(Color::from_hex(0xc40020)),
    operator: Some(Color::from_hex(0x404040)),
    tag: Some(Color::from_hex(0x007958)),
    error: None,
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0x9c9c9c)),
    orange: None,
    yellow: Some(Color::from_hex(0x007958)),
    green: Some(Color::from_hex(0xc40020)),
    cyan: Some(Color::from_hex(0x00a0a0)),
    blue: Some(Color::from_hex(0xd8008e)),
    purple: Some(Color::from_hex(0x2a9400)),
    magenta: Some(Color::from_hex(0x2a9400)),
};
