//! graywh color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// graywh
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "graywh",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1c1c1c),
    fg: Color::from_hex(0xd7d7d7),
    cursor: None,
    selection: None,
    line_highlight: Some(Color::from_hex(0x303030)),
    gutter: Some(Color::from_hex(0xd7d7af)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0xafffaf)),
    keyword: Some(Color::from_hex(0x87afff)),
    string: Some(Color::from_hex(0xffafff)),
    function: Some(Color::from_hex(0xafd7ff)),
    variable: Some(Color::from_hex(0xafffff)),
    r#type: Some(Color::from_hex(0xffffaf)),
    constant: Some(Color::from_hex(0xffafaf)),
    operator: Some(Color::from_hex(0xffaf87)),
    tag: None,
    error: Some(Color::from_hex(0xd70000)),
    warning: Some(Color::from_hex(0xd7d700)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd70000)),
    orange: None,
    yellow: Some(Color::from_hex(0xd7d700)),
    green: Some(Color::from_hex(0xffafff)),
    cyan: Some(Color::from_hex(0xffffaf)),
    blue: Some(Color::from_hex(0xafd7ff)),
    purple: Some(Color::from_hex(0x87afff)),
    magenta: Some(Color::from_hex(0x5fffff)),
};
