//! highwayman color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// highwayman
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "highwayman",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xdcdccc),
    cursor: Some(Color::from_hex(0xfbde2d)),
    selection: Some(Color::from_hex(0x7f073f)),
    line_highlight: Some(Color::from_hex(0x333333)),
    gutter: Some(Color::from_hex(0x9fc59f)),
    statusbar_bg: Some(Color::from_hex(0x4c83ff)),
    statusbar_fg: Some(Color::from_hex(0x333333)),
    comment: Some(Color::from_hex(0x8b8989)),
    keyword: Some(Color::from_hex(0xfbde2d)),
    string: Some(Color::from_hex(0x61ce3c)),
    function: Some(Color::from_hex(0xff1493)),
    variable: Some(Color::from_hex(0xd8fa3c)),
    r#type: Some(Color::from_hex(0xd8fa3c)),
    constant: Some(Color::from_hex(0x4c83ff)),
    operator: Some(Color::from_hex(0xfbde2d)),
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0x61ce3c)),
    cyan: Some(Color::from_hex(0xd8fa3c)),
    blue: Some(Color::from_hex(0xff1493)),
    purple: Some(Color::from_hex(0xfbde2d)),
    magenta: Some(Color::from_hex(0x919191)),
};
