//! holokai color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// holokai
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "holokai",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xbcbcbc),
    cursor: Some(Color::from_hex(0xdadada)),
    selection: Some(Color::from_hex(0x005faf)),
    line_highlight: Some(Color::from_hex(0x080808)),
    gutter: Some(Color::from_hex(0xbcbcbc)),
    statusbar_bg: Some(Color::from_hex(0xdadada)),
    statusbar_fg: Some(Color::from_hex(0x444444)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0xffdf00)),
    string: Some(Color::from_hex(0xdfaf00)),
    function: Some(Color::from_hex(0x87d700)),
    variable: Some(Color::from_hex(0x87d700)),
    r#type: Some(Color::from_hex(0x87d700)),
    constant: Some(Color::from_hex(0xff00df)),
    operator: Some(Color::from_hex(0xffdf00)),
    tag: Some(Color::from_hex(0xffdf00)),
    error: Some(Color::from_hex(0xffafff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffafff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0xdfaf00)),
    cyan: Some(Color::from_hex(0x87d700)),
    blue: Some(Color::from_hex(0x87d700)),
    purple: Some(Color::from_hex(0xffdf00)),
    magenta: Some(Color::from_hex(0x5fafff)),
};
