//! hydrangea color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// hydrangea
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("hydrangea"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1e222c),
    fg: Color::from_hex(0xc3d0ec),
    cursor: Some(Color::from_hex(0xedf9ff)),
    selection: Some(Color::from_hex(0x373d4b)),
    line_highlight: Some(Color::from_hex(0x2a303b)),
    gutter: Some(Color::from_hex(0x474e5c)),
    statusbar_bg: Some(Color::from_hex(0x373d4b)),
    statusbar_fg: Some(Color::from_hex(0xc3d0ec)),
    comment: Some(Color::from_hex(0x474e5c)),
    keyword: Some(Color::from_hex(0x537dd5)),
    string: Some(Color::from_hex(0x36c2c2)),
    function: Some(Color::from_hex(0xedf9ff)),
    variable: Some(Color::from_hex(0xedf9ff)),
    r#type: Some(Color::from_hex(0xe242ac)),
    constant: Some(Color::from_hex(0x36c2c2)),
    operator: Some(Color::from_hex(0xe242ac)),
    tag: None,
    error: Some(Color::from_hex(0xe91e63)),
    warning: Some(Color::from_hex(0xe91e63)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xe91e63)),
    orange: None,
    yellow: Some(Color::from_hex(0xe91e63)),
    green: Some(Color::from_hex(0x36c2c2)),
    cyan: Some(Color::from_hex(0xe242ac)),
    blue: Some(Color::from_hex(0xedf9ff)),
    purple: Some(Color::from_hex(0x537dd5)),
    magenta: Some(Color::from_hex(0xceadff)),
};
