//! industry color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// industry
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "industry",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xdadada),
    cursor: Some(Color::from_hex(0xdadada)),
    selection: Some(Color::from_hex(0x6c6c6c)),
    line_highlight: Some(Color::from_hex(0x6c6c6c)),
    gutter: Some(Color::from_hex(0xffff00)),
    statusbar_bg: Some(Color::from_hex(0xdadada)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x00afaf)),
    keyword: Some(Color::from_hex(0xffffff)),
    string: None,
    function: Some(Color::from_hex(0x00ff00)),
    variable: Some(Color::from_hex(0xff00ff)),
    r#type: Some(Color::from_hex(0x00ff00)),
    constant: Some(Color::from_hex(0x00ffff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0xffffff)),
    cyan: Some(Color::from_hex(0x00ff00)),
    blue: Some(Color::from_hex(0x00ff00)),
    purple: Some(Color::from_hex(0xffffff)),
    magenta: Some(Color::from_hex(0xffff00)),
};
