//! itg_flat color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// itg_flat
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("itg_flat"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x282a31),
    fg: Color::from_hex(0xe4e4e4),
    cursor: Some(Color::from_hex(0xf0e68c)),
    selection: Some(Color::from_hex(0x6b8e23)),
    line_highlight: Some(Color::from_hex(0x404040)),
    gutter: Some(Color::from_hex(0x606a74)),
    statusbar_bg: Some(Color::from_hex(0x30323b)),
    statusbar_fg: Some(Color::from_hex(0xe0e0e0)),
    comment: Some(Color::from_hex(0x606a74)),
    keyword: Some(Color::from_hex(0xd1605e)),
    string: Some(Color::from_hex(0xddc96d)),
    function: Some(Color::from_hex(0x92e4c0)),
    variable: Some(Color::from_hex(0xe0e0e0)),
    r#type: Some(Color::from_hex(0x92e4c0)),
    constant: Some(Color::from_hex(0x92e4c0)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xe0e0e0)),
    green: Some(Color::from_hex(0xddc96d)),
    cyan: Some(Color::from_hex(0x92e4c0)),
    blue: Some(Color::from_hex(0x92e4c0)),
    purple: Some(Color::from_hex(0xd1605e)),
    magenta: Some(Color::from_hex(0xd1605e)),
};
