//! kolor color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// kolor
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "kolor",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x2e2d2b),
    fg: Color::from_hex(0xc6c6c6),
    cursor: Some(Color::from_hex(0xe2e2e2)),
    selection: Some(Color::from_hex(0x5c5c5c)),
    line_highlight: Some(Color::from_hex(0x383734)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0x9e9e9e)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0xd96e8a)),
    string: Some(Color::from_hex(0xad8788)),
    function: Some(Color::from_hex(0x88da77)),
    variable: Some(Color::from_hex(0x75d7d8)),
    r#type: Some(Color::from_hex(0xa080ea)),
    constant: Some(Color::from_hex(0xe6987a)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xd96e8a)),
    warning: Some(Color::from_hex(0xff5fd7)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd96e8a)),
    orange: None,
    yellow: Some(Color::from_hex(0xff5fd7)),
    green: Some(Color::from_hex(0xad8788)),
    cyan: Some(Color::from_hex(0xa080ea)),
    blue: Some(Color::from_hex(0x88da77)),
    purple: Some(Color::from_hex(0xd96e8a)),
    magenta: Some(Color::from_hex(0xdbc570)),
};
