//! kkruby color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// kkruby
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("kkruby"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x070706),
    fg: Color::from_hex(0xd1c1cf),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x5a647e)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x9e9e9e)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x76d676)),
    keyword: Some(Color::from_hex(0xd7875f)),
    string: Some(Color::from_hex(0xe6f881)),
    function: Some(Color::from_hex(0x50e7c5)),
    variable: Some(Color::from_hex(0xdfdf10)),
    r#type: Some(Color::from_hex(0xda4939)),
    constant: Some(Color::from_hex(0x4596ff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffc66d)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffc66d)),
    orange: None,
    yellow: Some(Color::from_hex(0xbb3333)),
    green: Some(Color::from_hex(0xe6f881)),
    cyan: Some(Color::from_hex(0xda4939)),
    blue: Some(Color::from_hex(0x50e7c5)),
    purple: Some(Color::from_hex(0xd7875f)),
    magenta: Some(Color::from_hex(0xcc7833)),
};
