//! lucius color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// lucius
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "lucius",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xf8f8f8),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x406090)),
    selection: Some(Color::from_hex(0xd0e0f0)),
    line_highlight: Some(Color::from_hex(0xe8e8e8)),
    gutter: Some(Color::from_hex(0x2060a0)),
    statusbar_bg: Some(Color::from_hex(0xb0c0d0)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x909090)),
    keyword: Some(Color::from_hex(0x0040a0)),
    string: Some(Color::from_hex(0x208000)),
    function: Some(Color::from_hex(0x009070)),
    variable: Some(Color::from_hex(0x009070)),
    r#type: Some(Color::from_hex(0x007090)),
    constant: Some(Color::from_hex(0x208000)),
    operator: Some(Color::from_hex(0x0040a0)),
    tag: Some(Color::from_hex(0x7020a0)),
    error: Some(Color::from_hex(0xaa0000)),
    warning: Some(Color::from_hex(0xe06020)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xaa0000)),
    orange: None,
    yellow: Some(Color::from_hex(0xe06020)),
    green: Some(Color::from_hex(0x208000)),
    cyan: Some(Color::from_hex(0x007090)),
    blue: Some(Color::from_hex(0x009070)),
    purple: Some(Color::from_hex(0x0040a0)),
    magenta: Some(Color::from_hex(0xb07000)),
};
