//! lxvc color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// lxvc
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("lxvc"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x202020),
    fg: Color::from_hex(0xe0e0e0),
    cursor: None,
    selection: Some(Color::from_hex(0x8895dd)),
    line_highlight: Some(Color::from_hex(0x34373b)),
    gutter: Some(Color::from_hex(0x818698)),
    statusbar_bg: Some(Color::from_hex(0x363946)),
    statusbar_fg: Some(Color::from_hex(0xe0e0e0)),
    comment: Some(Color::from_hex(0x636970)),
    keyword: Some(Color::from_hex(0xdbda6e)),
    string: Some(Color::from_hex(0x5dbaa9)),
    function: Some(Color::from_hex(0xa5a9af)),
    variable: Some(Color::from_hex(0x8895dd)),
    r#type: Some(Color::from_hex(0xd66b84)),
    constant: Some(Color::from_hex(0x8895dd)),
    operator: Some(Color::from_hex(0x808d9e)),
    tag: Some(Color::from_hex(0xb0a0c0)),
    error: Some(Color::from_hex(0x574b4b)),
    warning: Some(Color::from_hex(0x574b4b)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x574b4b)),
    orange: None,
    yellow: Some(Color::from_hex(0x574b4b)),
    green: Some(Color::from_hex(0x5dbaa9)),
    cyan: Some(Color::from_hex(0xd66b84)),
    blue: Some(Color::from_hex(0xa5a9af)),
    purple: Some(Color::from_hex(0xdbda6e)),
    magenta: Some(Color::from_hex(0xa5a9af)),
};
