//! mac_classic color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// mac_classic
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("mac_classic"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x3c4c72)),
    selection: Some(Color::from_hex(0xc6deff)),
    line_highlight: Some(Color::from_hex(0xf0f6ff)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0xc6deff)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x0066ff)),
    keyword: Some(Color::from_hex(0x1e39f6)),
    string: Some(Color::from_hex(0x007b22)),
    function: Some(Color::from_hex(0x0000a2)),
    variable: Some(Color::from_hex(0x1e39f6)),
    r#type: None,
    constant: Some(Color::from_hex(0xd51015)),
    operator: Some(Color::from_hex(0x1e39f6)),
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x007b22)),
    cyan: None,
    blue: Some(Color::from_hex(0x0000a2)),
    purple: Some(Color::from_hex(0x1e39f6)),
    magenta: Some(Color::from_hex(0x1e39f6)),
};
