//! macvim-light color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// macvim-light
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("macvim-light"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x333333),
    cursor: None,
    selection: Some(Color::from_hex(0x72f7ff)),
    line_highlight: Some(Color::from_hex(0xf1f5fa)),
    gutter: Some(Color::from_hex(0x888888)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x0000ff)),
    keyword: Some(Color::from_hex(0xa71d5d)),
    string: Some(Color::from_hex(0x4a708b)),
    function: None,
    variable: Some(Color::from_hex(0x458b74)),
    r#type: Some(Color::from_hex(0x009e00)),
    constant: Some(Color::from_hex(0xff8c00)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xa71d5d)),
    warning: Some(Color::from_hex(0xee2c2c)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xa71d5d)),
    orange: None,
    yellow: Some(Color::from_hex(0xee2c2c)),
    green: Some(Color::from_hex(0x4a708b)),
    cyan: Some(Color::from_hex(0x009e00)),
    blue: None,
    purple: Some(Color::from_hex(0xa71d5d)),
    magenta: Some(Color::from_hex(0x1874cd)),
};
