//! Made of Code color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// Made of Code
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "Made of Code",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x090a1b),
    fg: Color::from_hex(0xf8f8f8),
    cursor: Some(Color::from_hex(0x00ffff)),
    selection: Some(Color::from_hex(0x05448d)),
    line_highlight: Some(Color::from_hex(0x212231)),
    gutter: Some(Color::from_hex(0x81818a)),
    statusbar_bg: Some(Color::from_hex(0x4e4f5b)),
    statusbar_fg: Some(Color::from_hex(0xf8f8f8)),
    comment: Some(Color::from_hex(0xc050c2)),
    keyword: Some(Color::from_hex(0xff3854)),
    string: Some(Color::from_hex(0x8fff58)),
    function: Some(Color::from_hex(0x6fd3ff)),
    variable: Some(Color::from_hex(0x99cf50)),
    r#type: Some(Color::from_hex(0x6fd3ff)),
    constant: Some(Color::from_hex(0x0a9cff)),
    operator: Some(Color::from_hex(0xff3854)),
    tag: Some(Color::from_hex(0x6fd3ff)),
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xf8f8f8)),
    green: Some(Color::from_hex(0x8fff58)),
    cyan: Some(Color::from_hex(0x6fd3ff)),
    blue: Some(Color::from_hex(0x6fd3ff)),
    purple: Some(Color::from_hex(0xff3854)),
    magenta: Some(Color::from_hex(0xff3854)),
};
