//! materialtheme color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// materialtheme
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "materialtheme",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x263238),
    fg: Color::from_hex(0xeeeeec),
    cursor: Some(Color::from_hex(0x607d8b)),
    selection: None,
    line_highlight: Some(Color::from_hex(0x2b3940)),
    gutter: Some(Color::from_hex(0x37474f)),
    statusbar_bg: Some(Color::from_hex(0x546e7a)),
    statusbar_fg: Some(Color::from_hex(0x263238)),
    comment: Some(Color::from_hex(0x546e7a)),
    keyword: Some(Color::from_hex(0xff8a65)),
    string: None,
    function: Some(Color::from_hex(0x9bcf8d)),
    variable: Some(Color::from_hex(0xad7fa8)),
    r#type: Some(Color::from_hex(0xffb74d)),
    constant: Some(Color::from_hex(0xffd54f)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0x64b5f6)),
    green: None,
    cyan: Some(Color::from_hex(0xffb74d)),
    blue: Some(Color::from_hex(0x9bcf8d)),
    purple: Some(Color::from_hex(0xff8a65)),
    magenta: Some(Color::from_hex(0xe9ba6e)),
};
