//! Vim color themes.
//!
//! Themes parsed from [vim-colorschemes](https://github.com/flazz/vim-colorschemes)
//! and [vim/colorschemes](https://github.com/vim/colorschemes).
//! Colors extracted from `hi` (highlight) commands in `.vim` files.
//!
//! Enable with the `vim` feature flag.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::Theme;

pub mod _0x7a69_dark;
pub mod _256_grayvim;
pub mod _256_jungle;
pub mod _256_noir;
pub mod adventurous;
pub mod af;
pub mod anderson;
pub mod angr;
pub mod apprentice;
pub mod arcadia;
pub mod archery;
pub mod argonaut;
pub mod ashen;
pub mod asmanian_blood;
pub mod atom;
pub mod aurora;
pub mod autumnleaf;
pub mod babymate256;
pub mod base;
pub mod baycomb;
pub mod bayqua;
pub mod bclear;
pub mod beachcomber;
pub mod beauty256;
pub mod beekai;
pub mod behelit;
pub mod benlight;
pub mod benokai;
pub mod biogoo;
pub mod birds_of_paradise;
pub mod bitterjug;
pub mod blackboard;
pub mod blackdust;
pub mod blacklight;
pub mod blazer;
pub mod blue;
pub mod bluechia;
pub mod bluenes;
pub mod blues;
pub mod bluez;
pub mod bluish;
pub mod boa;
pub mod boltzmann;
pub mod breeze;
pub mod breezy;
pub mod brighton;
pub mod brogrammer;
pub mod bubblegum;
pub mod bubblegum_256_dark;
pub mod bubblegum_256_light;
pub mod buddy;
pub mod burnttoast256;
pub mod busierbee;
pub mod busybee;
pub mod bvemu;
pub mod c16gui;
pub mod c64;
pub mod cake;
pub mod cake16;
pub mod campfire;
pub mod candy;
pub mod candycode;
pub mod caramel;
pub mod carvedwood;
pub mod carvedwoodcool;
pub mod cascadia;
pub mod celtics_away;
pub mod cgpro;
pub mod chance_of_storm;
pub mod chasing_logic;
pub mod chlordane;
pub mod chocolate;
pub mod chrysoprase;
pub mod cleanphp;
pub mod clearance;
pub mod cloudy;
pub mod cobalt;
pub mod codeblocks_dark;
pub mod codefactoryv3;
pub mod codeschool;
pub mod colorful256;
pub mod colorzone;
pub mod cool;
pub mod corn;
pub mod corporation;
pub mod crayon;
pub mod crt;
pub mod crunchbang;
pub mod darkblue;
pub mod darkbone;
pub mod darkburn;
pub mod darkdevel;
pub mod darkdot;
pub mod darkeclipse;
pub mod darker_robin;
pub mod darkocean;
pub mod darkrobot;
pub mod darkslategray;
pub mod darkspectrum;
pub mod darktango;
pub mod deepsea;
pub mod delek;
pub mod denim;
pub mod desert;
pub mod desertedocean;
pub mod desertedoceanburnt;
pub mod desertex;
pub mod despacio;
pub mod devbox_dark_256;
pub mod deveiate;
pub mod diokai;
pub mod disciple;
pub mod distill;
pub mod django;
pub mod donbass;
pub mod doorhinge;
pub mod doriath;
pub mod dw_blue;
pub mod dw_cyan;
pub mod dw_green;
pub mod dw_orange;
pub mod dw_purple;
pub mod dw_red;
pub mod dw_yellow;
pub mod dzo;
pub mod earendel;
pub mod earth;
pub mod eclipse;
pub mod eclm_wombat;
pub mod ecostation;
pub mod edo_sea;
pub mod ego;
pub mod ekinivim;
pub mod elflord;
pub mod eva01;
pub mod eva01_lcl;
pub mod evening;
pub mod evokai;
pub mod evolution;
pub mod fahrenheit;
pub mod fairyfloss;
pub mod falcon;
pub mod felipec;
pub mod feral;
pub mod fine_blue;
pub mod flatland;
pub mod flatlandia;
pub mod flattened_dark;
pub mod flattened_light;
pub mod flattown;
pub mod flattr;
pub mod fnaqevan;
pub mod fokus;
pub mod forneus;
pub mod foursee;
pub mod freya;
pub mod frozen;
pub mod fruit;
pub mod fruity;
pub mod fu;
pub mod garden;
pub mod gardener;
pub mod gemcolors;
pub mod genericdc_light;
pub mod gentooish;
pub mod getafe;
pub mod github;
pub mod golded;
pub mod google;
pub mod gothic;
pub mod gravity;
pub mod graywh;
pub mod greenvision;
pub mod greenwint;
pub mod greyblue;
pub mod greygull;
pub mod guardian;
pub mod guepardo;
pub mod habamax;
pub mod heliotrope;
pub mod herald;
pub mod herokudoc_gvim;
pub mod hhazure;
pub mod hhorange;
pub mod hhpink;
pub mod hhspring;
pub mod hhteal;
pub mod hhviolet;
pub mod highwayman;
pub mod hilal;
pub mod holokai;
pub mod hornet;
pub mod hydrangea;
pub mod iceberg;
pub mod industrial;
pub mod industry;
pub mod ironman;
pub mod itg_flat;
pub mod itsasoa;
pub mod jaime;
pub mod janah;
pub mod jitterbug;
pub mod kalahari;
pub mod kalisi;
pub mod kellys;
pub mod khaki;
pub mod kings_away;
pub mod kiss;
pub mod koehler;
pub mod kolor;
pub mod kruby;
pub mod lakers_away;
pub mod lanox;
pub mod lapis256;
pub mod legiblelight;
pub mod leglight2;
pub mod leo;
pub mod less;
pub mod lettuce;
pub mod leya;
pub mod lightcolors;
pub mod lightning;
pub mod lilac;
pub mod lilydjwg_dark;
pub mod lilydjwg_green;
pub mod lilypink;
pub mod liquidcarbon;
pub mod lizard;
pub mod lodestone;
pub mod loogica;
pub mod lucius;
pub mod luinnar;
pub mod luna;
pub mod luna_term;
pub mod lunaperche;
pub mod lxvc;
pub mod lyla;
pub mod mac_classic;
pub mod macvim_light;
pub mod made_of_code;
pub mod madeofcode;
pub mod magellan;
pub mod magicwb;
pub mod manuscript;
pub mod manxome;
pub mod maroloccio;
pub mod maroloccio2;
pub mod mars;
pub mod material;
pub mod materialtheme;
pub mod maui;
pub mod mayansmoke;
pub mod messy;
pub mod meta5;
pub mod minimalist;
pub mod mint;
pub mod mizore;
pub mod mojave;
pub mod molokai;
pub mod monochrome;
pub mod monokai;
pub mod monokai_chris;
pub mod monokain;
pub mod moody;
pub mod moonshine;
pub mod moonshine_lowcontrast;
pub mod moonshine_minimal;
pub mod mopkai;
pub mod morning;
pub mod moss;
pub mod mountaindew;
pub mod mrpink;
pub mod mud;
pub mod muon;
pub mod murphy;
pub mod mushroom;
pub mod mustang;
pub mod native;
pub mod nature;
pub mod nazca;
pub mod neon;
pub mod neonwave;
pub mod nerv_ous;
pub mod nets_away;
pub mod neutron;
pub mod neverland;
pub mod neverland2;
pub mod neverland2_darker;
pub mod neverland_darker;
pub mod neverness;
pub mod new_railscasts;
pub mod newspaper;
pub mod newsprint;
pub mod nicotine;
pub mod night;
pub mod night_vision;
pub mod nightsky;
pub mod nocturne;
pub mod norwaytoday;
pub mod obsidian;
pub mod oceanblack256;
pub mod orange;
pub mod oxeded;
pub mod pablo;
pub mod pacific;
pub mod paintbox;
pub mod peachpuff;
pub mod peaksea;
pub mod penultimate;
pub mod perfect;
pub mod perfectdark;
pub mod petrel;
pub mod phphaxor;
pub mod phpx;
pub mod plasticine;
pub mod playroom;
pub mod predawn;
pub mod prmths;
pub mod proton;
pub mod py_darcula;
pub mod pyte;
pub mod quagmire;
pub mod quiet;
pub mod radicalgoodspeed;
pub mod railscasts;
pub mod rainbow_autumn;
pub mod rainbow_sea;
pub mod rastafari;
pub mod rdark;
pub mod rdark_terminal;
pub mod relaxedgreen;
pub mod retrobox;
pub mod revolutions;
pub mod rockets_away;
pub mod ron;
pub mod rootwater;
pub mod sadek1;
pub mod scheakur;
pub mod scite;
pub mod seagull;
pub mod selenitic;
pub mod seoul;
pub mod serialexperimentslain;
pub mod seti;
pub mod sexy_railscasts;
pub mod sf;
pub mod shades_of_teal;
pub mod shadesofamber;
pub mod shine;
pub mod shiny_white;
pub mod shobogenzo;
pub mod sierra;
pub mod sift;
pub mod simple_dark;
pub mod simplon;
pub mod skittles_autumn;
pub mod skittles_berry;
pub mod skittles_dark;
pub mod slate;
pub mod smyck;
pub mod soda;
pub mod softbluev2;
pub mod softlight;
pub mod sol_term;
pub mod solarized8_dark;
pub mod solarized8_dark_flat;
pub mod solarized8_dark_high;
pub mod solarized8_dark_low;
pub mod solarized8_light;
pub mod solarized8_light_flat;
pub mod solarized8_light_high;
pub mod solarized8_light_low;
pub mod sonofobsidian;
pub mod sonoma;
pub mod sorbet;
pub mod sorcerer;
pub mod soruby;
pub mod sourcerer;
pub mod southwest_fog;
pub mod spacegray;
pub mod spink;
pub mod spring;
pub mod spurs_away;
pub mod stackoverflow;
pub mod stereokai;
pub mod stonewashed_256;
pub mod stonewashed_dark_256;
pub mod stonewashed_dark_gui;
pub mod stonewashed_gui;
pub mod stormpetrel;
pub mod strange;
pub mod strawimodo;
pub mod summerfruit;
pub mod sunburst;
pub mod surveyor;
pub mod swamplight;
pub mod sweater;
pub mod sweetcandy;
pub mod symfony;
pub mod tango;
pub mod tango2;
pub mod tango_desert;
pub mod tango_morning;
pub mod tangoshady;
pub mod tangox;
pub mod taqua;
pub mod tayra;
pub mod tchaba2;
pub mod telstar;
pub mod tender;
pub mod termschool;
pub mod tetragrammaton;
pub mod thor;
pub mod thornbird;
pub mod tigrana_256_dark;
pub mod tigrana_256_light;
pub mod tir_black;
pub mod torte;
pub mod tropikos;
pub mod true_monochrome;
pub mod tutticolori;
pub mod twitchy;
pub mod umber_green;
pub mod underwater;
pub mod underwater_mod;
pub mod unokai;
pub mod up;
pub mod valloric;
pub mod vanzan_color;
pub mod vertlaiton;
pub mod vexorian;
pub mod vilight;
pub mod vimbrant;
pub mod vivid;
pub mod vydark;
pub mod warm_grey;
pub mod warriors_away;
pub mod watermark;
pub mod wellsokai;
pub mod whitedust;
pub mod wikipedia;
pub mod wildcharm;
pub mod win9xblueback;
pub mod winter;
pub mod winterd;
pub mod wintersday;
pub mod wolfpack;
pub mod wombat;
pub mod wombat256;
pub mod wombat256dave;
pub mod wwdc16;
pub mod wwdc17;
pub mod xcode_default;
pub mod xian;
pub mod xoria256;
pub mod yeller;
pub mod yuejiu;
pub mod zaibatsu;
pub mod zazen;
pub mod zellner;
pub mod zenburn;
pub mod zenesque;
pub mod zephyr;
pub mod zmrok;

/// All themes in the `vim` collection.
pub static THEMES: &[&Theme] = &[
    &_0x7a69_dark::THEME,
    &_256_grayvim::THEME,
    &_256_jungle::THEME,
    &_256_noir::THEME,
    &adventurous::THEME,
    &af::THEME,
    &anderson::THEME,
    &angr::THEME,
    &apprentice::THEME,
    &arcadia::THEME,
    &archery::THEME,
    &argonaut::THEME,
    &ashen::THEME,
    &asmanian_blood::THEME,
    &atom::THEME,
    &aurora::THEME,
    &autumnleaf::THEME,
    &babymate256::THEME,
    &base::THEME,
    &baycomb::THEME,
    &bayqua::THEME,
    &bclear::THEME,
    &beachcomber::THEME,
    &beauty256::THEME,
    &beekai::THEME,
    &behelit::THEME,
    &benlight::THEME,
    &benokai::THEME,
    &biogoo::THEME,
    &birds_of_paradise::THEME,
    &bitterjug::THEME,
    &blackboard::THEME,
    &blackdust::THEME,
    &blacklight::THEME,
    &blazer::THEME,
    &blue::THEME,
    &bluechia::THEME,
    &bluenes::THEME,
    &blues::THEME,
    &bluez::THEME,
    &bluish::THEME,
    &boa::THEME,
    &boltzmann::THEME,
    &breeze::THEME,
    &breezy::THEME,
    &brighton::THEME,
    &brogrammer::THEME,
    &bubblegum::THEME,
    &bubblegum_256_dark::THEME,
    &bubblegum_256_light::THEME,
    &buddy::THEME,
    &burnttoast256::THEME,
    &busierbee::THEME,
    &busybee::THEME,
    &bvemu::THEME,
    &c16gui::THEME,
    &c64::THEME,
    &cake::THEME,
    &cake16::THEME,
    &campfire::THEME,
    &candy::THEME,
    &candycode::THEME,
    &caramel::THEME,
    &carvedwood::THEME,
    &carvedwoodcool::THEME,
    &cascadia::THEME,
    &celtics_away::THEME,
    &cgpro::THEME,
    &chance_of_storm::THEME,
    &chasing_logic::THEME,
    &chlordane::THEME,
    &chocolate::THEME,
    &chrysoprase::THEME,
    &cleanphp::THEME,
    &clearance::THEME,
    &cloudy::THEME,
    &cobalt::THEME,
    &codeblocks_dark::THEME,
    &codefactoryv3::THEME,
    &codeschool::THEME,
    &colorful256::THEME,
    &colorzone::THEME,
    &cool::THEME,
    &corn::THEME,
    &corporation::THEME,
    &crayon::THEME,
    &crt::THEME,
    &crunchbang::THEME,
    &darkblue::THEME,
    &darkbone::THEME,
    &darkburn::THEME,
    &darkdevel::THEME,
    &darkdot::THEME,
    &darkeclipse::THEME,
    &darker_robin::THEME,
    &darkocean::THEME,
    &darkrobot::THEME,
    &darkslategray::THEME,
    &darkspectrum::THEME,
    &darktango::THEME,
    &deepsea::THEME,
    &delek::THEME,
    &denim::THEME,
    &desert::THEME,
    &desertedocean::THEME,
    &desertedoceanburnt::THEME,
    &desertex::THEME,
    &despacio::THEME,
    &devbox_dark_256::THEME,
    &deveiate::THEME,
    &diokai::THEME,
    &disciple::THEME,
    &distill::THEME,
    &django::THEME,
    &donbass::THEME,
    &doorhinge::THEME,
    &doriath::THEME,
    &dw_blue::THEME,
    &dw_cyan::THEME,
    &dw_green::THEME,
    &dw_orange::THEME,
    &dw_purple::THEME,
    &dw_red::THEME,
    &dw_yellow::THEME,
    &dzo::THEME,
    &earendel::THEME,
    &earth::THEME,
    &eclipse::THEME,
    &eclm_wombat::THEME,
    &ecostation::THEME,
    &edo_sea::THEME,
    &ego::THEME,
    &ekinivim::THEME,
    &elflord::THEME,
    &eva01::THEME,
    &eva01_lcl::THEME,
    &evening::THEME,
    &evokai::THEME,
    &evolution::THEME,
    &fahrenheit::THEME,
    &fairyfloss::THEME,
    &falcon::THEME,
    &felipec::THEME,
    &feral::THEME,
    &fine_blue::THEME,
    &flatland::THEME,
    &flatlandia::THEME,
    &flattened_dark::THEME,
    &flattened_light::THEME,
    &flattown::THEME,
    &flattr::THEME,
    &fnaqevan::THEME,
    &fokus::THEME,
    &forneus::THEME,
    &foursee::THEME,
    &freya::THEME,
    &frozen::THEME,
    &fruit::THEME,
    &fruity::THEME,
    &fu::THEME,
    &garden::THEME,
    &gardener::THEME,
    &gemcolors::THEME,
    &genericdc_light::THEME,
    &gentooish::THEME,
    &getafe::THEME,
    &github::THEME,
    &golded::THEME,
    &google::THEME,
    &gothic::THEME,
    &gravity::THEME,
    &graywh::THEME,
    &greenvision::THEME,
    &greenwint::THEME,
    &greyblue::THEME,
    &greygull::THEME,
    &guardian::THEME,
    &guepardo::THEME,
    &habamax::THEME,
    &heliotrope::THEME,
    &herald::THEME,
    &herokudoc_gvim::THEME,
    &hhazure::THEME,
    &hhorange::THEME,
    &hhpink::THEME,
    &hhspring::THEME,
    &hhteal::THEME,
    &hhviolet::THEME,
    &highwayman::THEME,
    &hilal::THEME,
    &holokai::THEME,
    &hornet::THEME,
    &hydrangea::THEME,
    &iceberg::THEME,
    &industrial::THEME,
    &industry::THEME,
    &ironman::THEME,
    &itg_flat::THEME,
    &itsasoa::THEME,
    &jaime::THEME,
    &janah::THEME,
    &jitterbug::THEME,
    &kalahari::THEME,
    &kalisi::THEME,
    &kellys::THEME,
    &khaki::THEME,
    &kings_away::THEME,
    &kiss::THEME,
    &koehler::THEME,
    &kolor::THEME,
    &kruby::THEME,
    &lakers_away::THEME,
    &lanox::THEME,
    &lapis256::THEME,
    &legiblelight::THEME,
    &leglight2::THEME,
    &leo::THEME,
    &less::THEME,
    &lettuce::THEME,
    &leya::THEME,
    &lightcolors::THEME,
    &lightning::THEME,
    &lilac::THEME,
    &lilydjwg_dark::THEME,
    &lilydjwg_green::THEME,
    &lilypink::THEME,
    &liquidcarbon::THEME,
    &lizard::THEME,
    &lodestone::THEME,
    &loogica::THEME,
    &lucius::THEME,
    &luinnar::THEME,
    &luna::THEME,
    &luna_term::THEME,
    &lunaperche::THEME,
    &lxvc::THEME,
    &lyla::THEME,
    &mac_classic::THEME,
    &macvim_light::THEME,
    &made_of_code::THEME,
    &madeofcode::THEME,
    &magellan::THEME,
    &magicwb::THEME,
    &manuscript::THEME,
    &manxome::THEME,
    &maroloccio::THEME,
    &maroloccio2::THEME,
    &mars::THEME,
    &material::THEME,
    &materialtheme::THEME,
    &maui::THEME,
    &mayansmoke::THEME,
    &messy::THEME,
    &meta5::THEME,
    &minimalist::THEME,
    &mint::THEME,
    &mizore::THEME,
    &mojave::THEME,
    &molokai::THEME,
    &monochrome::THEME,
    &monokai::THEME,
    &monokai_chris::THEME,
    &monokain::THEME,
    &moody::THEME,
    &moonshine::THEME,
    &moonshine_lowcontrast::THEME,
    &moonshine_minimal::THEME,
    &mopkai::THEME,
    &morning::THEME,
    &moss::THEME,
    &mountaindew::THEME,
    &mrpink::THEME,
    &mud::THEME,
    &muon::THEME,
    &murphy::THEME,
    &mushroom::THEME,
    &mustang::THEME,
    &native::THEME,
    &nature::THEME,
    &nazca::THEME,
    &neon::THEME,
    &neonwave::THEME,
    &nerv_ous::THEME,
    &nets_away::THEME,
    &neutron::THEME,
    &neverland::THEME,
    &neverland2::THEME,
    &neverland2_darker::THEME,
    &neverland_darker::THEME,
    &neverness::THEME,
    &new_railscasts::THEME,
    &newspaper::THEME,
    &newsprint::THEME,
    &nicotine::THEME,
    &night::THEME,
    &night_vision::THEME,
    &nightsky::THEME,
    &nocturne::THEME,
    &norwaytoday::THEME,
    &obsidian::THEME,
    &oceanblack256::THEME,
    &orange::THEME,
    &oxeded::THEME,
    &pablo::THEME,
    &pacific::THEME,
    &paintbox::THEME,
    &peachpuff::THEME,
    &peaksea::THEME,
    &penultimate::THEME,
    &perfect::THEME,
    &perfectdark::THEME,
    &petrel::THEME,
    &phphaxor::THEME,
    &phpx::THEME,
    &plasticine::THEME,
    &playroom::THEME,
    &predawn::THEME,
    &prmths::THEME,
    &proton::THEME,
    &py_darcula::THEME,
    &pyte::THEME,
    &quagmire::THEME,
    &quiet::THEME,
    &radicalgoodspeed::THEME,
    &railscasts::THEME,
    &rainbow_autumn::THEME,
    &rainbow_sea::THEME,
    &rastafari::THEME,
    &rdark::THEME,
    &rdark_terminal::THEME,
    &relaxedgreen::THEME,
    &retrobox::THEME,
    &revolutions::THEME,
    &rockets_away::THEME,
    &ron::THEME,
    &rootwater::THEME,
    &sadek1::THEME,
    &scheakur::THEME,
    &scite::THEME,
    &seagull::THEME,
    &selenitic::THEME,
    &seoul::THEME,
    &serialexperimentslain::THEME,
    &seti::THEME,
    &sexy_railscasts::THEME,
    &sf::THEME,
    &shades_of_teal::THEME,
    &shadesofamber::THEME,
    &shine::THEME,
    &shiny_white::THEME,
    &shobogenzo::THEME,
    &sierra::THEME,
    &sift::THEME,
    &simple_dark::THEME,
    &simplon::THEME,
    &skittles_autumn::THEME,
    &skittles_berry::THEME,
    &skittles_dark::THEME,
    &slate::THEME,
    &smyck::THEME,
    &soda::THEME,
    &softbluev2::THEME,
    &softlight::THEME,
    &sol_term::THEME,
    &solarized8_dark::THEME,
    &solarized8_dark_flat::THEME,
    &solarized8_dark_high::THEME,
    &solarized8_dark_low::THEME,
    &solarized8_light::THEME,
    &solarized8_light_flat::THEME,
    &solarized8_light_high::THEME,
    &solarized8_light_low::THEME,
    &sonofobsidian::THEME,
    &sonoma::THEME,
    &sorbet::THEME,
    &sorcerer::THEME,
    &soruby::THEME,
    &sourcerer::THEME,
    &southwest_fog::THEME,
    &spacegray::THEME,
    &spink::THEME,
    &spring::THEME,
    &spurs_away::THEME,
    &stackoverflow::THEME,
    &stereokai::THEME,
    &stonewashed_256::THEME,
    &stonewashed_dark_256::THEME,
    &stonewashed_dark_gui::THEME,
    &stonewashed_gui::THEME,
    &stormpetrel::THEME,
    &strange::THEME,
    &strawimodo::THEME,
    &summerfruit::THEME,
    &sunburst::THEME,
    &surveyor::THEME,
    &swamplight::THEME,
    &sweater::THEME,
    &sweetcandy::THEME,
    &symfony::THEME,
    &tango::THEME,
    &tango2::THEME,
    &tango_desert::THEME,
    &tango_morning::THEME,
    &tangoshady::THEME,
    &tangox::THEME,
    &taqua::THEME,
    &tayra::THEME,
    &tchaba2::THEME,
    &telstar::THEME,
    &tender::THEME,
    &termschool::THEME,
    &tetragrammaton::THEME,
    &thor::THEME,
    &thornbird::THEME,
    &tigrana_256_dark::THEME,
    &tigrana_256_light::THEME,
    &tir_black::THEME,
    &torte::THEME,
    &tropikos::THEME,
    &true_monochrome::THEME,
    &tutticolori::THEME,
    &twitchy::THEME,
    &umber_green::THEME,
    &underwater::THEME,
    &underwater_mod::THEME,
    &unokai::THEME,
    &up::THEME,
    &valloric::THEME,
    &vanzan_color::THEME,
    &vertlaiton::THEME,
    &vexorian::THEME,
    &vilight::THEME,
    &vimbrant::THEME,
    &vivid::THEME,
    &vydark::THEME,
    &warm_grey::THEME,
    &warriors_away::THEME,
    &watermark::THEME,
    &wellsokai::THEME,
    &whitedust::THEME,
    &wikipedia::THEME,
    &wildcharm::THEME,
    &win9xblueback::THEME,
    &winter::THEME,
    &winterd::THEME,
    &wintersday::THEME,
    &wolfpack::THEME,
    &wombat::THEME,
    &wombat256::THEME,
    &wombat256dave::THEME,
    &wwdc16::THEME,
    &wwdc17::THEME,
    &xcode_default::THEME,
    &xian::THEME,
    &xoria256::THEME,
    &yeller::THEME,
    &yuejiu::THEME,
    &zaibatsu::THEME,
    &zazen::THEME,
    &zellner::THEME,
    &zenburn::THEME,
    &zenesque::THEME,
    &zephyr::THEME,
    &zmrok::THEME,
];
