//! moonshine color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// moonshine
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("moonshine"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xd7af5f),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x121212)),
    line_highlight: Some(Color::from_hex(0x303030)),
    gutter: Some(Color::from_hex(0x626262)),
    statusbar_bg: Some(Color::from_hex(0x303030)),
    statusbar_fg: Some(Color::from_hex(0xeeeeee)),
    comment: Some(Color::from_hex(0x444444)),
    keyword: Some(Color::from_hex(0xd78700)),
    string: Some(Color::from_hex(0x878700)),
    function: Some(Color::from_hex(0x875f00)),
    variable: Some(Color::from_hex(0x5f875f)),
    r#type: Some(Color::from_hex(0x875f00)),
    constant: Some(Color::from_hex(0xd75f00)),
    operator: Some(Color::from_hex(0xd78700)),
    tag: Some(Color::from_hex(0x5f875f)),
    error: Some(Color::from_hex(0x262626)),
    warning: Some(Color::from_hex(0xaf0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x262626)),
    orange: None,
    yellow: Some(Color::from_hex(0xaf0000)),
    green: Some(Color::from_hex(0x878700)),
    cyan: Some(Color::from_hex(0x875f00)),
    blue: Some(Color::from_hex(0x875f00)),
    purple: Some(Color::from_hex(0xd78700)),
    magenta: Some(Color::from_hex(0x875f5f)),
};
