//! moonshine_minimal color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// moonshine_minimal
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("moonshine_minimal"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xffd787),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x121212)),
    line_highlight: Some(Color::from_hex(0x303030)),
    gutter: Some(Color::from_hex(0x626262)),
    statusbar_bg: Some(Color::from_hex(0x303030)),
    statusbar_fg: Some(Color::from_hex(0xffffd7)),
    comment: Some(Color::from_hex(0x6c6c6c)),
    keyword: Some(Color::from_hex(0xaf875f)),
    string: Some(Color::from_hex(0xafaf5f)),
    function: Some(Color::from_hex(0xaf875f)),
    variable: Some(Color::from_hex(0xafaf5f)),
    r#type: Some(Color::from_hex(0xaf875f)),
    constant: Some(Color::from_hex(0xafaf5f)),
    operator: Some(Color::from_hex(0xaf875f)),
    tag: Some(Color::from_hex(0x875f00)),
    error: Some(Color::from_hex(0x262626)),
    warning: Some(Color::from_hex(0xaf0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x262626)),
    orange: None,
    yellow: Some(Color::from_hex(0xaf0000)),
    green: Some(Color::from_hex(0xafaf5f)),
    cyan: Some(Color::from_hex(0xaf875f)),
    blue: Some(Color::from_hex(0xaf875f)),
    purple: Some(Color::from_hex(0xaf875f)),
    magenta: Some(Color::from_hex(0xaf875f)),
};
