//! mud color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// mud
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("mud"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x330000),
    fg: Color::from_hex(0xffffcc),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x996666)),
    keyword: Some(Color::from_hex(0xff8088)),
    string: Some(Color::from_hex(0x99ccff)),
    function: Some(Color::from_hex(0xfffcfc)),
    variable: Some(Color::from_hex(0x33ff99)),
    r#type: Some(Color::from_hex(0xccffff)),
    constant: Some(Color::from_hex(0xf0f000)),
    operator: Some(Color::from_hex(0xff0000)),
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xcccccc)),
    green: Some(Color::from_hex(0x99ccff)),
    cyan: Some(Color::from_hex(0xccffff)),
    blue: Some(Color::from_hex(0xfffcfc)),
    purple: Some(Color::from_hex(0xff8088)),
    magenta: Some(Color::from_hex(0xcc6600)),
};
