//! mushroom color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// mushroom
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "mushroom",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0x8787af),
    cursor: None,
    selection: Some(Color::from_hex(0x303030)),
    line_highlight: Some(Color::from_hex(0x1c1c1c)),
    gutter: Some(Color::from_hex(0x875f5f)),
    statusbar_bg: Some(Color::from_hex(0x303030)),
    statusbar_fg: Some(Color::from_hex(0xd7875f)),
    comment: Some(Color::from_hex(0x6c6c6c)),
    keyword: Some(Color::from_hex(0xaf8700)),
    string: Some(Color::from_hex(0x5f8700)),
    function: None,
    variable: Some(Color::from_hex(0xaf5f5f)),
    r#type: Some(Color::from_hex(0x5f87af)),
    constant: Some(Color::from_hex(0xaf5f00)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xd75f5f)),
    warning: Some(Color::from_hex(0xffd7ff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd75f5f)),
    orange: None,
    yellow: Some(Color::from_hex(0xffd7ff)),
    green: Some(Color::from_hex(0x5f8700)),
    cyan: Some(Color::from_hex(0x5f87af)),
    blue: None,
    purple: Some(Color::from_hex(0xaf8700)),
    magenta: Some(Color::from_hex(0x875f87)),
};
