//! neon color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// neon
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("neon"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x303030),
    fg: Color::from_hex(0xf0f0f0),
    cursor: Some(Color::from_hex(0x8040ff)),
    selection: Some(Color::from_hex(0x008000)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x707070)),
    statusbar_bg: Some(Color::from_hex(0xc4c4c4)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xc0c0c0)),
    keyword: Some(Color::from_hex(0xdcdc78)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x40f8f8)),
    r#type: Some(Color::from_hex(0x60f0a8)),
    constant: Some(Color::from_hex(0x92d4ff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffa0ff)),
    warning: Some(Color::from_hex(0xffa0ff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffa0ff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffa0ff)),
    green: Some(Color::from_hex(0xa0d0ff)),
    cyan: Some(Color::from_hex(0x60f0a8)),
    blue: None,
    purple: Some(Color::from_hex(0xdcdc78)),
    magenta: Some(Color::from_hex(0xffa8ff)),
};
