//! nerv-ous color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// nerv-ous
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("nerv-ous"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x1a1a1a),
    fg: Color::from_hex(0xb9c6e0),
    cursor: Some(Color::from_hex(0xd0cb50)),
    selection: Some(Color::from_hex(0x400000)),
    line_highlight: Some(Color::from_hex(0x000000)),
    gutter: Some(Color::from_hex(0x615882)),
    statusbar_bg: Some(Color::from_hex(0x2e254f)),
    statusbar_fg: Some(Color::from_hex(0xa9a1c7)),
    comment: Some(Color::from_hex(0x615882)),
    keyword: Some(Color::from_hex(0x9253ad)),
    string: Some(Color::from_hex(0xd05310)),
    function: Some(Color::from_hex(0x8eaa29)),
    variable: Some(Color::from_hex(0x8eaa29)),
    r#type: Some(Color::from_hex(0x8eaa29)),
    constant: Some(Color::from_hex(0xab2315)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0x000000)),
    warning: Some(Color::from_hex(0x000000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x000000)),
    orange: None,
    yellow: Some(Color::from_hex(0x000000)),
    green: Some(Color::from_hex(0xd05310)),
    cyan: Some(Color::from_hex(0x8eaa29)),
    blue: Some(Color::from_hex(0x8eaa29)),
    purple: Some(Color::from_hex(0x9253ad)),
    magenta: Some(Color::from_hex(0xd0cb50)),
};
