//! neutron color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// neutron
///
/// Variant: Light
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "neutron",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0xf2efd5),
    fg: Color::from_hex(0x404040),
    cursor: Some(Color::from_hex(0x404040)),
    selection: Some(Color::from_hex(0xfffac8)),
    line_highlight: Some(Color::from_hex(0xe0e0e0)),
    gutter: Some(Color::from_hex(0x808080)),
    statusbar_bg: Some(Color::from_hex(0x808080)),
    statusbar_fg: Some(Color::from_hex(0xf2efd5)),
    comment: Some(Color::from_hex(0xbbbbbb)),
    keyword: Some(Color::from_hex(0x408077)),
    string: Some(Color::from_hex(0xa07060)),
    function: Some(Color::from_hex(0x6d7181)),
    variable: Some(Color::from_hex(0x546c48)),
    r#type: Some(Color::from_hex(0x7d95ad)),
    constant: Some(Color::from_hex(0x555321)),
    operator: Some(Color::from_hex(0xa79a39)),
    tag: Some(Color::from_hex(0xa6a679)),
    error: Some(Color::from_hex(0xc83c28)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xc83c28)),
    orange: None,
    yellow: Some(Color::from_hex(0x408077)),
    green: Some(Color::from_hex(0xa07060)),
    cyan: Some(Color::from_hex(0x7d95ad)),
    blue: Some(Color::from_hex(0x6d7181)),
    purple: Some(Color::from_hex(0x408077)),
    magenta: Some(Color::from_hex(0x7d64af)),
};
