//! oceanblack256 color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// oceanblack256
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("oceanblack256"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0xafd7d7)),
    selection: Some(Color::from_hex(0xffffff)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x767676)),
    statusbar_bg: Some(Color::from_hex(0xe4e4e4)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x875f5f)),
    keyword: Some(Color::from_hex(0x5fd75f)),
    string: Some(Color::from_hex(0x87afff)),
    function: Some(Color::from_hex(0xafd7af)),
    variable: Some(Color::from_hex(0xafd7d7)),
    r#type: Some(Color::from_hex(0x87afd7)),
    constant: Some(Color::from_hex(0x008080)),
    operator: Some(Color::from_hex(0x87ff00)),
    tag: None,
    error: Some(Color::from_hex(0xffffd7)),
    warning: Some(Color::from_hex(0xff5f5f)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffd7)),
    orange: None,
    yellow: Some(Color::from_hex(0xff5f5f)),
    green: Some(Color::from_hex(0x87afff)),
    cyan: Some(Color::from_hex(0x87afd7)),
    blue: Some(Color::from_hex(0xafd7af)),
    purple: Some(Color::from_hex(0x5fd75f)),
    magenta: Some(Color::from_hex(0x87d7ff)),
};
