//! paintbox color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// paintbox
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("paintbox"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x19191d),
    fg: Color::from_hex(0xdddddd),
    cursor: Some(Color::from_hex(0xdddddd)),
    selection: Some(Color::from_hex(0xd9c900)),
    line_highlight: Some(Color::from_hex(0x343434)),
    gutter: Some(Color::from_hex(0x5a5a5a)),
    statusbar_bg: Some(Color::from_hex(0xdddddd)),
    statusbar_fg: Some(Color::from_hex(0xbd0d74)),
    comment: Some(Color::from_hex(0x5a5a5a)),
    keyword: Some(Color::from_hex(0x9fc439)),
    string: Some(Color::from_hex(0x238bcc)),
    function: Some(Color::from_hex(0xdddddd)),
    variable: Some(Color::from_hex(0x904ca8)),
    r#type: Some(Color::from_hex(0xe08a1f)),
    constant: Some(Color::from_hex(0x238bcc)),
    operator: Some(Color::from_hex(0x904ca8)),
    tag: Some(Color::from_hex(0x904ca8)),
    error: Some(Color::from_hex(0xcf310c)),
    warning: Some(Color::from_hex(0xcf310c)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xcf310c)),
    orange: None,
    yellow: Some(Color::from_hex(0xcf310c)),
    green: Some(Color::from_hex(0x238bcc)),
    cyan: Some(Color::from_hex(0xe08a1f)),
    blue: Some(Color::from_hex(0xdddddd)),
    purple: Some(Color::from_hex(0x9fc439)),
    magenta: Some(Color::from_hex(0xbd0d74)),
};
