//! perfect color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// perfect
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("perfect"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x000000)),
    selection: None,
    line_highlight: Some(Color::from_hex(0xf7f7f7)),
    gutter: Some(Color::from_hex(0xbbbbbb)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0xbbbbbb)),
    keyword: Some(Color::from_hex(0x1d5a88)),
    string: Some(Color::from_hex(0x56882c)),
    function: Some(Color::from_hex(0xa9082f)),
    variable: Some(Color::from_hex(0x000000)),
    r#type: Some(Color::from_hex(0x000000)),
    constant: Some(Color::from_hex(0x56882c)),
    operator: Some(Color::from_hex(0x1d5a88)),
    tag: Some(Color::from_hex(0x000000)),
    error: Some(Color::from_hex(0x000000)),
    warning: Some(Color::from_hex(0x000000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x000000)),
    orange: None,
    yellow: Some(Color::from_hex(0x000000)),
    green: Some(Color::from_hex(0x56882c)),
    cyan: Some(Color::from_hex(0x000000)),
    blue: Some(Color::from_hex(0xa9082f)),
    purple: Some(Color::from_hex(0x1d5a88)),
    magenta: Some(Color::from_hex(0x000000)),
};
