//! petrel color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// petrel
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "petrel",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x0b141a),
    fg: Color::from_hex(0x787e82),
    cursor: Some(Color::from_hex(0x61707a)),
    selection: Some(Color::from_hex(0x0b141a)),
    line_highlight: Some(Color::from_hex(0x1d252b)),
    gutter: Some(Color::from_hex(0x61707a)),
    statusbar_bg: Some(Color::from_hex(0x0b141a)),
    statusbar_fg: Some(Color::from_hex(0x61707a)),
    comment: Some(Color::from_hex(0x61707a)),
    keyword: Some(Color::from_hex(0x3f8f36)),
    string: Some(Color::from_hex(0x35898c)),
    function: Some(Color::from_hex(0x4384b0)),
    variable: Some(Color::from_hex(0x4384b0)),
    r#type: Some(Color::from_hex(0x947b38)),
    constant: Some(Color::from_hex(0x35898c)),
    operator: Some(Color::from_hex(0x3f8f36)),
    tag: Some(Color::from_hex(0xba656d)),
    error: Some(Color::from_hex(0xba656d)),
    warning: Some(Color::from_hex(0xba656d)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xba656d)),
    orange: None,
    yellow: Some(Color::from_hex(0xba656d)),
    green: Some(Color::from_hex(0x35898c)),
    cyan: Some(Color::from_hex(0x947b38)),
    blue: Some(Color::from_hex(0x4384b0)),
    purple: Some(Color::from_hex(0x3f8f36)),
    magenta: Some(Color::from_hex(0xb06d43)),
};
