//! phphaxor color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// phphaxor
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "phphaxor",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xc0c0c0),
    cursor: Some(Color::from_hex(0x00ff00)),
    selection: None,
    line_highlight: None,
    gutter: None,
    statusbar_bg: None,
    statusbar_fg: None,
    comment: None,
    keyword: Some(Color::from_hex(0x00ffff)),
    string: Some(Color::from_hex(0xc0c0c0)),
    function: Some(Color::from_hex(0x00ffff)),
    variable: Some(Color::from_hex(0xc0c0c0)),
    r#type: Some(Color::from_hex(0xc0c0c0)),
    constant: Some(Color::from_hex(0xc0c0c0)),
    operator: Some(Color::from_hex(0x00ffff)),
    tag: Some(Color::from_hex(0x008000)),
    error: Some(Color::from_hex(0xc0c0c0)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xc0c0c0)),
    orange: None,
    yellow: Some(Color::from_hex(0x008000)),
    green: Some(Color::from_hex(0xc0c0c0)),
    cyan: Some(Color::from_hex(0xc0c0c0)),
    blue: Some(Color::from_hex(0x00ffff)),
    purple: Some(Color::from_hex(0x00ffff)),
    magenta: Some(Color::from_hex(0xc0c0c0)),
};
