//! sea color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// sea
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("sea"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x343478),
    fg: Color::from_hex(0xf0f0f8),
    cursor: Some(Color::from_hex(0xd86020)),
    selection: Some(Color::from_hex(0x6060ff)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x7070e8)),
    statusbar_bg: Some(Color::from_hex(0xd0d0e0)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0xb0b0c8)),
    keyword: Some(Color::from_hex(0xf0f060)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xc0c0ff)),
    r#type: Some(Color::from_hex(0x40ff80)),
    constant: Some(Color::from_hex(0x60ffff)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x60ff60)),
    cyan: Some(Color::from_hex(0x40ff80)),
    blue: None,
    purple: Some(Color::from_hex(0xf0f060)),
    magenta: Some(Color::from_hex(0xffb0ff)),
};
