//! rastafari color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// rastafari
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "rastafari",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xaaaaaa),
    cursor: Some(Color::from_hex(0xff0000)),
    selection: Some(Color::from_hex(0x008000)),
    line_highlight: Some(Color::from_hex(0x111111)),
    gutter: Some(Color::from_hex(0xffff60)),
    statusbar_bg: Some(Color::from_hex(0x008000)),
    statusbar_fg: Some(Color::from_hex(0x66ff66)),
    comment: Some(Color::from_hex(0x00aa00)),
    keyword: Some(Color::from_hex(0xdddddd)),
    string: Some(Color::from_hex(0xaa2222)),
    function: Some(Color::from_hex(0xdddddd)),
    variable: Some(Color::from_hex(0xdddddd)),
    r#type: Some(Color::from_hex(0xdddddd)),
    constant: Some(Color::from_hex(0xaa2222)),
    operator: Some(Color::from_hex(0xdddddd)),
    tag: None,
    error: Some(Color::from_hex(0xffff60)),
    warning: Some(Color::from_hex(0xffff60)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffff60)),
    orange: None,
    yellow: Some(Color::from_hex(0xffff60)),
    green: Some(Color::from_hex(0xaa2222)),
    cyan: Some(Color::from_hex(0xdddddd)),
    blue: Some(Color::from_hex(0xdddddd)),
    purple: Some(Color::from_hex(0xdddddd)),
    magenta: Some(Color::from_hex(0x666666)),
};
