//! retrobox color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// retrobox
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "retrobox",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xfbf1c7),
    fg: Color::from_hex(0x3c3836),
    cursor: Some(Color::from_hex(0x282828)),
    selection: Some(Color::from_hex(0xb0d0d0)),
    line_highlight: Some(Color::from_hex(0xe5d4b1)),
    gutter: Some(Color::from_hex(0xa89984)),
    statusbar_bg: Some(Color::from_hex(0x3c3836)),
    statusbar_fg: Some(Color::from_hex(0xbdae93)),
    comment: Some(Color::from_hex(0x928374)),
    keyword: Some(Color::from_hex(0x9d0006)),
    string: Some(Color::from_hex(0x79740e)),
    function: Some(Color::from_hex(0x79740e)),
    variable: Some(Color::from_hex(0x076678)),
    r#type: Some(Color::from_hex(0xb57614)),
    constant: Some(Color::from_hex(0x8f3f71)),
    operator: Some(Color::from_hex(0x427b58)),
    tag: Some(Color::from_hex(0xff5f00)),
    error: Some(Color::from_hex(0xfbf1c7)),
    warning: Some(Color::from_hex(0x9d0006)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xfbf1c7)),
    orange: None,
    yellow: Some(Color::from_hex(0x9d0006)),
    green: Some(Color::from_hex(0x79740e)),
    cyan: Some(Color::from_hex(0xb57614)),
    blue: Some(Color::from_hex(0x79740e)),
    purple: Some(Color::from_hex(0x9d0006)),
    magenta: Some(Color::from_hex(0x427b58)),
};
