//! soyokaze color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// soyokaze
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "soyokaze",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x202020),
    fg: Color::from_hex(0xb4b4b4),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: None,
    line_highlight: Some(Color::from_hex(0x333333)),
    gutter: Some(Color::from_hex(0xb4b4b4)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x666666)),
    keyword: Some(Color::from_hex(0x49ff89)),
    string: None,
    function: Some(Color::from_hex(0x49ff89)),
    variable: Some(Color::from_hex(0xffffff)),
    r#type: Some(Color::from_hex(0x49ff89)),
    constant: Some(Color::from_hex(0xffffff)),
    operator: None,
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: None,
    cyan: Some(Color::from_hex(0x49ff89)),
    blue: Some(Color::from_hex(0x49ff89)),
    purple: Some(Color::from_hex(0x49ff89)),
    magenta: Some(Color::from_hex(0xffffff)),
};
