//! shine color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// shine
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "shine",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x000000)),
    selection: Some(Color::from_hex(0xa8a8a8)),
    line_highlight: Some(Color::from_hex(0xdadada)),
    gutter: Some(Color::from_hex(0x767676)),
    statusbar_bg: Some(Color::from_hex(0x000000)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0xa8a8a8)),
    keyword: Some(Color::from_hex(0x2e8b57)),
    string: None,
    function: Some(Color::from_hex(0x008b8b)),
    variable: Some(Color::from_hex(0x008b8b)),
    r#type: Some(Color::from_hex(0x2e8b57)),
    constant: Some(Color::from_hex(0xa07070)),
    operator: Some(Color::from_hex(0x2e8b57)),
    tag: Some(Color::from_hex(0xff8c00)),
    error: Some(Color::from_hex(0xff0000)),
    warning: Some(Color::from_hex(0x6a0dad)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff0000)),
    orange: None,
    yellow: Some(Color::from_hex(0x6a0dad)),
    green: Some(Color::from_hex(0xffffff)),
    cyan: Some(Color::from_hex(0x2e8b57)),
    blue: Some(Color::from_hex(0x008b8b)),
    purple: Some(Color::from_hex(0x2e8b57)),
    magenta: Some(Color::from_hex(0x6a0dad)),
};
