//! skittles_berry color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// skittles_berry
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "skittles_berry",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xffffd7),
    cursor: Some(Color::from_hex(0x005fd7)),
    selection: Some(Color::from_hex(0x875f5f)),
    line_highlight: Some(Color::from_hex(0x262626)),
    gutter: Some(Color::from_hex(0xffffff)),
    statusbar_bg: None,
    statusbar_fg: Some(Color::from_hex(0x5f8787)),
    comment: Some(Color::from_hex(0x5f8787)),
    keyword: Some(Color::from_hex(0x87d700)),
    string: Some(Color::from_hex(0x87d700)),
    function: Some(Color::from_hex(0x005faf)),
    variable: Some(Color::from_hex(0xffff87)),
    r#type: Some(Color::from_hex(0x5fd7ff)),
    constant: Some(Color::from_hex(0x8700af)),
    operator: Some(Color::from_hex(0xffaf00)),
    tag: Some(Color::from_hex(0x87d7ff)),
    error: Some(Color::from_hex(0x87d7ff)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x87d7ff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x87d700)),
    cyan: Some(Color::from_hex(0x5fd7ff)),
    blue: Some(Color::from_hex(0x005faf)),
    purple: Some(Color::from_hex(0x87d700)),
    magenta: Some(Color::from_hex(0xafd75f)),
};
