//! skittles_dark color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// skittles_dark
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("skittles_dark"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x231f20),
    fg: Color::from_hex(0xf8f8f2),
    cursor: Some(Color::from_hex(0xf8f8f0)),
    selection: Some(Color::from_hex(0x403d3d)),
    line_highlight: Some(Color::from_hex(0x121212)),
    gutter: Some(Color::from_hex(0xffffff)),
    statusbar_bg: None,
    statusbar_fg: Some(Color::from_hex(0x455354)),
    comment: Some(Color::from_hex(0x5d8d8f)),
    keyword: Some(Color::from_hex(0x8ac6f2)),
    string: Some(Color::from_hex(0x75d142)),
    function: Some(Color::from_hex(0x0c60a0)),
    variable: Some(Color::from_hex(0xffffff)),
    r#type: Some(Color::from_hex(0x5faac7)),
    constant: Some(Color::from_hex(0xae81ff)),
    operator: Some(Color::from_hex(0xff9900)),
    tag: Some(Color::from_hex(0x8ac6f2)),
    error: Some(Color::from_hex(0x8ac6f2)),
    warning: Some(Color::from_hex(0xffffff)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x8ac6f2)),
    orange: None,
    yellow: Some(Color::from_hex(0xffffff)),
    green: Some(Color::from_hex(0x75d142)),
    cyan: Some(Color::from_hex(0x5faac7)),
    blue: Some(Color::from_hex(0x0c60a0)),
    purple: Some(Color::from_hex(0x8ac6f2)),
    magenta: Some(Color::from_hex(0xa6e22e)),
};
