//! softbluev2 color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// softbluev2
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "softbluev2",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x183058),
    fg: Color::from_hex(0xb0b0e0),
    cursor: Some(Color::from_hex(0xb3b2df)),
    selection: Some(Color::from_hex(0x001146)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x87875f)),
    statusbar_bg: Some(Color::from_hex(0x466292)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x6279a0)),
    keyword: Some(Color::from_hex(0xcdee56)),
    string: None,
    function: Some(Color::from_hex(0xc777ef)),
    variable: Some(Color::from_hex(0x00ac55)),
    r#type: Some(Color::from_hex(0x8070ff)),
    constant: Some(Color::from_hex(0xffa0a0)),
    operator: Some(Color::from_hex(0xffff00)),
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0xff8787)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xff8787)),
    green: None,
    cyan: Some(Color::from_hex(0x8070ff)),
    blue: Some(Color::from_hex(0xc777ef)),
    purple: Some(Color::from_hex(0xcdee56)),
    magenta: Some(Color::from_hex(0xff80ff)),
};
