//! sonofobsidian color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// sonofobsidian
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("sonofobsidian"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x22282a),
    fg: Color::from_hex(0xffffff),
    cursor: None,
    selection: Some(Color::from_hex(0x4f6164)),
    line_highlight: Some(Color::from_hex(0x32383a)),
    gutter: Some(Color::from_hex(0x3f4e49)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x99aa8a)),
    keyword: Some(Color::from_hex(0x93c763)),
    string: Some(Color::from_hex(0xec7600)),
    function: None,
    variable: Some(Color::from_hex(0xffffff)),
    r#type: Some(Color::from_hex(0x93c763)),
    constant: None,
    operator: Some(Color::from_hex(0xe8e2b7)),
    tag: Some(Color::from_hex(0x93c763)),
    error: Some(Color::from_hex(0xff0000)),
    warning: Some(Color::from_hex(0xffcd22)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff0000)),
    orange: None,
    yellow: Some(Color::from_hex(0xffcd22)),
    green: Some(Color::from_hex(0xec7600)),
    cyan: Some(Color::from_hex(0x93c763)),
    blue: None,
    purple: Some(Color::from_hex(0x93c763)),
    magenta: Some(Color::from_hex(0xa082bd)),
};
