//! spacegray color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// spacegray
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "spacegray",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x111314),
    fg: Color::from_hex(0xb3b8c4),
    cursor: Some(Color::from_hex(0x6c6c6c)),
    selection: Some(Color::from_hex(0x404040)),
    line_highlight: Some(Color::from_hex(0x303030)),
    gutter: Some(Color::from_hex(0x3e4853)),
    statusbar_bg: Some(Color::from_hex(0x303537)),
    statusbar_fg: Some(Color::from_hex(0xb3b8c4)),
    comment: Some(Color::from_hex(0x515f6a)),
    keyword: Some(Color::from_hex(0xa57a9e)),
    string: Some(Color::from_hex(0x95b47b)),
    function: Some(Color::from_hex(0xcc6666)),
    variable: Some(Color::from_hex(0xe5c078)),
    r#type: Some(Color::from_hex(0xe5c078)),
    constant: Some(Color::from_hex(0xc5735e)),
    operator: Some(Color::from_hex(0xa57a9e)),
    tag: Some(Color::from_hex(0x7d8fa3)),
    error: Some(Color::from_hex(0xc5735e)),
    warning: Some(Color::from_hex(0x7d8fa3)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xc5735e)),
    orange: None,
    yellow: Some(Color::from_hex(0x7d8fa3)),
    green: Some(Color::from_hex(0x95b47b)),
    cyan: Some(Color::from_hex(0xe5c078)),
    blue: Some(Color::from_hex(0xcc6666)),
    purple: Some(Color::from_hex(0xa57a9e)),
    magenta: Some(Color::from_hex(0x85a7a5)),
};
