//! stackoverflow color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// stackoverflow
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("stackoverflow"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xe9e9e9),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0xf4a83d)),
    selection: Some(Color::from_hex(0xb36a02)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0xa0a0a0)),
    statusbar_bg: Some(Color::from_hex(0xdab05b)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0x666666)),
    string: Some(Color::from_hex(0x800000)),
    function: None,
    variable: None,
    r#type: Some(Color::from_hex(0x000077)),
    constant: Some(Color::from_hex(0x800000)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0x6f6f6f)),
    warning: Some(Color::from_hex(0xcfcfcf)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x6f6f6f)),
    orange: None,
    yellow: Some(Color::from_hex(0xcfcfcf)),
    green: Some(Color::from_hex(0x800000)),
    cyan: Some(Color::from_hex(0x000077)),
    blue: None,
    purple: Some(Color::from_hex(0x666666)),
    magenta: Some(Color::from_hex(0x6b6b6b)),
};
