//! stonewashed-dark-gui color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// stonewashed-dark-gui
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("stonewashed-dark-gui"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xdddddd),
    cursor: None,
    selection: Some(Color::from_hex(0xffa8a8)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x585858)),
    statusbar_bg: Some(Color::from_hex(0xaf87d7)),
    statusbar_fg: Some(Color::from_hex(0xccc0b7)),
    comment: Some(Color::from_hex(0x949494)),
    keyword: Some(Color::from_hex(0xbb8888)),
    string: Some(Color::from_hex(0x7ba27b)),
    function: Some(Color::from_hex(0x5f5fd7)),
    variable: Some(Color::from_hex(0x7e74dd)),
    r#type: Some(Color::from_hex(0x788eab)),
    constant: Some(Color::from_hex(0xbb8888)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xaf0000)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xaf0000)),
    orange: None,
    yellow: Some(Color::from_hex(0x7e74dd)),
    green: Some(Color::from_hex(0x7ba27b)),
    cyan: Some(Color::from_hex(0x788eab)),
    blue: Some(Color::from_hex(0x5f5fd7)),
    purple: Some(Color::from_hex(0xbb8888)),
    magenta: Some(Color::from_hex(0xbb8888)),
};
