//! stonewashed-gui color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// stonewashed-gui
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "stonewashed-gui",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xf7f7f7),
    fg: Color::from_hex(0x000000),
    cursor: None,
    selection: Some(Color::from_hex(0x87d7ff)),
    line_highlight: Some(Color::from_hex(0xffffff)),
    gutter: Some(Color::from_hex(0x585858)),
    statusbar_bg: Some(Color::from_hex(0xaf87d7)),
    statusbar_fg: Some(Color::from_hex(0xccc0b7)),
    comment: Some(Color::from_hex(0x888888)),
    keyword: Some(Color::from_hex(0x5f0000)),
    string: Some(Color::from_hex(0x005f00)),
    function: Some(Color::from_hex(0x5f5fd7)),
    variable: Some(Color::from_hex(0x5f5fd7)),
    r#type: Some(Color::from_hex(0x00005f)),
    constant: Some(Color::from_hex(0x5f0000)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xaf0000)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xaf0000)),
    orange: None,
    yellow: Some(Color::from_hex(0x5f00ff)),
    green: Some(Color::from_hex(0x005f00)),
    cyan: Some(Color::from_hex(0x00005f)),
    blue: Some(Color::from_hex(0x5f5fd7)),
    purple: Some(Color::from_hex(0x5f0000)),
    magenta: Some(Color::from_hex(0x5f0000)),
};
