//! stonewashed-dark-256 color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// stonewashed-dark-256
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("stonewashed-dark-256"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xeeeeee),
    cursor: None,
    selection: Some(Color::from_hex(0x0087af)),
    line_highlight: Some(Color::from_hex(0x303030)),
    gutter: Some(Color::from_hex(0x585858)),
    statusbar_bg: Some(Color::from_hex(0xaf87d7)),
    statusbar_fg: Some(Color::from_hex(0xafaf87)),
    comment: Some(Color::from_hex(0x6c6c6c)),
    keyword: Some(Color::from_hex(0xaf0000)),
    string: Some(Color::from_hex(0x005f00)),
    function: Some(Color::from_hex(0x5f5fd7)),
    variable: Some(Color::from_hex(0x5f5fd7)),
    r#type: Some(Color::from_hex(0x00005f)),
    constant: Some(Color::from_hex(0xaf0000)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xaf0000)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xaf0000)),
    orange: None,
    yellow: Some(Color::from_hex(0x5f00ff)),
    green: Some(Color::from_hex(0x005f00)),
    cyan: Some(Color::from_hex(0x00005f)),
    blue: Some(Color::from_hex(0x5f5fd7)),
    purple: Some(Color::from_hex(0xaf0000)),
    magenta: Some(Color::from_hex(0x875f00)),
};
