//! strawimodo color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// strawimodo
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("strawimodo"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x393939),
    fg: Color::from_hex(0xc3dafd),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x5a647e)),
    line_highlight: Some(Color::from_hex(0x333435)),
    gutter: Some(Color::from_hex(0x797979)),
    statusbar_bg: Some(Color::from_hex(0xb2c867)),
    statusbar_fg: Some(Color::from_hex(0x222222)),
    comment: Some(Color::from_hex(0xbc9458)),
    keyword: Some(Color::from_hex(0xcc7833)),
    string: Some(Color::from_hex(0xb2c867)),
    function: Some(Color::from_hex(0xf9d07f)),
    variable: Some(Color::from_hex(0xd0d0ff)),
    r#type: Some(Color::from_hex(0xd78a42)),
    constant: Some(Color::from_hex(0x78acc9)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: Some(Color::from_hex(0x000000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0x000000)),
    green: Some(Color::from_hex(0xb2c867)),
    cyan: Some(Color::from_hex(0xd78a42)),
    blue: Some(Color::from_hex(0xf9d07f)),
    purple: Some(Color::from_hex(0xcc7833)),
    magenta: Some(Color::from_hex(0xcc7833)),
};
