//! strange color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// strange
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("strange"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x060606),
    fg: Color::from_hex(0xffffff),
    cursor: None,
    selection: Some(Color::from_hex(0xc0ffc0)),
    line_highlight: Some(Color::from_hex(0x111111)),
    gutter: Some(Color::from_hex(0x3d464c)),
    statusbar_bg: Some(Color::from_hex(0x222222)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0x777777)),
    keyword: Some(Color::from_hex(0x5d6065)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0xbbbaab)),
    r#type: Some(Color::from_hex(0x999999)),
    constant: Some(Color::from_hex(0x818f71)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xffa500)),
    green: None,
    cyan: Some(Color::from_hex(0x999999)),
    blue: None,
    purple: Some(Color::from_hex(0x5d6065)),
    magenta: Some(Color::from_hex(0xbbbaab)),
};
