//! summerfruit color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// summerfruit
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("summerfruit"),
    author: Cow::Borrowed(""),
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: None,
    selection: None,
    line_highlight: Some(Color::from_hex(0xeff2f4)),
    gutter: Some(Color::from_hex(0xeeeeee)),
    statusbar_bg: Some(Color::from_hex(0x43c464)),
    statusbar_fg: Some(Color::from_hex(0xffffff)),
    comment: Some(Color::from_hex(0x22a21f)),
    keyword: Some(Color::from_hex(0xfb660a)),
    string: Some(Color::from_hex(0x0086d2)),
    function: Some(Color::from_hex(0xff0086)),
    variable: Some(Color::from_hex(0xff0086)),
    r#type: Some(Color::from_hex(0x70796b)),
    constant: Some(Color::from_hex(0x0086d2)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xffffff)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xffffff)),
    orange: None,
    yellow: Some(Color::from_hex(0xfd8900)),
    green: Some(Color::from_hex(0x0086d2)),
    cyan: Some(Color::from_hex(0x70796b)),
    blue: Some(Color::from_hex(0xff0086)),
    purple: Some(Color::from_hex(0xfb660a)),
    magenta: Some(Color::from_hex(0xff0007)),
};
