//! tangoshady color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// tangoshady
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("tangoshady"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x272727),
    fg: Color::from_hex(0xeeeeec),
    cursor: None,
    selection: Some(Color::from_hex(0x363636)),
    line_highlight: Some(Color::from_hex(0xd3d7cf)),
    gutter: Some(Color::from_hex(0x666666)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x3465a4)),
    keyword: Some(Color::from_hex(0xc4a000)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x06989a)),
    r#type: Some(Color::from_hex(0x4e9a06)),
    constant: Some(Color::from_hex(0xcc0000)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xd3d7cf)),
    warning: Some(Color::from_hex(0xcc0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xd3d7cf)),
    orange: None,
    yellow: Some(Color::from_hex(0xcc0000)),
    green: None,
    cyan: Some(Color::from_hex(0x4e9a06)),
    blue: None,
    purple: Some(Color::from_hex(0xc4a000)),
    magenta: Some(Color::from_hex(0x75507b)),
};
