//! tango-morning color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// tango-morning
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "tango-morning",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xeeeeec),
    fg: Color::from_hex(0x2e3436),
    cursor: Some(Color::from_hex(0x8ae234)),
    selection: Some(Color::from_hex(0xd3d7cf)),
    line_highlight: Some(Color::from_hex(0x555753)),
    gutter: Some(Color::from_hex(0x204a87)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x888a85)),
    keyword: Some(Color::from_hex(0x8f5902)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x204a87)),
    r#type: Some(Color::from_hex(0x4e9a06)),
    constant: Some(Color::from_hex(0xce5c00)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xeeeeec)),
    warning: Some(Color::from_hex(0xcc0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xeeeeec)),
    orange: None,
    yellow: Some(Color::from_hex(0xcc0000)),
    green: Some(Color::from_hex(0xeeeeec)),
    cyan: Some(Color::from_hex(0x4e9a06)),
    blue: None,
    purple: Some(Color::from_hex(0x8f5902)),
    magenta: Some(Color::from_hex(0x204a87)),
};
