//! tayra color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};
use alloc::borrow::Cow;

/// tayra
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: Cow::Borrowed("tayra"),
    author: Cow::Borrowed(""),
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x262626),
    fg: Color::from_hex(0xd0d0d0),
    cursor: Some(Color::from_hex(0xffff87)),
    selection: Some(Color::from_hex(0x3a3a3a)),
    line_highlight: Some(Color::from_hex(0x3a3a3a)),
    gutter: Some(Color::from_hex(0x444444)),
    statusbar_bg: Some(Color::from_hex(0x121212)),
    statusbar_fg: Some(Color::from_hex(0x87d7af)),
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0xd7d75f)),
    string: Some(Color::from_hex(0xafd75f)),
    function: None,
    variable: Some(Color::from_hex(0xd7875f)),
    r#type: Some(Color::from_hex(0xd75f5f)),
    constant: Some(Color::from_hex(0xd7af5f)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xff0000)),
    warning: Some(Color::from_hex(0xff0000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff0000)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0xafd75f)),
    cyan: Some(Color::from_hex(0xd75f5f)),
    blue: None,
    purple: Some(Color::from_hex(0xd7d75f)),
    magenta: Some(Color::from_hex(0xd7d787)),
};
