//! tchaba color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// tchaba
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "tchaba",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x121212),
    fg: Color::from_hex(0xd0d0d0),
    cursor: None,
    selection: Some(Color::from_hex(0xd7ff87)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0xbcbcbc)),
    statusbar_bg: None,
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x808080)),
    keyword: Some(Color::from_hex(0x87ff00)),
    string: Some(Color::from_hex(0x5f87af)),
    function: None,
    variable: Some(Color::from_hex(0xd75f00)),
    r#type: Some(Color::from_hex(0x87ff00)),
    constant: Some(Color::from_hex(0xd75f00)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0x800000)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0x800000)),
    orange: None,
    yellow: Some(Color::from_hex(0xff0000)),
    green: Some(Color::from_hex(0x5f87af)),
    cyan: Some(Color::from_hex(0x87ff00)),
    blue: None,
    purple: Some(Color::from_hex(0x87ff00)),
    magenta: Some(Color::from_hex(0x5f5faf)),
};
