//! tender color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// tender
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "tender",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x282828),
    fg: Color::from_hex(0xeeeeee),
    cursor: None,
    selection: Some(Color::from_hex(0x040404)),
    line_highlight: Some(Color::from_hex(0x323232)),
    gutter: Some(Color::from_hex(0x444444)),
    statusbar_bg: Some(Color::from_hex(0x666666)),
    statusbar_fg: Some(Color::from_hex(0x1d1d1d)),
    comment: Some(Color::from_hex(0x666666)),
    keyword: Some(Color::from_hex(0xb3deef)),
    string: Some(Color::from_hex(0xd3b987)),
    function: Some(Color::from_hex(0xb3deef)),
    variable: Some(Color::from_hex(0xb3deef)),
    r#type: Some(Color::from_hex(0x73cef4)),
    constant: Some(Color::from_hex(0xffc24b)),
    operator: Some(Color::from_hex(0xf43753)),
    tag: None,
    error: Some(Color::from_hex(0xf43753)),
    warning: Some(Color::from_hex(0xf43753)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf43753)),
    orange: None,
    yellow: Some(Color::from_hex(0xf43753)),
    green: Some(Color::from_hex(0xd3b987)),
    cyan: Some(Color::from_hex(0x73cef4)),
    blue: Some(Color::from_hex(0xb3deef)),
    purple: Some(Color::from_hex(0xb3deef)),
    magenta: Some(Color::from_hex(0xc9d05c)),
};
