//! tir_black color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// tir_black
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "tir_black",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xf6f3e8),
    cursor: Some(Color::from_hex(0xffffff)),
    selection: Some(Color::from_hex(0x262d51)),
    line_highlight: Some(Color::from_hex(0x121212)),
    gutter: Some(Color::from_hex(0x3d3d3d)),
    statusbar_bg: Some(Color::from_hex(0x202020)),
    statusbar_fg: Some(Color::from_hex(0xcccccc)),
    comment: Some(Color::from_hex(0x7c7c7c)),
    keyword: Some(Color::from_hex(0x96cbfe)),
    string: Some(Color::from_hex(0xa8ff60)),
    function: Some(Color::from_hex(0xffd2a7)),
    variable: Some(Color::from_hex(0xc6c5fe)),
    r#type: Some(Color::from_hex(0xffffb6)),
    constant: Some(Color::from_hex(0x99cc99)),
    operator: None,
    tag: Some(Color::from_hex(0xe18964)),
    error: Some(Color::from_hex(0xff5f5f)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff5f5f)),
    orange: None,
    yellow: Some(Color::from_hex(0xe18964)),
    green: Some(Color::from_hex(0xa8ff60)),
    cyan: Some(Color::from_hex(0xffffb6)),
    blue: Some(Color::from_hex(0xffd2a7)),
    purple: Some(Color::from_hex(0x96cbfe)),
    magenta: Some(Color::from_hex(0x96cbfe)),
};
