//! tutticolori color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// tutticolori
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "tutticolori",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0xcccecf)),
    selection: Some(Color::from_hex(0xdbebff)),
    line_highlight: Some(Color::from_hex(0xdbebff)),
    gutter: Some(Color::from_hex(0xaabbcc)),
    statusbar_bg: Some(Color::from_hex(0xffffff)),
    statusbar_fg: Some(Color::from_hex(0x888888)),
    comment: Some(Color::from_hex(0x999999)),
    keyword: Some(Color::from_hex(0x2f6f9f)),
    string: None,
    function: None,
    variable: Some(Color::from_hex(0x3a1d72)),
    r#type: Some(Color::from_hex(0x699d36)),
    constant: Some(Color::from_hex(0xd44950)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0xf9f2ce)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xf9f2ce)),
    orange: None,
    yellow: Some(Color::from_hex(0x2f6f9f)),
    green: None,
    cyan: Some(Color::from_hex(0x699d36)),
    blue: None,
    purple: Some(Color::from_hex(0x2f6f9f)),
    magenta: Some(Color::from_hex(0x222222)),
};
