//! vanzan_color color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// vanzan_color
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "vanzan_color",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x080a0c),
    fg: Color::from_hex(0xb0b0b0),
    cursor: Some(Color::from_hex(0xb8b4b0)),
    selection: Some(Color::from_hex(0x102030)),
    line_highlight: Some(Color::from_hex(0x1c281c)),
    gutter: Some(Color::from_hex(0x68727c)),
    statusbar_bg: Some(Color::from_hex(0x181a1c)),
    statusbar_fg: None,
    comment: Some(Color::from_hex(0x404a5c)),
    keyword: Some(Color::from_hex(0x60a0b0)),
    string: Some(Color::from_hex(0xa05050)),
    function: Some(Color::from_hex(0xd0a040)),
    variable: Some(Color::from_hex(0x5080a0)),
    r#type: Some(Color::from_hex(0x909060)),
    constant: Some(Color::from_hex(0x808080)),
    operator: Some(Color::from_hex(0x5070a0)),
    tag: None,
    error: Some(Color::from_hex(0xa02000)),
    warning: None,
    info: None,
    success: None,
    red: Some(Color::from_hex(0xa02000)),
    orange: None,
    yellow: Some(Color::from_hex(0xa05050)),
    green: Some(Color::from_hex(0xa05050)),
    cyan: Some(Color::from_hex(0x909060)),
    blue: Some(Color::from_hex(0xd0a040)),
    purple: Some(Color::from_hex(0x60a0b0)),
    magenta: Some(Color::from_hex(0x706080)),
};
