//! warriors-away color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// warriors-away
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "warriors-away",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1a2372),
    fg: Color::from_hex(0xd1b856),
    cursor: Some(Color::from_hex(0xf9f9f9)),
    selection: Some(Color::from_hex(0xf9f9ff)),
    line_highlight: Some(Color::from_hex(0x222e30)),
    gutter: Some(Color::from_hex(0xd3ac0f)),
    statusbar_bg: Some(Color::from_hex(0xbd9800)),
    statusbar_fg: Some(Color::from_hex(0x192224)),
    comment: Some(Color::from_hex(0x5e6c70)),
    keyword: Some(Color::from_hex(0xbd9800)),
    string: Some(Color::from_hex(0xe4f1ff)),
    function: Some(Color::from_hex(0xe4f1ff)),
    variable: Some(Color::from_hex(0xbd9800)),
    r#type: Some(Color::from_hex(0xb6c6e3)),
    constant: Some(Color::from_hex(0xa1a6a8)),
    operator: Some(Color::from_hex(0xbd9800)),
    tag: Some(Color::from_hex(0xbd9800)),
    error: Some(Color::from_hex(0xa1a6a8)),
    warning: Some(Color::from_hex(0xa1a6a8)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xa1a6a8)),
    orange: None,
    yellow: Some(Color::from_hex(0xa1a6a8)),
    green: Some(Color::from_hex(0xe4f1ff)),
    cyan: Some(Color::from_hex(0xb6c6e3)),
    blue: Some(Color::from_hex(0xe4f1ff)),
    purple: Some(Color::from_hex(0xbd9800)),
    magenta: Some(Color::from_hex(0xbd9800)),
};
