//! watermark color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// watermark
///
/// Variant: Dark
/// Contrast: Normal
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "watermark",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::Normal,
    bg: Color::from_hex(0x1a202a),
    fg: Color::from_hex(0x8b9aaa),
    cursor: Some(Color::from_hex(0xcad5c0)),
    selection: Some(Color::from_hex(0x43d5ff)),
    line_highlight: None,
    gutter: Some(Color::from_hex(0x8095d5)),
    statusbar_bg: None,
    statusbar_fg: Some(Color::from_hex(0x203ad5)),
    comment: Some(Color::from_hex(0x559988)),
    keyword: Some(Color::from_hex(0xcac0c0)),
    string: None,
    function: Some(Color::from_hex(0xa090a0)),
    variable: Some(Color::from_hex(0xa090b0)),
    r#type: Some(Color::from_hex(0x6ac0ba)),
    constant: Some(Color::from_hex(0x70a0de)),
    operator: Some(Color::from_hex(0xaa9a45)),
    tag: None,
    error: Some(Color::from_hex(0xc0c0c0)),
    warning: Some(Color::from_hex(0x800000)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xc0c0c0)),
    orange: None,
    yellow: Some(Color::from_hex(0x800000)),
    green: None,
    cyan: Some(Color::from_hex(0x6ac0ba)),
    blue: Some(Color::from_hex(0xa090a0)),
    purple: Some(Color::from_hex(0xcac0c0)),
    magenta: Some(Color::from_hex(0xc0a0b0)),
};
