//! zazen color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// zazen
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "zazen",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x000000),
    fg: Color::from_hex(0xcccccc),
    cursor: None,
    selection: Some(Color::from_hex(0x515151)),
    line_highlight: Some(Color::from_hex(0x555555)),
    gutter: Some(Color::from_hex(0x555555)),
    statusbar_bg: Some(Color::from_hex(0x727272)),
    statusbar_fg: Some(Color::from_hex(0x000000)),
    comment: Some(Color::from_hex(0x777777)),
    keyword: Some(Color::from_hex(0x666666)),
    string: Some(Color::from_hex(0x838383)),
    function: Some(Color::from_hex(0xeeeeee)),
    variable: Some(Color::from_hex(0xffffff)),
    r#type: Some(Color::from_hex(0xeeeeee)),
    constant: Some(Color::from_hex(0x838383)),
    operator: None,
    tag: None,
    error: Some(Color::from_hex(0x6f6f6f)),
    warning: Some(Color::from_hex(0xcfcfcf)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0x6f6f6f)),
    orange: None,
    yellow: Some(Color::from_hex(0xcfcfcf)),
    green: Some(Color::from_hex(0x838383)),
    cyan: Some(Color::from_hex(0xeeeeee)),
    blue: Some(Color::from_hex(0xeeeeee)),
    purple: Some(Color::from_hex(0x666666)),
    magenta: Some(Color::from_hex(0x6b6b6b)),
};
