//! zellner color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// zellner
///
/// Variant: Light
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "zellner",
    author: "",
    variant: Variant::Light,
    contrast: Contrast::High,
    bg: Color::from_hex(0xffffff),
    fg: Color::from_hex(0x000000),
    cursor: Some(Color::from_hex(0x000000)),
    selection: Some(Color::from_hex(0xffff00)),
    line_highlight: Some(Color::from_hex(0xe5e5e5)),
    gutter: Some(Color::from_hex(0xa52a2a)),
    statusbar_bg: Some(Color::from_hex(0xa9a9a9)),
    statusbar_fg: Some(Color::from_hex(0xffff00)),
    comment: Some(Color::from_hex(0xff0000)),
    keyword: Some(Color::from_hex(0xa52a2a)),
    string: None,
    function: Some(Color::from_hex(0x0000ff)),
    variable: Some(Color::from_hex(0x0000ff)),
    r#type: Some(Color::from_hex(0x0000ff)),
    constant: Some(Color::from_hex(0xff00ff)),
    operator: None,
    tag: Some(Color::from_hex(0x006400)),
    error: Some(Color::from_hex(0xff0000)),
    warning: Some(Color::from_hex(0xa020f0)),
    info: None,
    success: None,
    red: Some(Color::from_hex(0xff0000)),
    orange: None,
    yellow: Some(Color::from_hex(0xa020f0)),
    green: Some(Color::from_hex(0xffffff)),
    cyan: Some(Color::from_hex(0x0000ff)),
    blue: Some(Color::from_hex(0x0000ff)),
    purple: Some(Color::from_hex(0xa52a2a)),
    magenta: Some(Color::from_hex(0xa020f0)),
};
