//! zmrok color theme.
//!
//! Auto-generated by `cargo xtask generate vim` — do not edit.

use crate::{Color, Contrast, Theme, Variant};

/// zmrok
///
/// Variant: Dark
/// Contrast: High
/// Source: vim (vim-colorschemes)
pub const THEME: Theme = Theme {
    name: "zmrok",
    author: "",
    variant: Variant::Dark,
    contrast: Contrast::High,
    bg: Color::from_hex(0x141414),
    fg: Color::from_hex(0xf8f8f8),
    cursor: None,
    selection: None,
    line_highlight: Some(Color::from_hex(0x0d0d0d)),
    gutter: Some(Color::from_hex(0x777777)),
    statusbar_bg: Some(Color::from_hex(0x202020)),
    statusbar_fg: Some(Color::from_hex(0xf8f8f8)),
    comment: Some(Color::from_hex(0x888888)),
    keyword: Some(Color::from_hex(0xa56a30)),
    string: Some(Color::from_hex(0xd9ff77)),
    function: Some(Color::from_hex(0xc7ca87)),
    variable: Some(Color::from_hex(0xc7ca87)),
    r#type: Some(Color::from_hex(0xc7ca87)),
    constant: Some(Color::from_hex(0xcf593c)),
    operator: Some(Color::from_hex(0xdfcc77)),
    tag: None,
    error: None,
    warning: None,
    info: None,
    success: None,
    red: None,
    orange: None,
    yellow: None,
    green: Some(Color::from_hex(0xd9ff77)),
    cyan: Some(Color::from_hex(0xc7ca87)),
    blue: Some(Color::from_hex(0xc7ca87)),
    purple: Some(Color::from_hex(0xa56a30)),
    magenta: None,
};
